### ISSUE TITLE
Права для Oauth-токен

### ISSUE THREAD

**Issue by allmoney** [AlexxIT/YandexStation#10]
В инструкции не описано какие права выдать для токена.

**Comment by AlexxIT** [comment]
@allmoney токен запрашивается от имени приложения Яндекс.Музыка. Там нет указания прав в запросе. Только это `'grant_type': 'password'`.

**Comment by allmoney** [comment]
Вот по этой инструкции токен получал, не получилось с ним... Как-то по другому его надо получить?
https://yandex.ru/dev/oauth/doc/dg/tasks/get-oauth-token-docpage/

**Comment by AlexxIT** [comment]
Не знаю всех особенностей получения токена Яндекса. Может client_id важен...
