### ISSUE TITLE
Авторизация по токену

### ISSUE THREAD

**Issue by Drafteed** [AlexxIT/YandexStation#100]
После обновления на 3.0.0, колонка пропала. Была авторизована по токену. В README.MD вся информация про данный метод авторизации пропала. Можно попрощаться с этим типом авторизации?

**Comment by AlexxIT** [comment]
Его очень сложно поддерживать. В чём проблема через аккаунт Яндекса? Там тоже получается токен, только с более высокими правами

**Comment by Drafteed** [comment]
Не очень люблю хранить креденшиалсы в открытом виде, чисто даже эстетически. Тем более, что в Яндексе у меня много чего где привязано, такси, карты всякие и т.д.

**Comment by AlexxIT** [comment]
Пароль не сохраняется! Сохраняется только токен. И поддерживается двухцветная авторизация.
