### ISSUE TITLE
Не появляется колонка

### ISSUE THREAD

**Issue by moskovskiy82** [AlexxIT/YandexStation#101]
Удалил версию 2.4 которая так и не работала. Удалил station.json *не помню точно название файла) в корне config.
Проверил что в custom_components ничего не осталось.
Установил 3.0
Настроил через интеграции. По Яндекс паспорту авторизация пройдена
В core.config_entries появились x_token и cookie
station.json не воявился. Но как я понимаю он теперь в реестре?
В логах пусто.
Но вот сама колонка ни как устройство ни как media_player не появились.
В какую хотя бы сторону смотреть?

**Comment by AlexxIT** [comment]
Включите и покажите логи

```yaml
yandex_station:
  debug: true
```

**Comment by AlexxIT** [comment]
Без ответа
