### ISSUE TITLE
empty media_id

### ISSUE THREAD

**Issue by merccooper** [AlexxIT/YandexStation#102]
если пытаюсь ввести текст в карточке получаю ошибку empty media_id, если вводить текст на английском такой проблемы нет. 

Может я что-то пропустил в настройках?

**Comment by AlexxIT** [comment]
"Настройки - О системе" можно посмотреть?

**Comment by merccooper** [comment]
вот это?

## System Health

version | 2020.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.79-v7l
arch | armv7l
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4944
Installed Version | 1.9.0
Stage | running
Available Repositories | 704
Installed Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 26 января 2021 г., 3:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.9
-- | --
update_channel | stable
supervisor_version | 2020.12.7
docker_version | 19.03.13
disk_total | 57.8 GB
disk_used | 3.5 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.6.0), Samba share (9.3.0), RPC Shutdown (2.2), Node-RED (7.2.11), Spotify Connect (0.8.2), File editor (5.2.0), ADB - Android Debug Bridge (0.6.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
mode | storage
views | 1
resources | 0

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by AlexxIT** [comment]
Добавьте в конфиг

```yaml
yandex_station:
  debug: true
```

И покажите логи

**Comment by shprota** [comment]
Добавьте в конфиг:

```yaml
yandex_station:
  tts_service_name: alice_say
```  
Почему-то параграф про конфликт TTS из README пропал пару месяцев назад.

**Comment by AlexxIT** [comment]
Конфликт TTS был поправлен. Поэтому и пропал. Возможно новые какие-то проблемы

**Comment by shprota** [comment]
Возможно, новые. У меня был тот же эффект, что у ТС, и вылечился обзыванием TTS. Основным TTS у меня прописан Яндекс:

```yaml
tts:
  platform: yandextts
  api_key: "xxxxxxxxx"
  language: "ru-RU"
  voice: "oksana"
  emotion: "evil"
```

**Comment by AlexxIT** [comment]
Может с yandextts не совместим. С google_translate работает нормально

**Comment by alparo** [comment]
Со включенным дебагом и на последней бете у меня такое в логах:

2021-02-01 17:05:01 WARNING (MainThread) [custom_components.yandex_station.media_player] Получено пустое media_id
2021-02-01 17:05:19 ERROR (MainThread) [homeassistant.components.tts] ID3 tag error: can't sync to MPEG frame
2021-02-01 17:05:20 WARNING (MainThread) [custom_components.yandex_station.media_player] Получено пустое media_id

что с google tts в конфиге, что без него - не работает произнесение фраз на русском.

**Comment by AlexxIT** [comment]
Вероятно не актуально не сегодняшний день
