### ISSUE TITLE
Не заходит по логину и паролю

### ISSUE THREAD

**Issue by shelasmax** [AlexxIT/YandexStation#103]
При вводе корректных логина и пароля в настройках интеграции опять появляется окно ввода логина и пароля.
При вводе некорректных данных пишет **Неверный пароль**

**Comment by AlexxIT** [comment]
Может быть это очень старый аккаунт времён народа. С ними проблемы

**Comment by shelasmax** [comment]
> Может быть это очень старый аккаунт времён народа. С ними проблемы

Спасибо, попробую. Получается и Алису и все остальные сервисы на новый акк переводить? Или там алиас можно сделать какой-то?

**Comment by AlexxIT** [comment]
Можно попробовать включить двухфакторную авторизацию. Если не включится - писать в поддержку Яндекса, они починят. Были примеры

**Comment by G1K** [comment]
у меня та же ситуация на одном из аккаунтов, подскажи пожалуйста в какую именно поддержку стоит писать. мотивация как сторонний компонент для них нормально? или что-то другое стоит написать?

**Comment by G1K** [comment]
двухфакторку пробовал , но не помогало. 2 раза включал и пароль с ключа не подходил. но вот выключил совсем двухфакторку и заработало на проблемном старом аккаунте!

**Comment by AlexxIT** [comment]
Если кто-то пришлёт мне в личку Телеграм проблемный старый аккаунт, я могу попытаться победить проблему. На моих аккаунтах проблема не повторяется.

**Comment by fanagor123** [comment]
аналогичная проблема. Решилось включением двухфакторной активации в акк Яндекс, и ее выключением на старый пароль. Видимо что-то в яндексе..

**Comment by dmatora** [comment]
@fanagor123 спасибо, помогло. Привет всем олдфагам :)

**Comment by shelasmax** [comment]
> аналогичная проблема. Решилось включением двухфакторной активации в акк Яндекс, и ее выключением на старый пароль. Видимо что-то в яндексе..

у меня тоже получилось. благодарю!

**Comment by AlexxIT** [comment]
Можно прислать мне в телеграмм логин/пароль. Я попробую починить

**Comment by drdic** [comment]
Может кому поможет. После переустановки системы и восстановления из бекапа возникла эта же проблема. Интеграция Яндекс.Станция не добавлялась, выскакивало окошко, что логин и пароль не подходят и ссылка на эту страничку. Как-тот давно, аналогичная проблема уже была. После переписки с поддержкой Яндекс, махания бубном, курением мануалов, пришел к выводу, что каким то чудным образом влияет протокол IPv6. Тогда я отключил протокол IPv6 полностью, и на роутере и у провайдера, и все получилось. Так и сейчас. Отключил протокол IPv6 на роутере. И повторил добавление интеграции и ввод логина и пароля. И все получилось....

**Comment by AlexxIT** [comment]
У кого проблема **Аккаунт не поддерживается** - попробуйте последнюю мастер версию.

**Comment by DisDis** [comment]
У меня была аналогичная проблема, решилась включением двух факторной авторизации и одноразовым паролем для входа

**Comment by AlexxIT** [comment]
Думаю Яндекс просто увидел, что включение двухфакторки было с того же интернета, где и ваш сервер ХА. И перестал его подозревать как злоумышленника.

**Comment by runnerfanspb** [comment]
Переустановил интеграцию. Не заходит по логину и паролю. Двухфакторную аутентификацию включал и выключал. Стоит последняя версия интеграции. Что можно сделать?

**Comment by Mishania210701** [comment]
Та же история.Может уже появилось решение

**Comment by AlexxIT** [comment]
Решение появилось довольно давно, это авторизация через куки. Если она не заработает - ВНИМАТЕЛЬНО читаем подсказки.

**Comment by DisDis** [comment]
я только вчера пробовал заходить, работает через логин и одноразовый пароль.(чистая установка интеграции)

**Comment by AlexxIT** [comment]
Исправлено в последней бета-версии

**Comment by bulava92** [comment]
<img width="466" alt="Screenshot 2023-02-20 at 17 58 50" src="https://user-images.githubusercontent.com/96921934/220140349-4778d0fa-c7de-4824-bbbf-0c3d7264f25e.png">
ввожу 100% верные данные, не входит.
включал/отключал/включал двухфакторку
менял роутер, менял провайдера
не входит.

**Comment by bulava92** [comment]
> авторизация через куки

какие куки и где почитать?

**Comment by rugameuser** [comment]
This issue can be resolved with opening static url. Usually you have the field called track_id in api, so by using this field you can pass this "action request".
 - try to login and save track_id somewhere
 - open link "https://passport.yandex.com/auth?track_id="+$track_id_here+"&retpath=https://passport.yandex.com/profile"
 - usually this link asked for entering a phone number or captcha
 - try to login again with the same track_id (don't try to get a new track_id in this step)
 - done
Also this issue probably will never happen if you will use the same "device_id" after resolve this issue in the first time.

**Comment by semikor** [comment]
Переключил одну из колонок обратно (на ранее использовавшийся аккаунт), но сохраненный Токен не принимает, при вводе логина/пароля выдает ошибку. Включал/выключал 2х факторный вход - ошибка. Обновил пароль, включил/выключил 2х факторный вход - всё равно ошибка. IP6 отключен давно.
Где брать эти куки и что с ними делать?

**Comment by BolikStav** [comment]
Что может означать?
"Too many devices. Some devices may not work. Buy a subscription for full functionality!"
"Bad oAuth token"
Устройств меньше чем 10, яндекс плюс подключен, токен проверял
