### ISSUE TITLE
HA не видит ни розетку, ни лампочку

### ISSUE THREAD

**Issue by y0rker** [AlexxIT/YandexStation#104]
HA не видит ни розетку, ни лампочку.
Установил по инструкции, но стал видеть только саму яндекс колонку мини
![image](https://user-images.githubusercontent.com/5592102/103297849-2b35b300-4a0a-11eb-96ed-2683cdc1e7a8.png)

**Comment by AlexxIT** [comment]
В конфиг прописали? Регистр в именах верный?

**Comment by ilvi80** [comment]
У меня такая же ситуация. в конфиге прописано, но не видит ни розетку, ни другие устройства

**Comment by AlexxIT** [comment]
Покажите конфиг

**Comment by y0rker** [comment]
yandex_smart_home:
  filter:
    include_domains:
      - switch
      - light
      
yandex_smart_home_fix:

yandex_station:
  username: "kidav5@yandex.ru"
  password: "!yH3hZuPqYC7cWm"

**Comment by ilvi80** [comment]
> Покажите конфиг

в конфиг прописал и все увидело, спасибо
 include:
  - Светильник
  - Телевизор
  - Пульт
  - Подсветка
  - Елка

**Comment by AlexxIT** [comment]
Чтоб розетки и лампочки попали в ХА - их необходимо указать в конфиге
