### ISSUE TITLE
Интеграция перестала работать

### ISSUE THREAD

**Issue by uPagge** [AlexxIT/YandexStation#105]
Пользовался ей где-то полгода. Недавно отвалились все устройства, писало не доступно. Ну ладно думаю, перезапущу интеграцию. Удилал старую, добавил новую. все заработало до первой перезагрузки. Теперь снова статус недоступно

**Comment by AlexxIT** [comment]
Ошибки в логах?

**Comment by uPagge** [comment]
Если речь про логи, которые журнал логов в HA, то там только это

![изображение](https://user-images.githubusercontent.com/40397740/103474164-28dcab80-4db2-11eb-8893-1c9e6dfac70f.png)

**Comment by uPagge** [comment]
После перезагрузки HA

![изображение](https://user-images.githubusercontent.com/40397740/103474384-54609580-4db4-11eb-9d4d-285fe203031a.png)

![изображение](https://user-images.githubusercontent.com/40397740/103474389-5c203a00-4db4-11eb-9038-be41ddc49ea5.png)

**Comment by AlexxIT** [comment]
У вас что-то с интернетом. Компонент не может подключиться к серверам Яндекса

**Comment by uPagge** [comment]
Хм, возможно проблема с vpn, но до этого полгода все работало. И временами колонка опять начинает работать, хотя впн работает нон-стоп 24/7

**Comment by AlexxIT** [comment]
Не актуально
