### ISSUE TITLE
Станция мини перестала работать с телеграм

### ISSUE THREAD

**Issue by itpcss** [AlexxIT/YandexStation#106]
После последнего обновления, в телеграмме перестала отвечать станция мини, до обновления было все хорошо.

**Comment by AlexxIT** [comment]
Скорее всего пропал локальный режим. Обложку показывает?

**Comment by itpcss** [comment]
Да верно! обложку перестало показывать тоже, хотя когда ставил музыку на колонку обложка появлялась, сейчас попробовал ее нет.

**Comment by itpcss** [comment]
Проверил еще вывод звука с яндекс музыки, по этой настройке в мануале:
script:
  yandex_doorbell:
    alias: Дверной звонок
    sequence:
    - service: media_player.play_media
      entity_id: media_player.yandex_station_моя станция
      data:
        media_content_id: https://music.yandex.ru/album/993803/track/9381260
        media_content_type: 

Звук также не работает, пишет что сработало, но колонка молчит!

**Comment by AlexxIT** [comment]
Проигрывание ссылок работает только в локальном режиме. Ваш локальный режим поломался.
Почитайте про проблемы с локальным режимом в документации
