### ISSUE TITLE
Лампочка добавляется без устройства

### ISSUE THREAD

**Issue by poofeg** [AlexxIT/YandexStation#108]
Умная лампочка Яндекса 2 (YNDX-00010) добавляется только как объект, без устройства. Яндекса Станция при этом добавляется нормально. Из-за этого не могу добавить лампочку в сцену. Других устройств яндекса нет, поэтому не могу понять, это нормальное поведение или нет. Если нормальное, то я бы добавил это в README.

**Comment by AlexxIT** [comment]
На данный момент устройства есть только для колонок

**Comment by poofeg** [comment]
Однако, в тему Яндекс лампы, я понял, что она от Tuya, а значит ей можно управлять с помощью [localtuya](https://github.com/rospogrigio/localtuya).

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.0

**Comment by almirus** [comment]
@AlexxIT чтобы подтянули как устройства, после обновления интеграции нужно перепривязать устройства с удалением?

**Comment by AlexxIT** [comment]
Дополнительных действий после обновления не требуется. Просто должен быть верно настроен конфиг include.
