### ISSUE TITLE
Проблемы с новой прошивкой Яндекс.Станции Мини

### ISSUE THREAD

**Issue by Zuz666** [AlexxIT/YandexStation#112]
@AlexxIT  спасибо за компонент, крутая штука!

Не знаю когда, но появилась проблема (возможно, после обновления HA).

Простой скрипт:
```yaml
alias: тест вопроса
  sequence:
  - service: media_player.play_media
    entity_id: media_player.yandex_station
    data:
      media_content_id: Какая влажность дома?
      media_content_type: question
  mode: single
```
Вызывает зависание в homeassistant.components.media_player и как следствие компонент перестаёт работать.

В логе:
```
2021-01-13 21:36:52 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_session] Login in Yandex with token
2021-01-13 21:36:53 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_quasar] Получение списка устройств.
2021-01-13 21:36:53 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Станция | Локальное подключение
2021-01-13 21:36:53 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Станция | Обновление токена устройства
2021-01-13 21:36:53 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Мини | Локальное подключение
2021-01-13 21:36:53 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Мини | Обновление токена устройства
2021-01-13 21:36:53 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Станция Макс | Локальное подключение
2021-01-13 21:36:53 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Станция Макс | Обновление токена устройства
2021-01-13 21:43:21 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Мини => local | {'command': 'sendText', 'text': 'Какая влажность дома?'}
2021-01-13 21:43:23 DEBUG (MainThread) [custom_components.yandex_station.media_player] Яндекс Мини | Влажность 28 процентов | xxxxx-xxx-xxxx-xxxx-xxxxx
2021-01-13 21:43:23 WARNING (SyncWorker_1) [homeassistant.components.telegram_bot] Disallowed targets: [], using default: XXXXXXXXX
2021-01-13 21:43:34 WARNING (MainThread) [homeassistant.components.media_player] Updating yandex_station media_player took longer than the scheduled update interval 0:00:10
2021-01-13 21:43:38 WARNING (MainThread) [homeassistant.components.script.1610556045739] тест вопроса: Already running
2021-01-13 21:43:44 WARNING (MainThread) [homeassistant.components.media_player] Updating yandex_station media_player took longer than the scheduled update interval 0:00:10
2021-01-13 21:43:54 WARNING (MainThread) [homeassistant.components.media_player] Updating yandex_station media_player took longer than the scheduled update interval 0:00:10
2021-01-13 21:44:04 WARNING (MainThread) [homeassistant.components.media_player] Updating yandex_station media_player took longer than the scheduled update interval 0:00:10
2021-01-13 21:44:14 WARNING (MainThread) [homeassistant.components.media_player] Updating yandex_station media_player took longer than the scheduled update interval 0:00:10
2021-01-13 21:44:24 WARNING (MainThread) [homeassistant.components.media_player] Updating yandex_station media_player took longer than the scheduled update interval 0:00:10
```
_Версия компонента последний мастер.
HA:
Версия | 2021.1.0
Тип установки | Unknown
Среда разработки | false
Supervisor | false
Docker | false
Виртуальное окружение | false
Версия Python | 3.8.5
Семейство операционных систем | Windows
Версия операционной системы | 10
Архитектура ЦП | AMD64_

**Comment by Nemiroff** [comment]
Похожая ситуация, только вместо question - dialog. Срабатывает 1 раз. дальше тишина до перезагрузки HA. После перезагрузки опять 1 раз скажет и тишина. в логе Updating yandex_station media_player took longer than the scheduled update interval 0:00:10

**Comment by malinovsku** [comment]
Да компонент очень крутой и слишком много завязок и привычек теперь с ним, но вот тоже возникла проблема, после перезагрузки 1 раз реагирует норм и обложка появляется, потом при нажатии как будто действия отстают, показывает предыдущее (обновление страницы не помогало), помогает если громкость еще изменить, тогда обновит обложку до актуального, но так он работает минуту, после чего вообще перестает реагировать, обложка зависает и в логах Updating yandex_station media_player took longer than the scheduled update interval 0:00:10.
При этом intents работает.
Еще заметил если залочить адрес аутентификации  (где то в коде его видел) на роутере, то управление работает, но только не как локальное (без обложки и обратной связи).
перезапуск всего что есть не помог.
Hassio 2021.1.3 (на 2021.1.0 так же было)
версия компонента 3.0.1

**Comment by AlexxIT** [comment]
Видимо в API Яндекса что-то поменялось. Я посмотрю

**Comment by kirov** [comment]
Такая же проблема, как у @malinovsku. Статус плеера почти не обновляется. В логах пусто.

**Comment by VitBurg** [comment]
Хммм...
- через lovelace плеер "Режим звука: выполнить команду" ошибки нет
- media_content_type: command приводит к ошибке как и media_content_type: dialog.
- media_content_type: text, работает

При ошибке, сообщение журнала сервера повторяется каждые 10 секунд без остановки до перезагрузки.
_

> Logger: homeassistant.components.media_player
> Source: helpers/entity_platform.py:603
> Integration: Медиаплеер (documentation, issues)
> First occurred: 9:50:34 (7 occurrences)
> Last logged: 9:51:34
> 
> Updating yandex_station media_player took longer than the scheduled update interval 0:00:10

_

**Comment by VitBurg** [comment]
На большой колонке яндекс без дисплея подобную ошибку я смог повторить подключив ее по блютузу к чему либо и обратился к колонке с командой через lovelace плеер "Режим звука: выполнить команду" 
Регулировка громкости +/- или на шкале, а также режим произношения текста - ошибки не вызывает.

_> Logger: homeassistant.components.media_player
> Source: helpers/entity_platform.py:603
> Integration: Медиаплеер (documentation, issues)
> First occurred: 12:25:13 (7 occurrences)
> Last logged: 12:26:13
> 
> Updating yandex_station media_player took longer than the scheduled update interval 0:00:10_

**Comment by kirov** [comment]
Вот и добился такого же поведения. Подключил телеграм-бота — на первый вопрос отвечает, а потом не реагирует.

```
Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:603 
Integration: Медиаплеер (documentation, issues) 
First occurred: 19:45:04 (7 occurrences) 
Last logged: 19:46:04

Updating yandex_station media_player took longer than the scheduled update interval 0:00:10
```

**Comment by Zuz666** [comment]
> Вот и добился такого же поведения. Подключил телеграм-бота — на первый вопрос отвечает, а потом не реагирует.

Ну я с этой проблемой и пришёл, только упростил пример. )

**Comment by Zuz666** [comment]
Как-то грустно это, есть кто разобрался с проблемой?

**Comment by kirov** [comment]
Установил версию из мастера. Стало лучше. По первым впечатлениям:
1. Телеграм бот перестал затыкаться после первого вопроса (ура).
2. Статус музыки обновляется нестабильно (из-за чего виджет в lovelace обновляется с задержкой, и автоматизация срабатывает тоже не сразу)

**Comment by kirov** [comment]
Для решения второй проблемы временно добавил такую автоматизацию:

```
- id: '1611226662425'
  alias: Станция - Обновление
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /1
  condition: []
  action:
  - service: yandex_station.send_command
    data: {}
  mode: single
```

**Comment by Chapayyy** [comment]
:-( У меня тоже возникла проблема на фоне полного благополучия и на я.станции мини и на irbis, вчера на ночь обновил в интерграцию в HACS, сегодня заметил, что не произносят фразы из автоматизаций. Автор, спасай :-)

**Comment by kirov** [comment]
UPD: После последнего коммита статус плеера обновляется сам. С некоторой задержкой (секунд пять), но уже, считай, нормально. Свою автоматизацию убрал.

**Comment by AlexxIT** [comment]
@kirov шесть секунд, если быть точным. Думаю, вынесу время в конфиг
https://github.com/AlexxIT/YandexStation/blob/master/custom_components/yandex_station/core/yandex_glagol.py#L101

**Comment by Zuz666** [comment]
Дублирую для все кто проспал, как я ифну с канала @AlexxIT https://t.me/AlexxIT_SmartHome/426:

--------------------------
Владельцы Яндекс.Станции Мини, у меня для вас плохая новость.

Чуть больше недели назад вышла новая прошивка, в которой поломана обратная связь. Колонка больше не шлёт свой актуальный статус в режиме реального времени. А значит, все автоматизации, завязанные на оперативный статус колонки, потеряли актуальность.

Мне пришлось значительно усложнить код и добавить ручное обновление статуса. Но в любом случае оно будет происходить с некоторый задержкой от реального времени. И такие вот автоматизации будут работать довольно плохо на Мини:

https://youtu.be/XLoGvy4RLrg

Я надеюсь, это случайная ошибка и она будет поправлена в следующих прошивках. Но важно помнить, что нерабочий уровень громкости за полгода так и не был исправлен.

Исправление компонента пока в виде бета-версии:

https://github.com/AlexxIT/YandexStation/releases/tag/v3.0.2b1

С Большой станцией проблем по актуальному статусу пока не наблюдается. Хотя когда-то давно у неё и уровень громкости исправно работал...

--------------------------

**Comment by Zuz666** [comment]
> @kirov шесть секунд, если быть точным. Думаю, вынесу время в конфиг

@AlexxIT я это первым делом проверил и статус слушает она сразу писала, а сейчас с задержкой. Трафик вчера захватывал, дошёл уже до того, что что-то не так именно мини не отвечает.

Тикет пока не закрываю, т.к. это обходное решение. Возможно потребуется ещё фикс.

**Comment by AlexxIT** [comment]
Станция сразу отвечает на команду и больше не отвечает совсем! То есть LISTENING она возможно пошлёт первым ответом, а дальше запускается процесс перезапроса статуса. Первый перезапрос будет через 0.5 секунд, а следующие через 6 секунд, чтоб не спамить запрос слишком часто. Я подумаю как динамически подбирать время опроса.

**Comment by VitBurg** [comment]
После обновления через lovelace плеер текст и команды выполняются!, без задержек, без зависаний.
Будем начинать радоваться?

**Comment by Zuz666** [comment]
> Станция сразу отвечает на команду и больше не отвечает совсем!

Не совсем понял объяснение проблемы. Т.е. подвисает web-сокет на стороне станции мини и перестаёт направлять статус автоматически?
Дальше судя по изменения, идут ping команды, видимо в которых и возвращается статус.

Есть где-то описание API для локального протокола? Интересно разобраться в сути проблемы...

**Comment by AlexxIT** [comment]
Сокет не подвисает. Из прошивки станции просто убрали функцию, когда она шлёт свой статус при любых его изменениях

**Comment by popstas** [comment]
У меня похожие проблемы последние 1-2 недели: в какой-то момент TTS перестаёт работать, проходит часов 10, после чего все TTS за день озвучиваются разом :)

Перезагрузка HA помогает. Логи не смотрел, живу пока так.

**Comment by zohann** [comment]
Добрый вечер, я новичок и у меня такие же проблемы: 
Updating yandex_station media_player took longer than the scheduled update interval 0:00:10
Хотел с утра чтоб мне женский голос сказал приятности разные, один раз сработала автоматизация и на этом все, посыпались логи. Перезагрузил, логи исчезли. 
Также логи сыпятся при нажатии в карточке кнопки Выкл (а что она делает?).

**Comment by maxifly** [comment]
> У меня похожие проблемы последние 1-2 недели: в какой-то момент TTS перестаёт работать, проходит часов 10, после чего все TTS за день озвучиваются разом :)
> 
> Перезагрузка HA помогает. Логи не смотрел, живу пока так.

У меня так же.

**Comment by fantomnotabene** [comment]
Поменял в коде на  `+ 1`. Работает сносно. Послевкусие только остается, что это черезжопие, пардон, какое-то. После пропадания репортов об изменении состояния и замены на "опрос".
Надеемся, что просто поломали и вернут..

**Comment by AlexxIT** [comment]
@fantomnotabene поговаривают уже сломана и большая станция :)

**Comment by Zuz666** [comment]
> @fantomnotabene поговаривают уже сломана и большая станция :)

У меня Макс стала хуже работать (просто большую не проверял), но пока лучше мини, но я не тестировал ещё с "приборами".
Честно говоря я не понимаю разработчиков от Яндекса, Знают же что используют API в сторонних компонентах. Никогда не поверю, что вот им говорят вносить изменения, создающие такие проблемы. Ну глупо же. Не уж-то сами не используют своё же устройство дома...

**Comment by Zuz666** [comment]
@AlexxIT 
local_poll - состояние колонки запрашивается по таймеру (может обновляться с задержкой)
local_push - колонка сама шлёт своё состояние (всё работает хорошо)

Смотрю свойства у мини push, хотя с неё проблема и начиналась у большой станции и у макс poll...
Точно в коде на напутано (не смотрел пока сам)? Если не напутано, то получается в мини починили, а в больших станциях сломали.

**Comment by AlexxIT** [comment]
Мини починили позавчера в ночь. Большие станции сломали пару недель назад. Все новости я пишу на канале в телеграмм

**Comment by AlexxIT** [comment]
Прошивка новой Мини поправлена. Всё ещё есть проблемы с прошивкой больших станций
