### ISSUE TITLE
When install error in check config

### ISSUE THREAD

**Issue by didjeru** [AlexxIT/YandexStation#118]
Package services setup failed. Component send_command Integration 'send_command' not found.

**Comment by AlexxIT** [comment]
Не вижу, чтоб это относилось к компоненту YandexStation.

**Comment by didjeru** [comment]
После удаления плагина никаких ошибок. Установка требует перезагрузки, которая невозможна. Только удаление компонента, но тогда не нужна перезагрузка.

**Comment by didjeru** [comment]
После рестарта контейнера, компонент завелся, но чек конфиг выдает ту же ошибку. Перезагрузка средствами HA невозможна.

**Comment by didjeru** [comment]
> Не вижу, чтоб это относилось к компоненту YandexStation.

Помогите решить вопрос. В логах ничего нет, куда копать?

**Comment by AlexxIT** [comment]
Проблема не связана с компонентом. У вас ошибки в конфиге.

**Comment by didjeru** [comment]
Без компоненты конфиг работает без проблем...

**Comment by didjeru** [comment]
Вдруг кому поможет. Была строчка в конфиге:
packages: !include_dir_named custom_components
