### ISSUE TITLE
Непредсказуемы intents

### ISSUE THREAD

**Issue by EropForWork** [AlexxIT/YandexStation#119]
Добрый день, возможно ли добавить статичным intents вариативности?
Например вместо
```
intents:
  какая температура в спальне:
  какая температура на кухне:
```

вот как то так

```
 intents:
   какая температура PEREMENNAYA
```

В данном примере конечно не чувствуется зачем это, но я бы хотел используя Яндекс.Мини включать на андроид_тв через HA любой фильм, мультик и тд. 

```
 intents:
   включи фильм PEREMENNAYA
```
А уже в автоматизациях/скриптах я бы написал, если есть PEREMENNAYA, то включи приложение для фильмов и найди PEREMENNAYA.

А вообще спасибо за замечательный компонент, я уже забыл где лежит от телика, и пользуюсь пультом от приставки только для выбора нужного фильм\сериала!

**Comment by AlexxIT** [comment]
Для этого необходимо использовать компонент YandexDialogs

**Comment by EropForWork** [comment]
Я прочитал руководство, но я увидел лишь инструмент, почти такой же как и intents. В диалогах же тоже сначала забиваешь какие то значения. Но как внести все фильмы в мире?
Для кухни/спальни этот вариант конечно рабочий, но мне кажется лишним. 2 строчки в конфиге и одна автоматизация на условиях template. С диалогом же получится блок в конфиге и две автоматизации(или же так же одна автоматизация)..

**Comment by EropForWork** [comment]
А всё нашёл, пример с калькулятором, да? Попробуем!

**Comment by AlexxIT** [comment]
intent в этой интеграции технически не может быть динамическим
