### ISSUE TITLE
Список покупок. Отправляем список покупок в телеграм \ на почту

### ISSUE THREAD

**Issue by DivanX10** [AlexxIT/YandexStation#120]
Данный способ позволит вам отправить список покупок прямо в телеграм. Можете к примеру автоматизировать процесс при покидании зоны и в телеграм придет список покупок.  

1) Создаем файлик к примеру с таким именем `send_shoppinglist.py`, не важно какое имя, это всего лишь питоновский скрипт который мы будем запускать в ХА. Скопируйте этот код и вставьте в ваш созданный файлик.

Если хотите отправить список в телеграм
```
#!/usr/local/bin/python
# coding: utf8
import json

with open('/config/.shopping_list.json') as data_file:
    shoppingListData = json.load(data_file)

content = u"Список покупок:\n"
for entry in shoppingListData:
    if not entry['complete']:
        content += u"- %s\n" % entry['name']

content += u"\n"

print(content)
```

Если если хотите отправить список на почту. 

```
#!/usr/bin/python
# coding: utf8
import json, smtplib, datetime

sender='y@gmail.com' # Указываем свой почтовый ящик
reciever='y@gmail.com' # Указываем свой почтовый ящик
account='y@gmail.com' # Указываем логин почтового ящика
password='xxx' # Указываем пароль почтового ящика

with open(' home/homeassistant/.homeassistant/python_scripts/shopping_list.json') as data_file:
    shoppingListData = json.load(data_file)
   
# build message
content = u"Shopping list:\n"
for entry in shoppingListData:
    if not entry['complete']:
        content += u"- %s\n" % entry['name']

content += u"\nThank you for shopping!"

mail=smtplib.SMTP('smtp.gmail.com',587)
mail.ehlo()
mail.starttls()
mail.login(account,password)
message = """From: %s\nTo: %s\nSubject: %s\n\n%s""" % (sender, reciever, "Shopping list", content)
mail.sendmail(sender,reciever,message.encode('utf-8'))
mail.close()
```

2) Созданный файлик `send_shoppinglist.py` нужно разместить в папке python_scripts
3) Если у вас все конфиги лежат в папке packages, то просто создайте файлик, к примеру `shopping_list.yaml` и вставьте код или просто вставьте код в `configuration.yaml`

```
sensor:
  - platform: command_line
    name: Список покупок
    command: python3 /config/python_scripts/send_shoppinglist.py
```

4) Перезагружаем ХА
5) В шаблоне для проверки вставляем: `message: '{{states.sensor.shopping_list.state}}'`
6) Если отображается сенсор, то можно добавить сенсор в lovelace
7) Список можно отправить в телеграм кодом `message: '{{states.sensor.shopping_list.state}}'`

В телеграм это выглядит вот так
 ![список](https://user-images.githubusercontent.com/64090632/108091481-ce12c100-708c-11eb-9559-12e17994bdc1.JPG)

**Comment by AlexxIT** [comment]
Список покупок можно спросить у Алисы через интеграцию с Телеграмом. Поэтому не вижу смысла в реализации этого способа

**Comment by StelthRoman** [comment]
Сенсор из п.3 надо исправить иначе будет ошибка YAML. Прописать надо так:

```
  command_line:
    sensor:
      name: Список покупок
      command: python3 /config/send_shoppinglist.py
```
