### ISSUE TITLE
Плавное изменение громкости на яндекс станции макс

### ISSUE THREAD

**Issue by degorychev** [AlexxIT/YandexStation#125]
Насколько я понимаю, у яндекс станции макс есть больше градации громкости чем на обычной станции. Но через интерфейс mini-media-player громкость может установится только в положения "1 2 3 4..."
Пробовал менять volume_step на 0.1 и изменять max_volume на 10, не помогает, сам яндекс принимает только целые числа от 0 до 100, но при этом между 1 и 10 - разницы в громкости нет

**Comment by AlexxIT** [comment]
На обычных колонках громкость меняется фразами: "громкость на 1", "громкость на 10". Где 1 - самое тихое и 10 - самое громкое. У Макс станции другие команды?

**Comment by degorychev** [comment]
> На обычных колонках громкость меняется фразами: "громкость на 1", "громкость на 10". Где 1 - самое тихое и 10 - самое громкое. У Макс станции другие команды?

Проверил, команды "громкость на 1", "громкость на 10" - работают, команды "громкость два", "Громкость две целых три десятых" "громкость два и четыре" - для нее одинаковы. "два с половиной", "две целых семь десятых" ставят уровень громкости  на третий уровень. "Громкость чуть выше" - ставит следующий уровень громкости...

В общем я понял что тут нужно копать в сторону поддержки яндекса...

**Comment by whitesabv** [comment]
У меня все работает, голосом указываешь громкость - один, два, три, только целые, а в HA -  0.11 , 0.25 , и так далее.
