### ISSUE TITLE
Пропали обложки альбомов

### ISSUE THREAD

**Issue by Mr-Vovka** [AlexxIT/YandexStation#127]
Перестала показывать обложки альбомов, на сколько я понимаю не работает локальное управление. Подскажите пожалуйста, как его вернуть. Всё случилось после обновления и настройки через интеграции.

**Comment by AlexxIT** [comment]
Перезагрузить колонку, сервер (железку) ХА, зафиксировать IP колонки на роутере

**Comment by degorychev** [comment]
Судя по всему прошивка колонки обновилась, сегодня тоже такую проблему вижу. Более того, почему то при изменении громкости она теперь рассказывает фразы в духе "уровень установлен", раньше такого не было
