### ISSUE TITLE
Обрывается и не прилетает следующая фраза из Home assistant в Яндекс.

### ISSUE THREAD

**Issue by prokudin0777** [AlexxIT/YandexStation#128]
Приветствую. Во-первых, спасибо за разработку. Все настроил, все работает.
 Выяснил еще месяц, что обрывается и не прилетает следующая фраза из Home assistant в Яндекс.

intents:
  Пропылесось в коридоре и на кухне: Ок
  Пропылесось в коридоре и на кухн: Ок

Так вот,первая фраза в Яндекс в раздел сценарии - не прилетает.
Вторая фраза - все ок.

Остальные фразы вводил - всё работает.

Update:
Фразы "Пропылесось в коридоре и в кухне", "Пропылесось на кухне", "Пропылесось на кухне и в коридоре" - тоже нормально прилетают.

Неужели Яндекс проверяет правильность составления фразы?

Уже было несколько обновлений компонента, но это как было так и осталось.

**Comment by AlexxIT** [comment]
А в сценариях видно обе фразы? https://yandex.ru/quasar/

**Comment by prokudin0777** [comment]
Нет, "Пропылесось в коридоре и на кухне" - эта фраза не прилетает.
Вот в yaml
 
 intents:
    Пропылесось на кухне: Хорошо в кухне
    Пропылесось на кухне и в коридоре: Хорошо коридор и кухня
    Пропылесось в гостинной: Хорошо в гостинной
    Пропылесось в детской: Хорошо в детской 
    Пропылесось в коридоре: Хорошо в коридоре
    Пропылесось в коридоре и в кухне: Хорошо коридор и кухня
    Пропылесось в коридоре и на кухне: Хорошо коридор и кухня

![image](https://user-images.githubusercontent.com/77752859/109524198-459b1400-7ac1-11eb-8ebe-df3660067fb8.png)


Несколько раз удалял фразы, удалял интеграцию. Но все равно не прилетает.

**Comment by AlexxIT** [comment]
Возможно Яндекс запрещает создавать такую фразу по своим внутренним причинам

**Comment by AlexxIT** [comment]
Не актуально
