### ISSUE TITLE
Не подгружаются обложки песен

### ISSUE THREAD

**Issue by glinkin55** [AlexxIT/YandexStation#129]
В чем может быть проблема?

**Comment by glinkin55** [comment]
Также нет информации что конкретно проигрывается. Управление с кнопопк работает, команды считываются колонкой.

**Comment by glinkin55** [comment]
Я так понимаю не рабоиает локальный режим. Колонки яндекс мини и jbl music link. Только у меня такое или у всех?

**Comment by AlexxIT** [comment]
Только у вас. Или неправильно установлен ХА или проблемы с сеть

**Comment by glinkin55** [comment]
ХА установлен в докер на NAS Synology. SSL сделан через обратный прокси. Может дело в портах?

**Comment by glinkin55** [comment]
Вопрос решил

**Comment by new-kirte** [comment]
@glinkin55 а как вы его решили? у меня такой же setup  и та же проблема
