### ISSUE TITLE
Ругается на yandex_tts

### ISSUE THREAD

**Issue by Vannoo** [AlexxIT/YandexStation#13]
Добрый день.
Подключил по инструкции, колонку в конфигурации создает. Но при попытке прописать скрипт ругается на yandex_tts:
`Invalid config for [script]: [yandex_tts] is an invalid option for [script]. Check: script->script->script->yandex_tts`
Подскажите, куда копать. TTS гугла закомментирован. Home Assistant 0.105.3

**Comment by AlexxIT** [comment]
Неправильно написали конфиг скрипта.

**Comment by Vannoo** [comment]
Хмм. Это первый скрипт, который я пишу, да и тот на 98% взят из примера. Что такое "конфиг скрипта" и где его писать?
У меня есть в configuration.yaml:
```
yandex_station:
  username: !secret yandex_user
  password: !secret yandex_password
```
в scripts.yaml
```
# script:
#   yandex_tts:
#     alias: TTS на Яндекс.Станции
#     sequence:
#     - service: tts.yandex_station_say
#       data_template:
#         entity_id: media_player.yandex_station_9410503441101c0d060b
#         message: Температура в комнате {{ states("sensor.temperature_bme280_pir_sensor02")|round }} градуса.
```
Ну и, естественно, пароли и связи между файлами. Надо что-то еще где-то еще?

**Comment by Nezumikun** [comment]
В scripts.yaml уберите script: он у вас, наверняка уже объявлен в configuration.yaml

**Comment by Vannoo** [comment]
Точно! Спасибо! А ведь по этим граблям я уже ходил...
