### ISSUE TITLE
Возможность управлять яркостью на Яндекс станции Макс

### ISSUE THREAD

**Issue by agamemnen** [AlexxIT/YandexStation#135]
Было бы здорово, если бы была возможность управлять из НА яркостью дисплея Яндекс станции Макс.
Возможно как то это реализовать?

А то авто яркость довольно не тривиально отрабатывает, а корректировать в ручную не удобно.
Так бы поставить в НА автоматизацию и он бы сам менял яркость в зависимости от заданных параметров.

**Comment by AlexxIT** [comment]
Готово давно
https://github.com/AlexxIT/YandexStation/releases/tag/v3.0.1

**Comment by agamemnen** [comment]
Благодарю! Упустил из виду!
Спасибо Вам!
