### ISSUE TITLE
Интеграция ломает UI - бесконечная загрузка Lovelace

### ISSUE THREAD

**Issue by bigsem89** [AlexxIT/YandexStation#137]
Версия HA 2021.3.3

в логах:

2021-03-13 01:23:12 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 403
2021-03-13 01:24:59 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.result[310](state: media_player.yandex_station_ff98f0293072922f0c80c351).attributes.volume_level=-inf(<class 'float'>
 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.result[310](state: media_player.yandex_station_ff98f0293072922f0c80c351).attributes.volume_level=-inf(<class 'float'>2021-03-13 01:30:13 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 403

**Comment by bigsem89** [comment]
подключил intents, и все работало, но сегодня сломалось ))

**Comment by bigsem89** [comment]
Обновился до 2021.3.4 Lovelace заработа, но обьекты пропали....

Error while executing automation automation.alisa_telegram: Unable to find service media_player.play_media
9:55:31 – Автоматизация (ERROR) - первое сообщение получено 9:55:21 и повторялось 2 раз
alisa_telegram: Error executing script. Service not found for call_service at pos 1: Unable to find service media_player.play_media
9:55:31 – Автоматизация (ERROR) - первое сообщение получено 9:55:21 и повторялось 2 раз

**Comment by deliriumxp** [comment]
Такая же ситуация, но обновление проблему не решило. Только отключение компонента.

**Comment by al-ivanov** [comment]
Аналогичная проблема. Обновление тоже не помогло

**Comment by dreem2001** [comment]
Тоже самое поведение на двух последних версиях компонента и двух версиях HASSIO

**Comment by j0ker13** [comment]
Обновление 2021.3.4 не помогло

**Comment by dreem2001** [comment]
У меня все интенты продолжают замечательно работать и без компонента яндекс станции, на yandex smart home компоненте. 
Можно смело ждать и ещё раз поблагодарить автора за очень полезную и крутую интеграцию 👍

**Comment by NikitaKA** [comment]
Судя по логам проблема была в том, что Яндекс прислал невалидное значения параметра громкости:
![image](https://user-images.githubusercontent.com/2543427/111146312-5441fa80-859a-11eb-8a01-853429c2ba71.png)

Исправилось довольно просто - после перезагрузки HA панель управления частично подгрузилась и я поменял через виджет колонки ее громкость. После этого через некоторое время все восстановилось.

**Comment by antropophob** [comment]
Как решение здесь и сейчас - поменять громкость работает, но надо добавить обработку: -inf переводить в какое-то значение (видимо, 0). В моем случае этот баг воспроизвелся со станцией мини.

**Comment by AlexxIT** [comment]
Видимо вам всем прилетела новая версия прошивки на Мини. На моей мини нет такой проблемы. Мне нужно видеть, как выглядит эта громкость в коде, чтоб правильно поставить исключение.

**Comment by AlexxIT** [comment]
В теории поправлено в последнем релизе

**Comment by AlexxIT** [comment]
Помогло?

**Comment by dreem2001** [comment]
Да. С последним релизом и UI не уходит влуп и станция работает, как обычно.
Большое спасибо за оперативность!

**Comment by darkfessing** [comment]
Сегодня столкнулся с такой же проблемой на своей Яндекс Мини. Рестарт HA не помогал (у меня Core). Авто-обновления включены. Помогло только уменьшение голосом громкости на станции до 0, потом возврат на произвольное значение. После чего интерфейс загрузился и все стало ОК.

PS. автору спасибо за крутую интеграцию!

**Comment by AlexxIT** [comment]
Чтоб обновить компонент нужно или установить громкость всех станций мини на ноль. Или временно их выключить из розетки.

**Comment by DivanX10** [comment]
> У меня все интенты продолжают замечательно работать и без компонента яндекс станции, на yandex smart home компоненте.

Потому что вы, если я правильно вас понял, используете [форк интеграции от dext0r](https://github.com/dext0r/YandexStation) и там интенты работают иначе.  В форке есть классная фишка, это [фразы-синонимы](https://github.com/AlexxIT/YandexStation/pull/178)
