### ISSUE TITLE
После обновления компонента, станция недоступна

### ISSUE THREAD

**Issue by ezverev1980** [AlexxIT/YandexStation#14]
После обновления компонента, станция перестает быть доступной, пробовал удалять .yandex_station.txt не помогает, создается объект media_player.yandex_station_04007884c9143c2907cf с пометкой:
Этот объект в настоящее время недоступен.

Неделю назад все работало, конфигурацию не менял. В чем может быть проблема куда копать?
Спасибо!

**Comment by devbis** [comment]
Столкнулся с такой же проблемой. Мне помогла перезагрузка самого устройства с home assistant. Перед этим обновил компонент до последнего коммита

**Comment by ezverev1980** [comment]
> Столкнулся с такой же проблемой. Мне помогла перезагрузка самого устройства с home assistant. Перед этим обновил компонент до последнего коммита

Пробовал не помогает.
Только откат до старой версии помог.
Спасибо!

**Comment by AlexxIT** [comment]
Что в логах? Если не было ошибок - станция просто не обнаружилась по Мультикасту. Такое иногда быват.

**Comment by ezverev1980** [comment]
После последнего апдейта, все заработало. Спасибо.
