### ISSUE TITLE
Не зайти в HA lovelace

### ISSUE THREAD

**Issue by maxifly** [AlexxIT/YandexStation#140]
Стояла не самая последняя версия аддона (какая точно не помню - обновлял месяц назад), но до сегодняшнего утра все работало.
Утром не смог войти в HA lovelace - страница крутится на заставке.
В логах HA:

```
2021-03-21 15:22:08 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.result[189](state: media_player.yandex_station_ff98
f029ad3a2fc9ebblablabla).attributes.volume_level=-inf(<class 'float'>
```
пока не удалил каталог с компонентом из /usr/share/hassio/homeassistant/custom_components

Пробовал разное:
перегружать яндекс-станцию (мини)
удалять медиа-плеер из lovelace

Ничего не помогло.

На всякий случай каталог со скриптами компонента я сохранил, если там где-то прошита версия - могу сообщить

**Comment by merccooper** [comment]
такая же проблема, lovelace заработал только после удаления компонента :\

**Comment by Su4oNoK** [comment]
Неистово плюсую - такая же беда, пришлось снести каталог с компонентом. Иногда получалось при ручном рестарте контейнера HA попасть в  lovelace, но практически по всем датчикам было - "не удалось обнаружить"

**Comment by darkfessing** [comment]
Прикажите голосом колонке сделать "громкость 0", потом любую которая вам нужна. Например "громкость 5". Помогает, сам сталкивался с подобным и это уже обсуждали тут: https://github.com/AlexxIT/YandexStation/issues/137

**Comment by AlexxIT** [comment]
Дубликат #137
