### ISSUE TITLE
Список покупок.

### ISSUE THREAD

**Issue by NMGAndy** [AlexxIT/YandexStation#144]
Привет!

Обновляю список покупок в HA скриптом из описания.
При обновлении Алиса зачитывает весь список. Можно этого избежать? Чтобы скрипт молча обновлялся.

**Comment by runnerfanspb** [comment]
Добрый день. После последних обновлений перестал работать список покупок. 
При обновлении выдает следующее:
Logger: custom_components.yandex_station.media_player
Source: custom_components/yandex_station/media_player.py:711
Integration: Yandex.Station (documentation)
First occurred: 11:16:39 (1 occurrences)
Last logged: 11:16:39

Unsupported cloud media: shopping_list

Скрип сделан следующий по образцу: 
script:
# Список покупок большая станция
  update_shopping_list:
    alias: Обновить список покупок
    sequence:
      - service: media_player.play_media
        entity_id: media_player.yandex_station_64007891832454170bcf  # замените на вашу колонку
        data:
          media_content_id: update
          media_content_type: shopping_list

Прошу подсказать, что с этим делать

**Comment by runnerfanspb** [comment]
`script:
# Список покупок большая станция
  update_shopping_list:
    alias: Обновить список покупок
    sequence:
      - service: media_player.play_media
        entity_id: media_player.yandex_station_64007891832454170bcf  # замените на вашу колонку
        data:
          media_content_id: update
          media_content_type: shopping_list`

**Comment by AlexxIT** [comment]
Если только уменьшать громкость колонки в ноль, а затем её возвращать...
