### ISSUE TITLE
TTS Yandex (script, automation) нет формы message

### ISSUE THREAD

**Issue by itpcss** [AlexxIT/YandexStation#149]
Всем привет!
Заметил если создавать скрипт, и выбрать tts.yandex, то дальнейших настроек нет (не предлагает) возможности провести настройку через lovelace не появляется форма где вводить message, если вручную создавать то все хорошо, также это касается и автоматизации. Для примера скинул 2 скриншота, если выбрать tts.amazon, то дополнительная форма появляется где вводить message, а на яндекс нет. Собственно вопрос это у меня так, или у всех? И будет ли в будущем доработка? 
![amazon](https://user-images.githubusercontent.com/25006833/115237877-bfe12f80-a125-11eb-964e-5dd4fde6fa5e.png)
![tts yandex](https://user-images.githubusercontent.com/25006833/115237883-c079c600-a125-11eb-958a-2a9946a2d744.png)

**Comment by denis660** [comment]
Такая же проблема, присоединяюсь!

**Comment by AlexxIT** [comment]
И не будет. Это устаревший сервис для обратной совместимости, которым не рекомендуется пользоваться.
