### ISSUE TITLE
Громкость TTS

### ISSUE THREAD

**Issue by alexfrydr** [AlexxIT/YandexStation#152]
Большая колонка стала искать либо включать то что написано в скрипте. 
Интеграция последней версии.
Home Assistant 2021.4.6

==================================================
script:
  alice_custom_volume2:
    sequence:
    - service: tts.yandex_station_say
      entity_id: media_player.yandex_station_540078920110102034cf
      data_template:
        message: Доброе утро!
        options:
          volume_level: 0.1

**Comment by AlexxIT** [comment]
Документацию читали? Раздел первый способ TTS

**Comment by alexfrydr** [comment]
> Документацию читали? Раздел первый способ TTS

В первую очередь. 

Громкость TTS
Только для локального режима!

Колонка произнесёт текст с заданной громкостью и вернёт громкость на прежний уровень.

**Comment by AlexxIT** [comment]
> Зависит от настройки "Режим звука" (из окна медиа-плеера). Будет или произносить текст или выполнять команду. Он же вызывается из окна медиа-плеера.

> Из-за зависимости от "Режим звука" - не рекомендуется к использованию в автоматизациях. Используйте Второй способ.

**Comment by AlexxIT** [comment]
Не актуально
