### ISSUE TITLE
Алиса комментирует изменение громкости, если пытаться выставить уже выставленный уровень

### ISSUE THREAD

**Issue by tayanov** [AlexxIT/YandexStation#155]
Если в скрипте или автоматизации менять уровень громкости, на такой же какой установлен сейчас на колонке то Алиса комментирует действие лишними паразитными фразами вроде "Такая громкость уже стоит" итп.  
Хорошо бы добавить в компонент сравнение текущего уровня громкости и запрашиваемого на установку уровня и при их совпадении не давать команды алисе на исполнение

**Comment by AlexxIT** [comment]
Сравнение есть, возможно не работает

**Comment by AlexxIT** [comment]
В теории не должно быть такой проблемы в последней мастер версии. Если проблема сохраняется - issue можно переоткрыть

**Comment by vofka18** [comment]
Яндекс станция миди в последние пару месяцев начала комментировать установку такой же громкости. Нет ли возможности делать тихую установку громкости?
