### ISSUE TITLE
Не создается media_player.yandex_intent

### ISSUE THREAD

**Issue by sushami** [AlexxIT/YandexStation#156]
Перестал работать yandex_intent, переустановил все, теперь не подгружается интеграция yandex.station(в hacs установлена), если, несмотря на это, прописать(логин пароль яндекс аккаунта) станцию в конфиге, то появляется карточка интеграции, но без устройств. Если добавить id и ip адрес колонки в конфиг, то появляется устройство в карточке интеграции.
![изображение](https://user-images.githubusercontent.com/11832917/118316948-1c0a5a00-b500-11eb-97b8-337e553352af.png)

**Comment by sushami** [comment]
Проблема с  yandex_intent решилась после добавления записи intents: Покажи сообщение: ага , хотя в мануале написано, что плеер yandex_intent создается при первом запуске компонента.

**Comment by AlexxIT** [comment]
Там написано, что он сдается после настройки фраз

**Comment by sushami** [comment]
> 
> 
> Там написано, что он сдается после настройки фраз

![изображение](https://user-images.githubusercontent.com/11832917/118637969-05555300-b7df-11eb-8fed-619f749eef94.png)
