### ISSUE TITLE
Не добавляются устройства в интеграции

### ISSUE THREAD

**Issue by PeshkovAlexandr** [AlexxIT/YandexStation#157]
Добавляю интеграцию, в интеграции не появляются устройства и объекты

![image](https://user-images.githubusercontent.com/84032737/118395293-29375e00-b652-11eb-83f2-ef995e167da7.png)

яндекс станция мини с логином яндекса связана, управляет устройствами Mi Home.

**Comment by AlexxIT** [comment]
Может в логах есть ошибки?

**Comment by PeshkovAlexandr** [comment]
Посмотрел, действительно есть, как можно исправить?

Logger: homeassistant.components.media_player
Source: custom_components/yandex_station/core/yandex_quasar.py:145
Integration: Медиаплеер (documentation, issues)
First occurred: 18:23:27 (1 occurrences)
Last logged: 18:23:27

Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 74, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 91, in load_speakers
    await self.add_scenario(device_id)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 145, in add_scenario
    assert resp['status'] == 'ok', resp
AssertionError: {'request_id': '0e41ac87-c148-4cbf-a0ea-142e365f84b3', 'status': 'error', 'code': 'INVALID_VALUE', 'message': 'Активационная фраза для сценария уже используется'}

**Comment by PeshkovAlexandr** [comment]
Победил!!!! До этого пробовал можордом поставить, и подключал яндекс колонку. В настройках прописался какой-то сценарий, он мешал работе из HA
