### ISSUE TITLE
Не играет музыка со скрипта

### ISSUE THREAD

**Issue by Zwhouse2021** [AlexxIT/YandexStation#159]
Я не знаю, куда нужно было вставлять кусок кода для проигрывания музыки, поэтому вставил в папку "scripts":
![image](https://user-images.githubusercontent.com/80384216/118768602-e1018100-b887-11eb-99c7-8e5581df0a63.png)
Добавляю скрипт на lovelace, но он не играет. Если вставить ссылку на песню в плеер НА, то играет. Я, видимо, что-то неправильно делаю. Подскажите, пожалуйста

**Comment by AlexxIT** [comment]
Ссылки на `.com` поддерживаются только в последней master версии компонента

**Comment by Zwhouse2021** [comment]
Короче, проблема решена. Когда вы копируете ссылку с яндекс музыки поменяйте в адресе ".com" на ".ru"

**Comment by Zwhouse2021** [comment]
> Ссылки на `.com` поддерживаются только в последней master версии компонента

Да. Спасибо большое
