### ISSUE TITLE
Добавить в интеграцию сервис. Yandex_station.reload

### ISSUE THREAD

**Issue by lexxstorm** [AlexxIT/YandexStation#162]
При потере соединения колонки по локальному протоколу, вновь подключиться по нему возможно только через перезагрузку ХА. Что очень неудобно. Хотелось бы команду обновления соединения со станцией.

**Comment by dmamontov** [comment]
https://github.com/AlexxIT/YandexStation/pull/179

Добавил возможность, ждем как сольют) Пока можете просто внести изменения в компонент руками.

**Comment by AlexxIT** [comment]
Думаю правильнее найти и починить автоматическое переподключении. Пока не понимаю, почему оно не работает

**Comment by AlexxIT** [comment]
В каких случаях соединение с колонкой теряется и больше не восстанавливается? Нужно детальное пошаговое описание, чтоб повторить

**Comment by lexxstorm** [comment]
Бывает при отсутствии интернета на продолжительное время, когда интернет
восстанавливается колонка появляется в режиме assumed, то глобальное
отсутсвие интернета на некоторое время во всем доме

сб, 4 сент. 2021 г., 11:21 Alex X ***@***.***>:

**Comment by lexxstorm** [comment]
После открытия этого бага такое случалось всего два раза, один раз электрики отрубили электричество (меняли автомат в щитке), второй раз провайдер производил работы на канале. Оба раза лечилось перезагрузкой инстанса хоум ассистанта

**Comment by AlexxIT** [comment]
Поправил автоматическое соединение с локальной колонкой. Была проблема, когда сервер ХА терял интернет в момент попыток восстановить соединение. Изменения в последней мастер версии.

**Comment by Alex-Erofeev** [comment]
Могу ли я опять поднять этот вопрос?
Но причина немного другая. У меня через эту интеграцию прокинуты обогреватели Rubetek (родная интеграция для HA отсутствует). Загородный дом в будни обесточивается и удаленные устройства отваливаются с сообщением "Этот объект больше не предоставляется интеграцией". Когда удаленно включаю электричество, то приходится перезапускать сервис "Yandex_station" вручную, и тогда устройства снова появляются в сети.
Если бы была такая возможность, то я бы добавил скрипт, который после подачи электричества перезапускает службу.

**Comment by AlexxIT** [comment]
https://www.home-assistant.io/integrations/homeassistant/#service-homeassistantreload_config_entry

**Comment by Alex-Erofeev** [comment]
> https://www.home-assistant.io/integrations/homeassistant/#service-homeassistantreload_config_entry

Это работает! Спасибо!!!
