### ISSUE TITLE
Уведомление о входе в местоположение и выходе из него

### ISSUE THREAD

**Issue by reinethernal** [AlexxIT/YandexStation#164]
Доброго времени суток! Реально ли заставить алису произносить статус объекта при изменении местоположения? Условно пользователь вышел с работы - алиса сказала как и что.

**Comment by AlexxIT** [comment]
Доброе. Конечно это можно. Простейшая автоматизация ХА на выход из зоны. И действием TTS. Поспрашивайте в telegram чатах ХА, если есть вопросы, как такую автоматизацию сделать.
