### ISSUE TITLE
Yandex_intent < 100

### ISSUE THREAD

**Issue by mrpatrickstarkovich** [AlexxIT/YandexStation#167]
На данный момент нет возможно получать больше 100 команд от станции. Можно добавить еще Yandex Intent?

**Comment by AlexxIT** [comment]
Вы уже превысили лимит?

**Comment by mrpatrickstarkovich** [comment]
Так открывается огромная возможность автоматизаций в node-red

**Comment by AlexxIT** [comment]
В ближайший месяц врядли найду время для доработки. Но подумаю, что можно сделать. Не думал, что кому-то не хватит 100 интентов.
Яндекс поддерживает несколько разных фраз на 1 интент. Не спасёт ситуацию?

**Comment by mrpatrickstarkovich** [comment]
> В ближайший месяц врядли найду время для доработки. Но подумаю, что можно сделать. Не думал, что кому-то не хватит 100 интентов.
> Яндекс поддерживает несколько разных фраз на 1 интент. Не спасёт ситуацию?

**Comment by mrpatrickstarkovich** [comment]
Написал сценарии вручную, чтобы несколько фраз вызывали intent, но при получении нового внешнего url для home Assistant пришлось проводить авторизацию на яндекс диалогах заново и идентификатор устройства Yandex Intent изменился. В итоге все сценарии, привязанные к данную устройству сбросились, а привязать вручную не дает яндекс (((

**Comment by RestOp** [comment]
Превысил лимит в 100...
Вот бы увеличить!

Спасибо большое заранее

**Comment by dext0r** [comment]
> Яндекс поддерживает несколько разных фраз на 1 интент. Не спасёт ситуацию?

Отчасти спасёт, вот бы ещё это через конфиг можно было настраивать... :)

**Comment by RestOp** [comment]
> Отчасти спасёт, вот бы ещё это через конфиг можно было настраивать... :)

Факт, спасет очень даже, если бы все через конфиг можно было залить...

**Comment by dext0r** [comment]
Сделал экспериментальную ветку, подробнее - https://github.com/AlexxIT/YandexStation/pull/178

**Comment by AlexxIT** [comment]
Спасибо, посмотрю по возможности

**Comment by AlexxIT** [comment]
YandexIntents в этом компоненте развиваться не будет. Рекомендуется использовать новый способ:

https://github.com/AlexxIT/YandexStation#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4-%D0%BE%D1%82-%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D0%B8

Или такой компонент:

https://github.com/dext0r/ha-yandex-station-intents
