### ISSUE TITLE
Read.me - Несколько TTS в конфиге 

### ISSUE THREAD

**Issue by tjunussov** [AlexxIT/YandexStation#17]
Так же столкнулся с одновременной работой нескольких tts и нескольких колонок ( Google Home Mini, Sonos ) и Яндекс.Станция как в issue [#8 ](https://github.com/AlexxIT/YandexStation/issues/8)

На данный момент функция воспроизвести голос на интерфейсе вообще перестала работать для Google Mini

В доке написано что ...
> В этом случае вы можете настроить несколько TTS сервисов. Из окна медиа плеера всех колонок всегда будет стартовать первый повавшийся сервис (в алфавитном порядке). Поэтому название TTS сервиса Яндекса можно переименовать, например, в alice_say 

получается что если по алфавиту, то `alice_say ` будет всегда первой, так как на `a`, а `google_translate_say` будет вторым, соотвественно на интерфейсе медиа плеер для Google Home mini **не сможет воспроизвести** через `alice_say`, будет тишина и при этом Яндекс плеер будет работать. Если переименовать в `yandex_say `то будет наоборот, Google Mini заговорит но Яндекс плеер будет молчать, 

**Как быть ? в доке не сказано, либо мы что то недопонимаем**

**Comment by AlexxIT** [comment]
Вы правильно понимаете. Стандартным GUI медиа плеера эту проблему не обойти.
Вот этот медиа плеер позволяет указывать TTS для каждого медиа плеера в отдельности:
https://github.com/kalkih/mini-media-player#tts-object

**Comment by tjunussov** [comment]
Спасибо! Дочитал #8  и увидел комент 
> Только из GUI медиа плеера одновременно в двух колонках работать НЕ будет.
p.s просьба дописать этот EDGE CASE в readme 👍

**Comment by tjunussov** [comment]
и прежде чем закрыть этот issue еще один момент исходит из этой логики

- В automation, сооветсвенно `media_player = all` тоже будет работать либо одно либо другое ( google mini или яндекс станция ) 

и еще какбуто всетаки есть аномалии, когда в одном automation мне надо сказать в google.mini через `google_translate_say `а затем через `delay `в yandex станцию черех `alice_say`, то почемуто гугл молчит.

**Comment by alexanderznamensky** [comment]
добрый день.

установил mini-media-player. все яндексовские колонки работают. А вот Гугл мини в скрипте работает, а в плеере - нет.
может быть я неправильно конфигурирую? поправьте, пож, что не так делаю?

          - entity: media_player.google_home_mini
            shortcuts:
              attribute: sound_mode
              buttons:
                - icon: 'mdi:voice'
                  id: Произнеси текст
                  type: sound_mode
                - icon: 'mdi:google-assistant'
                  id: Выполни команду
                  type: sound_mode
                - icon: 'mdi:playlist-star'
                  id: включи мою любимую музыку вперемешку
                  type: command
                - icon: 'mdi:playlist-music'
                  id: включи плейлист дня
                  type: command
                - icon: 'mdi:heart'
                  id: лайк
                  type: command
                - icon: 'mdi:heart-off'
                  id: снять лайк
                  type: command
              columns: 6
            tts:
              - platform: google_translate
            type: 'custom:mini-media-player'

**Comment by AlexxIT** [comment]
Тере не надо в разделе `tts`

**Comment by alexanderznamensky** [comment]
Алексей, спасибо большое! все заработало!
Осталось мне только разобраться, почему 2 яндекс мини колонки не выключаются (в посте "Несколько станций #56").
Спасибо сказал в Яндекс.деньгах )

**Comment by AlexxIT** [comment]
Станции всегда включены. Чтоб быть готовыми произнести TTS

**Comment by alexanderznamensky** [comment]
День добрый, Алексей! По всей видимости, я не совсем правильно выразился.
При нажатии кнопки 
![image](https://user-images.githubusercontent.com/65254375/93077983-5af6c000-f692-11ea-8cb3-5039d12cf31f.png)
колонки мини прекращают воспроизведение, но заставка остается. А вот станция прекращает воспроизведение и убирает заставку.

Возможно, это какие-то особенности mini-media-player....

**Comment by AlexxIT** [comment]
На станции есть команда "на главный экран". Потому что у неё может быть экран. Он работает как стоп. На мини нет этой команды. Невозможно сделать стоп.

**Comment by alexanderznamensky** [comment]
Все ясно. Спасибо!

С уважением,
Александр Знаменский
M +7.903.7551788

пн, 14 сент. 2020 г., 17:24 Alex X <notifications@github.com>:

**Comment by AlexxIT** [comment]
Проблема нескольких TTS больше не актуальна
