### ISSUE TITLE
Не работает локальный режим со статическими адресами

### ISSUE THREAD

**Issue by new-kirte** [AlexxIT/YandexStation#173]
Мне кажется у меня не работает локальный режим. Кажется :) потому что обложки и названия треков не отображаются, но перемотка работает. Установка через HACS. Настройка через GUI. Дополнительно в configuration.yaml:
yandex_station:
  recognition_lang: ru-RU
  devices:
    <Yandex mini 1 device id>:  # device_id вашей колонки
         host: 192.168.1.49
    <Yandex mini 2 device id>:
        host: 192.168.1.45

conversation:
  intents:
    media_player.yandex_station_<Yandex mini 1 device id>: [.+]
    media_player.yandex_station_<Yandex mini 2 device id>: [.+] 

В homeassistant.log ничего. Как отлаживать и куда еще смотреть?

**Comment by AlexxIT** [comment]
1. У Яндекс Мини device ID обычно большими буквами
2. Локальный режим можно проверить в атрибутах объекта колонки: `connection_class: local_push`
3. В последних версиях есть баг с обложками. Но названия треков должны отображаться.

**Comment by stuffmsksu** [comment]
Доброго времени суток.
Есть 2  колонки мини и лайт. `connection_class: local_push`  на обоих. Все работает хорошо если сказать Алиса включи музыку - обложка, перемотка,  громкость  и т.д, все срабатывает мгновенно. Но если сказать включи мой плейлист или какой либо еще из моих плейлистов то не отображает обложки и громкость, перемотка и т.д. идет с задержкой как будто не локальный режим. 
```
entity_picture_local: 
entity_picture:
```
Отсутствуют. С чем может быть проблема?

**Comment by AlexxIT** [comment]
@stuffmsksu с обложкой известный баг, а вот перемотка и громкость - что-то новенькое

**Comment by AlexxIT** [comment]
Картинка поправлена в последней master версии

**Comment by new-kirte** [comment]
@AlexxIT ,

> 1. У Яндекс Мини device ID обычно большими буквами
> 2. Локальный режим можно проверить в атрибутах объекта колонки: `connection_class: local_push`
> 3. В последних версиях есть баг с обложками. Но названия треков должны отображаться.

@AlexxIT  огромное спасибо - большие буквы поправили Яндекс Мини, а у Макса вообще смешанный регистр :). Все заработало
