### ISSUE TITLE
Станция Лайт не появляется

### ISSUE THREAD

**Issue by popstas** [AlexxIT/YandexStation#175]
### Что пробовал делать:
- Перезапускал HA
- Добавлял `devices`

Не знаю детали общения со Станцией, готов помочь добавить поддержку, на уровне потыкать урлы, проверить, что имеется в наличии.

**Comment by Greenvli** [comment]
Prestigio Smartmate Mayak Edition тоже не появляется.

**Comment by AlexxIT** [comment]
@popstas сколько домов в Яндексе?

**Comment by Greenvli** [comment]
Добрый вечер, 2 было и в каждом по устройству
--
Отправлено из Mail.ru для Android вторник, 10 августа 2021г., 21:45 +03:00 от Alex X  ***@***.*** :

***@***.*** сколько домов в Яндексе?

**Comment by popstas** [comment]
У меня 1 дом, по умолчанию, не менял.

**Comment by Greenvli** [comment]
Я поэтому и написал, для чистоты эксперимента проверить бы еще где-то.
--
Отправлено из Mail.ru для Android вторник, 10 августа 2021г., 22:30 +03:00 от Stanislav Popov  ***@***.*** :

**Comment by AlexxIT** [comment]
@popstas можно в браузере открыть этот URL https://quasar.yandex.ru/device_list
Нужно быть залогиненым под тем же аккаунтом Яндекс

**Comment by Greenvli** [comment]
Вот ответ:
{"devices":[{"activation_code":3168863986,"activation_region":"RU","config":{"name":"\u0410\u043b\u0438\u0441\u0430"},"id":"FF98F0456B1BA62D7378F793","name":"\u0410\u043b\u0438\u0441\u0430","platform":"prestigio_smart_mate","promocode_activated":false,"tags":["QUASARINFRASUP-44","plus90"]},{"activation_code":3743462101,"activation_region":"RU","config":{"name":"\u0422\u0432\u0430\u0440\u044c"},"id":"FF98F0455F2A63B5346A5F91","name":"\u0422\u0432\u0430\u0440\u044c","platform":"prestigio_smart_mate","promocode_activated":false,"tags":["QUASARINFRASUP-44","plus90"]}],"status":"ok"}
Но , я еще раз говорю, второй дом я снес, все устройства с него переместил в основной, обновил Вашу замечательную интеграцию, устройства сразу  подхватило. До этого пробовал разные версии. Ни в 1 не видала устройств.
--
Отправлено из Mail.ru для Android среда, 11 августа 2021г., 11:02 +03:00 от Alex X  ***@***.*** :

***@***.*** можно в браузере открыть этот URL  https://quasar.yandex.ru/device_list

**Comment by Greenvli** [comment]
Если надо поэкспериментировать, вечером готов, готов так же стать экспериментатором проверке возможности подключения локального режима. Если это вам интересно
--
Отправлено из Mail.ru для Android среда, 11 августа 2021г., 11:02 +03:00 от Alex X  ***@***.*** :

***@***.*** можно в браузере открыть этот URL  https://quasar.yandex.ru/device_list

**Comment by popstas** [comment]
Тут все данные колонки были, как у соседних:

https://quasar.yandex.ru/device_list
https://iot.quasar.yandex.ru/m/user/devices

У меня в логах были ошибки, которые не касаются колонки напрямую, но видимо влияли.

Деактивация-активация компонента решила проблему!
