### ISSUE TITLE
Станция недоступна после отключения электричества.

### ISSUE THREAD

**Issue by mr-dxdy** [AlexxIT/YandexStation#180]
После отключения электричества в HA Яндекс колонка отображается со статусом "недоступно". Архитектура такая - микротик - Asus роутер - малинка с HA - колонка Алиса. Если HA перезапустить, то колонка подцепится. Как решить эту проблему? Похоже, что HA не может опросить ее, загружаясь быстрее.

**Comment by dmamontov** [comment]
Это проблема реконнекта. попробуйте добавить себе логику из PR https://github.com/AlexxIT/YandexStation/pull/179

У вас появится сервис для принудительного переподключения

**Comment by AlexxIT** [comment]
А как довести до такого состояния? Подробно по шагам. У меня не получается.

**Comment by dmamontov** [comment]
я просто отключаю роутер на время. и потом включаю. чтобы и ha и станция потеряли сеть. далее ждем 20-30 минут и  с вероятность 50/50 произойдет такое поведение.

**Comment by AlexxIT** [comment]
Сам ХА теряет сеть, понятно. Такой кейс я не тестировал

**Comment by AlexxIT** [comment]
Поправил автоматическое соединение с локальной колонкой. Была проблема, когда сервер ХА терял интернет в момент попыток восстановить соединение. Изменения в последней мастер версии.

Локальный режим может возвращаться с задержкой до 5 минут.
