### ISSUE TITLE
Не обновляется список покупок и слетел локальный режим в версии ha 2021.9.5


### ISSUE THREAD

**Issue by runnerfanspb** [AlexxIT/YandexStation#183]
Добрый день. После свежего обновления Почему то слетел локальный режим в станции (в большой и мини). На станции выделены статические ip адреса. Так же отвалился список покупок. В списке пусто, в логах пусто. Версия ha 2021.9.6

**Comment by runnerfanspb** [comment]
после последнего обновления, все снова слетело

**Comment by AlexxIT** [comment]
Duplicate #180 и поправлено в последнем мастере
