### ISSUE TITLE
Яндекс Станция Мини не работает локальный режим

### ISSUE THREAD

**Issue by denozord** [AlexxIT/YandexStation#185]
Добрый день!
Не работает локальный режим яндекс Станции Мини. Возникает ошибка Unsupported cloud media: dialog.
В конфиге прописан
```
yandex_station:
  devices:
    FF98***:  # device_id вашей колонки
      host: 192.168.1.36
```

**Comment by AlexxIT** [comment]
А он когда-нибудь работал?

**Comment by denozord** [comment]
Да :)
Неделю назад точно - но откат на предыдущую версию не помогает

**Comment by AlexxIT** [comment]
А компонент последней версии?

**Comment by denozord** [comment]
Да последней

**Comment by AlexxIT** [comment]
Можно попробовать перезагрузить колонку и сервер ХА (весь сервер)

**Comment by denozord** [comment]
Спасибо :) Полная перезагрузка RPI помогла :)
Можно даже это в FAQ добавить по локальному режиму, а то перезагрузил всё что мог, кроме самой малинки

**Comment by AlexxIT** [comment]
Вообще такого не должно возникать, особенно с прописанным в конфиге host.

**Comment by EvgenySkn** [comment]
AlexxIT, у меня HassWP версии 2021.11.5, на данной версии "HA" проблем с обычной "Яндекс.Станцией" нет, а вот с "Мини" (я про первую версию) есть. После перезагрузки "HA" статус вкл./выкл. колонки "Мини" виден (но это только после перезагрузки, до этого в "HA" даже этого не видно до следующей перезагрузки "HA"), но всё время пишет статус "Бездействие", поскольку отсутствует обратная связь от "Мини" (не показывает реальный уровень громкости на станции, состояние "Пауза", какая музыка проигрывается и обложку альбома и т. д.), хотя из "HA" она успешно управляется. Полный перезапуск "HA", переподключение к сети электропитания Wi-fi-роутера и колонки "Мини" не помогают решить проблему. Я так понимаю, здесь требуется исправление этого бага с вашей стороны, AlexxIT? Просто странно, что с обычной "Яндекс. Станцией" этих проблем нет, а на "Мини" есть. Если вдруг это важно, то обычная подключена к Wi-Fi на 5 ГГц, а "Мини" - 2,4 ГГц.

**Comment by AlexxIT** [comment]
@EvgenySkn роутер дома один? Пробовали прописывать IP-адрес колонки в конфиге?

**Comment by EvgenySkn** [comment]
@AlexxIT, да, роутер один. Нет, не пробовал, после ваших слов сделал это по вашему шаблону из документации к интеграции:
```
yandex_station:
  devices:
    12345678901234567890:  # device_id вашей колонки
      host: 192.168.1.123
      name: Яндекс Станция  # имя можно задать и тут
```
Когда только одну "Мини" в конфиге прописал (думал, что вторую колонку можно не указывать), то у меня и от обычной "Яндекс.Станции" обратная связь отвалилась.)) Тогда добавил и обычную туда же, но для неё не стал указывать строку с IP-адресом, тогда от обеих колонок появилась обратная связь (текущий уровень звука, обложки, статус и т. д.). На всякий случай ещё и на роутере зафиксировал IP-адрес "Мини". Вообще странно, что пришлось вручную прописывать колонки в конфиге, чтобы проблема с обратной связью решилась, ведь раньше обратная связь от "Мини" работала и без этого (проблемы начались примерно в дни выпуска обновлений 3.6-3.6.1 вашей интеграции). Большое спасибо за помощь!
