### ISSUE TITLE
Конвектор

### ISSUE THREAD

**Issue by dim246** [AlexxIT/YandexStation#188]
Добрый день! Отличный модуль, спасибо! Только одна проблема,  в home assistant появился конвектор из яндекс умного дома и отображается как термостат все ок но нет кнопки включения выключения

**Comment by panfmik** [comment]
можете скинуть скрин атрибутов из HA?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.0
