### ISSUE TITLE
Если у вас в конфиге есть другие TTS?

### ISSUE THREAD

**Issue by GlebOlden** [AlexxIT/YandexStation#189]
Подскажите, что нужно сделать, чтобы работала фунцкция воспроизвести Текст. Сейчас при вводе текста и нажатии на кнопку ничего не происходит. В Readme указано читать инструкцию по использованию нескольких TTS, но ссылка никуда не ведет и нигде не описано что нужно сделать для правильной работы.

**Comment by AlexxIT** [comment]
Раздел по нескольким TTS вернулся в документацию
