### ISSUE TITLE
Активационная фраза для сценария уже используется

### ISSUE THREAD

**Issue by BlackWarriorNT** [AlexxIT/YandexStation#193]
Пытаюсь подружить Яндекс.Станцию.Мини и Home Assistant, установил через HACS интеграцию от AlexIT, перезагрузил HA, добавил обычную интеграцию. Колонка не появляется, а в логах пишет это:
`
Logger: homeassistant.components.media_player
Source: custom_components/yandex_station/core/yandex_quasar.py:149
Integration: Медиаплеер (documentation, issues)
First occurred: 20:21:51 (1 occurrences)
Last logged: 20:21:51

Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 80, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 95, in load_speakers
    await self.add_scenario(device_id)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 149, in add_scenario
    assert resp['status'] == 'ok', resp
AssertionError: {'request_id': '3e963bb9-XXXX-XXXX-XXXX-cca2cd782ff0', 'status': 'error', 'code': 'INVALID_VALUE', 'message': 'Активационная фраза для сценария уже используется'}
`
![Буфер обмена01](https://user-images.githubusercontent.com/5547586/137593454-e2a17f86-991e-4aee-b10f-0e9a870a82f4.jpg)
В системе MajorDoMo, эта-же колонка на этом-же аккаунте работает.

**Comment by AlexxIT** [comment]
Так понимаю, в MajorDoMo скопирован алгоритм формирования ID сценариев, поэтому одновременное использование не работает
