### ISSUE TITLE
Conversation: Ошибка при получении ответа

### ISSUE THREAD

**Issue by ProASV** [AlexxIT/YandexStation#194]
В последних версиях HA (или с последними версиями компонента) Алиса перестала отвечать. 
B диалоге (по значку с микрофоном) пишешь что-либо, получаешь сообщение
"К сожалению, произошла ошибка"
Команды типа "включи что-то" выполняются по прежнему.
В логе ошибка:

Source: components/websocket_api/connection.py:134
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20 октября 2021 г., 21:38:11 (7 occurrences)
Last logged: 08:04:39

    [139886790327840] Error handling message: Error handling media_player.yandex_station_<далее ID>
    [139886642133312] Error handling message: Error handling media_player.yandex_station_<далее ID>
    [139886778530208] Error handling message: Error handling media_player.yandex_station_<далее ID>

Компонент: 3.5.0

HA:
Версия | core-2021.10.6
Тип установки | Home Assistant Container
Среда разработки | false
Supervisor | false
Docker | true
Пользователь | root
Виртуальное окружение | false
Версия Python | 3.9.7
Семейство операционных систем | Linux
Версия операционной системы | 4.15.0-159-generic
Архитектура ЦП | x86_64
Часовой пояс | Europe/Moscow

**Comment by ProASV** [comment]
В 3.7.0 и 3.8.0 работает.
Спасибо!

**Comment by AlexxIT** [comment]
Странно. Я не чинил
