### ISSUE TITLE
Чайник

### ISSUE THREAD

**Issue by iswitch** [AlexxIT/YandexStation#197]
Было бы здорово, если можно было бы прокинуть чайник из УДЯ в HA.

**Comment by profx5015** [comment]
Присоединяюсь к просьбе. Хотелось бы иметь возможность пробросить чайник.

**Comment by Den-88** [comment]
Тоже присоединяюсь!

**Comment by lanturn07** [comment]
Тоже прошу. Чайник Полярис pwk 1712cgld.

**Comment by Den-88** [comment]
> Тоже прошу. Чайник Полярис pwk 1712cgld.

И у меня он же!

**Comment by AlexxIT** [comment]
Присылайте мне в личку аккаунт с чайником и налитой водой для экспериментов :)
У меня нет чайника для тестов

**Comment by profx5015** [comment]
> Присылайте мне в личку аккаунт с чайником и налитой водой для экспериментов :)
Написал в телеграме

**Comment by shostko** [comment]
@AlexxIT почему-то чайник в HA получает только статус (вкл/выкл), управление не доступно. Хотя в самом яндексе чайник можно включить/выключить без проблем (голосом, приложением, через квазар).
Подскажи плиз, это я где-то недонастроил или это баг? или может ограничение такое есть?
![image](https://github.com/user-attachments/assets/c356e829-d39a-4942-9ac3-e3b949d433b7)
![image](https://github.com/user-attachments/assets/539e29fa-8d50-41da-b5f0-126e09bb1960)

**Comment by AlexxIT** [comment]
Управление внутри карточки чайника. Так работает ХА

**Comment by shostko** [comment]
> Управление внутри карточки чайника. Так работает ХА

вот в этой карточке нету, или я не там смотрю?
![image](https://github.com/user-attachments/assets/944e5d79-69e4-4f6a-9174-93baef4a3b5e)

**Comment by AlexxIT** [comment]
Можно создать новую issue и приложить туда device diagnostics от интеграции. Похоже чайник от Tuya сильно отличается от других чайников в Яндексе
