### ISSUE TITLE
Ошибка получения сообщения TTS, Получено пустое media_id

### ISSUE THREAD

**Issue by PSreal** [AlexxIT/YandexStation#198]
Здравствуйте.
Прошу помощи.
При отправке "произнести текст" или "выполнить команду"  - на яндекс-станции ничего не происходит. В логах выскакивают ошибки:

**Получено пустое media_id**
Logger: custom_components.yandex_station.media_player
Source: custom_components/yandex_station/media_player.py:656
Integration: Yandex.Station (documentation, issues)
First occurred: 5 ноября 2021 г., 22:56:00 (5 occurrences)
Last logged: 5 ноября 2021 г., 23:26:48

Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.yandex_station.core.utils
Source: custom_components/yandex_station/core/utils.py:226
Integration: Yandex.Station (documentation, issues)
First occurred: 5 ноября 2021 г., 22:56:00 (5 occurrences)
Last logged: 5 ноября 2021 г., 23:26:48

**Ошибка получения сообщения TTS**
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/utils.py", line 226, in get_tts_message
    r = await session.get(url, ssl=False)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

Вхожу из интернета по адресу https://*.duckdns.org/
SSL через Let's Encrypt от duckdns (автоматически)

## System Health

version | core-2021.11.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.75
arch | x86_64
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.16.0
Stage | running
Available Repositories | 949
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 30.8 GB
disk_used | 3.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Duck DNS (1.14.0), MariaDB (2.4.0), Terminal & SSH (9.2.1), NGINX Home Assistant SSL proxy (3.0.2), Samba share (9.5.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 5
mode | storage

</details>

С уважением,
Сергей

**Comment by AlexxIT** [comment]
Какие-то ваши личные проблемы с интернетом у сервера ХА. Сертификаты и DuckDNS тут не при чём. Посмотрите полный лог ошибок, там может чуть подробнее будет ошибка
