### ISSUE TITLE
Алиса слушает пользователя после любого вида TTS

### ISSUE THREAD

**Issue by enselerizer** [AlexxIT/YandexStation#20]
Хочу вызывать TTS, при котором Алиса произнесет заданную фразу и продолжит текущее медиа-действие (например, проигрывание музыки). Однако все варианты вызова tts приводят к тому, что Алиса после вывода фразы ожидает ответа от пользователя (проигрывается звуковой сигнал, сигнализирующий о том, что Алиса слушает, и уменьшается громкость музыки).

Является ли это ограничением Яндекса или багом?

**Comment by AlexxIT** [comment]
Обновление [24.03.2020](https://yandex.ru/support/station/release-notes.html) принесло эту проблему.
Так же поломан функционал ожидания окончания фразы.

Посмотрю что можно сделать как появится свободно время.

**Comment by AlexxIT** [comment]
В последнем релизе больше не слушает

**Comment by ekorsanov01** [comment]
Воспроизводится на последней версии в локальном режиме:

yandex_tts3:
    alias: TTS только для локального режима
    sequence:
    - service: media_player.play_media
      entity_id: media_player.yandex_station
      data:
        media_content_id: смелость sil <[500]> город+а берёт
        media_content_type: dialog

**Comment by AlexxIT** [comment]
Да. Теперь снова слушает. Пока не поправлено...
