### ISSUE TITLE
Уже на протяжении месяца не могу войти в аккаунт яндекса

### ISSUE THREAD

**Issue by Fustie** [AlexxIT/YandexStation#202]
Примерно мессяц назад изменил пароль в яндексе. Везде входит кроме hass.io, просто выводит "Неверный пароль" и подсвечивает логин. Что бы я не пробовал какой ноутбук, компьютер везде теперь выдаёт эту ошибку.

**Comment by Fustie** [comment]
Наверное нашёл причину. Вот что мне возвращает API яндекса на данной строке https://github.com/AlexxIT/YandexStation/blob/abc19e2d341dc8ff5e7b5b9362592e98e413cfd1/custom_components/yandex_station/core/yandex_session.py#L169 - {'error': 'invalid_grant', 'error_description': 'Session not valid'}

**Comment by izverev** [comment]
была такая же проблема, при попытке войти по паролю говорил "неверный пароль", через cookie была такая же ошибка, `Session not valid`  
Нашёл решение в [чате ](https://t.me/c/1337651089/32679) авторизовываться надо именно через **passport.yandex.com** не .ru  
дальше была проблема уже с копированием кук, но это уже вопрос к расширению Copy Cookies

**Comment by AlexxIT** [comment]
@izverev ну я уже не знаю, как объяснять пользователям. В инструкции всего 3 строчки. В пункте 2 явно написано про com. Ссылка ведёт на com сайт.

![image](https://user-images.githubusercontent.com/511909/143586708-bf9228d6-fce8-40e5-b5f8-7cd442764e48.png)

**Comment by izverev** [comment]
@AlexxIT из нашей практики - ничего не помогает, будет жирным и якро красным выделение чего-то не делать - всё равно сделают, всё бестолку, в данном случае можно лишь в скобках написать: 
Авторизуйтесь в [Yandex Passport.com](https://passport.yandex.com/) (passport.yandex.**ru** не работает)

в моём случае в соседней вкладке была открыта как раз страница yandex.passport, поэтому даже не подумал переходить по ссылке из инструкции заново)

а история с паролем не работает или это у меня какие-то глюки?

**Comment by Fustie** [comment]
> @izverev ну я уже не знаю, как объяснять пользователям. В инструкции всего 3 строчки. В пункте 2 явно написано про com. Ссылка ведёт на com сайт.
> 
> ![image](https://user-images.githubusercontent.com/511909/143586708-bf9228d6-fce8-40e5-b5f8-7cd442764e48.png)

У меня ссылка вела на непонятный сайт, который вообще был дохлый. А вот за то что не заметил .com извиняюсь.

**Comment by AlexxIT** [comment]
Это официальный международный сайт Яндекса. По какой-то причине только его куки работают

**Comment by AlexxIT** [comment]
Исправлено в последней бета-версии
