### ISSUE TITLE
Поддержка Yandex-Module2

### ISSUE THREAD

**Issue by anklimov** [AlexxIT/YandexStation#203]
Просьба добавить поддержку Yandex-Module2
Сейчас модуль не появляется в списке обьектов (в отличии, например, от Mini2)

**Comment by AlexxIT** [comment]
Готово в 3.6.1

**Comment by nick2525** [comment]
@AlexxIT не увидел в документации, через модуль на телевизор можно вывести какое-то сообщение из ha?

**Comment by nick2525** [comment]
@AlexxIT а теперь можно вывести сообщение на яндекс модуль 2, чтобы отобразилось на телевизоре?

**Comment by AlexxIT** [comment]
Было что-то такое ещё со времён первой станции. Но функция довольно бестолковая, не стал внедрять
