### ISSUE TITLE
3.6 Release Candidate - для колонки Elari smartbeat сломались элементы управления и функции TTS 

### ISSUE THREAD

**Issue by anklimov** [AlexxIT/YandexStation#208]
После установки RC3.6 у колонки Elari Smartbeat в интерфейсе HA (закладка Свойства) пропали все элементы управления, отображение статуса (Бездействие или Воспроизведение) а также, поля ввода для TTS

При переходе в Свойства плейера никаких сообщений в логе не возникает

В версии 3.5 все работает корректно (включая TTS)

В обоих случаях
HA Core 2021.11.5
supervisor-2021.10.8

**Comment by izibo** [comment]
Тоже самое на ирбисе.

**Comment by izibo** [comment]
Яндекс лайт не в локальной сети тоже. В локальной нормально.

**Comment by AlexxIT** [comment]
Поправлено в последнем мастере
