### ISSUE TITLE
 ERROR (MainThread) [homeassistant.helpers.integration_platform] Error

### ISSUE THREAD

**Issue by meliborn** [AlexxIT/YandexStation#209]
Что то вдруг перестал запускаться home assistant, полез в логи и нашел вот что
<img width="936" alt="Снимок экрана 2021-12-06 в 14 58 40" src="https://user-images.githubusercontent.com/735194/144842186-d1ed9067-d654-4881-b42e-a6345e7aaabc.png">
Есть какие то идеи?

**Comment by AlexxIT** [comment]
Вероятно давно поправлено
