### ISSUE TITLE
Ошибки при установке аддона

### ISSUE THREAD

**Issue by ASSever** [AlexxIT/YandexStation#21]
Пытаюсь установить ваш аддон в homeassistant 

Но при добавлении вашего репозитория 
https://github.com/AlexxIT/YandexStation

В логе вижу следующий текст

20-04-17 04:03:45 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/AlexxIT/YandexStation repository
20-04-17 04:03:48 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/b61114b4/repository.json: [Errno 2] No such file or directory: '/data/addons/git/b61114b4/repository.json'
20-04-17 04:03:48 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/b61114b4/repository.json

Сам репозиторий появляется среди прочих
Но с именем ‘unknown’ и без каких либо аддонов

Возможно я что-то не так делаю...
Помогите пожалуйста

**Comment by AlexxIT** [comment]
Это не аддон hassio. Компонент ставится через hacs или копированием в папку custom_components

**Comment by ASSever** [comment]
> Это не аддон hassio. Компонент ставится через hacs или копированием в папку custom_components

Спасибо попробую так

**Comment by AlexxIT** [comment]
Вот тут в обоих видео есть примеры установки через hacs (другого компонента)
https://github.com/AlexxIT/SonoffLAN

**Comment by ASSever** [comment]
Да
Спасибо

Я нашёл достаточно подробный видеогайд в который входит установка hacs 

https://youtu.be/ny0v8zqrFl4
