### ISSUE TITLE
Spotify через яндекс станции

### ISSUE THREAD

**Issue by martkotur** [AlexxIT/YandexStation#215]
Такой вопрос уже ранее пробегал. И напрямую конечно нельзя. Но вот через НА разве нельзя сделать конвертацию json в формат яндекса с данными спотифая?
В НА стоят интеграции яндекс станции, ямузыки и спотифая. Плюс кастомная интеграция https://github.com/fondberg/spotcast
После первичной настройки, когда на малинке еще не был настроен вывод звука на jack вместо HDMI при запуске spotcast
звук внезапно пошел на ЯС. И хороший звук. ЯМ очень так отстает в этом плане. После ребута малинки фокус уже не прошел. :(

**Comment by AlexxIT** [comment]
Всё сумбурно написано. Не очень понял, что произошло. Какая станция, какие jack, HDMI и прочее

**Comment by martkotur** [comment]
Вопрос собственно, возможна ли реализация конвертации и передачи для воспроизведения на Яндекс станцию контента Спотифай?

Суть сумбура в том, что как-то совпали звезды и на ЯС воспроизвелся трек из спотифая. Следующий трек из плейлиста не воспроизвелся уже. Такое получилось два раза. Воспроизведение 1 трека из плейлиста Спотифая на ЯС. После перезагрузки НА такое уже не воспроизводилось. 
Звук прошел при следующих вводных:
На raspberry был включен вывод звука на HDMI
Установил дополнение спотифай.
Установил интеграцию спотифай.
Установил кастом spotcast
Запускал воспроизведение из spotcast.

**Comment by AlexxIT** [comment]
Яндекс Станции на вход принимают только Bluetooth. Если вы так подключили колонку к малине - звук вполне себе мог пойти. Какие-либо другие способы отправить свою музыку на Станции, на данный момент, неизвестны.
