### ISSUE TITLE
Yandex light 

### ISSUE THREAD

**Issue by Vorchikhin** [AlexxIT/YandexStation#219]
Config entry 'vorc-nikolaj' for yandex_station integration not ready yet: b'<!DOCTYPE html>\n<html><head><title>403</title><meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<style>body{font-family:Arial,sans-serif;margin:0;padding:0;color:#000;background-color:#fff}.header{height:48px}.header__logo{display:inline-block;overflow:hidden;width:130px;height:48px;white-space:nowrap;text-indent:100%;background-repeat:no-repeat;background-position:center bottom}.header__code{font-size:32px;display:inline-block;overflow:hidden;width:76px;height:48px;text-align:center;color:#fff;background-color:#999}.header__logo_lang_ru{background-image:url(//yastatic.net/islands/_/5vJOTgN-leXxtlxIFPiM-vfC24o.png)}.header__logo_lang_en{background-image:url(//yastatic.net/islands/_/fGdVzvAAq7J8px5LpiysN6M_sy8.png)}.content{font-size:15px;line-height:20px;margin:20px 0 30px;padding-left:25px}.content__h1{font-size:21px;font-weight:400}.footer{line-height:30px;height:30px;padding:0 25px;border-top:1px solid #eee}.footer__copyright{font-size:13px}.link{color:#44b}.link:hover{color:#e00}</style>\n<link rel="stylesheet" href="captcha.min.css"/>\n</head><body><div class=\'header\'>\n <a class="header__logo header__logo_lang_ru" href="https://www.yandex.ru/">\xd0\xaf\xd0\xbd\xd0\xb4\xd0\xb5\xd0\xba\xd1\x81</a>\n<div class=\'header__code\'>403</div></div><div class=\'content\'>\n <h1 class="content__h1">\xd0\x94\xd0\xbe\xd1\x81\xd1\x82\xd1\x83\xd0\xbf \xd0\xba&nbsp;\xd0\xbd\xd0\xb0\xd1\x88\xd0\xb5\xd0\xbc\xd1\x83 \xd1\x81\xd0\xb5\xd1\x80\xd0\xb2\xd0\xb8\xd1\x81\xd1\x83 \xd0\xb2\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe \xd0\xb7\xd0\xb0\xd0\xbf\xd1\x80\xd0\xb5\xd1\x89\xd1\x91\xd0\xbd!</h1><p>\xd0\x92\xd0\xbe\xd0\xb7\xd0\xbc\xd0\xbe\xd0\xb6\xd0\xbd\xd0\xbe, \xd0\xb2\xd0\xb0\xd1\x88 \xd0\xba\xd0\xbe\xd0\xbc\xd0\xbf\xd1\x8c\xd1\x8e\xd1\x82\xd0\xb5\xd1\x80 \xd0\xb7\xd0\xb0\xd1\x80\xd0\xb0\xd0\xb6\xd1\x91\xd0\xbd \xd0\xb2\xd1\x80\xd0\xb5\xd0\xb4\xd0\xbe\xd0\xbd\xd0\xbe\xd1\x81\xd0\xbd\xd0\xbe\xd0\xb9 \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb3\xd1\x80\xd0\xb0\xd0\xbc\xd0\xbc\xd0\xbe\xd0\xb9, \xd0\xba\xd0\xbe\xd1\x82\xd0\xbe\xd1\x80\xd0\xb0\xd1\x8f \xd0\xb0\xd0\xb2\xd1\x82\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x82\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb8 \xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd1\x89\xd0\xb0\xd0\xb5\xd1\x82\xd1\x81\xd1\x8f \xd0\xba&nbsp;\xd0\xaf\xd0\xbd\xd0\xb4\xd0\xb5\xd0\xba\xd1\x81\xd1\x83.<br>\xd0\xa0\xd0\xb5\xd0\xba\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xb4\xd1\x83\xd0\xb5\xd0\xbc \xd0\xb2\xd0\xb0\xd0\xbc \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd0\xb8\xd1\x82\xd1\x8c \xd0\xba\xd0\xbe\xd0\xbc\xd0\xbf\xd1\x8c\xd1\x8e\xd1\x82\xd0\xb5\xd1\x80 \xd0\xbd\xd0\xb0&nbsp;\xd0\xb2\xd0\xb8\xd1\x80\xd1\x83\xd1\x81\xd1\x8b \xd0\xb8\xd0\xbb\xd0\xb8 \xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd1\x82\xd0\xb8\xd1\x82\xd1\x8c\xd1\x81\xd1\x8f \xd0\xba&nbsp;\xd0\xb0\xd0\xb4\xd0\xbc\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb0\xd1\x82\xd0\xbe\xd1\x80\xd1\x83 \xd0\xb2\xd0\xb0\xd1\x88\xd0\xb5\xd0\xb9 \xd1\x81\xd0\xb5\xd1\x82\xd0\xb8.</p><p>\xd0\x95\xd1\x81\xd0\xbb\xd0\xb8 \xd1\x83&nbsp;\xd0\xb2\xd0\xb0\xd1\x81 \xd0\xb2\xd0\xbe\xd0\xb7\xd0\xbd\xd0\xb8\xd0\xba\xd0\xbb\xd0\xb8 \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb1\xd0\xbb\xd0\xb5\xd0\xbc\xd1\x8b \xd0\xb8\xd0\xbb\xd0\xb8 \xd0\xb2\xd1\x8b&nbsp;\xd1\x85\xd0\xbe\xd1\x82\xd0\xb8\xd1\x82\xd0\xb5 \xd0\xb7\xd0\xb0\xd0\xb4\xd0\xb0\xd1\x82\xd1\x8c \xd0\xb2\xd0\xbe\xd0\xbf\xd1\x80\xd0\xbe\xd1\x81 \xd0\xbd\xd0\xb0\xd1\x88\xd0\xb5\xd0\xb9 \xd1\x81\xd0\xbb\xd1\x83\xd0\xb6\xd0\xb1\xd0\xb5 \xd0\xbf\xd0\xbe\xd0\xb4\xd0\xb4\xd0\xb5\xd1\x80\xd0\xb6\xd0\xba\xd0\xb8, \xd0\xbf\xd0\xbe\xd0\xb6\xd0\xb0\xd0\xbb\xd1\x83\xd0\xb9\xd1\x81\xd1\x82\xd0\xb0, \xd0\xb2\xd0\xbe\xd1\x81\xd0\xbf\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xb7\xd1\x83\xd0\xb9\xd1\x82\xd0\xb5\xd1\x81\xd1\x8c <a class="link" href="https://yandex.ru/support/smart-captcha/?unique_key=f4cef8fe-18d05aca-acc2eae5-4ae58dec" onclick="ym(15897442, \'reachGoal\', \'support_complain\', { \'req_id\': \'1639693077197203-6651761258189714097-sas2-0798-sas-l7-balancer-8080-BAL\' }); return true;">\xd1\x84\xd0\xbe\xd1\x80\xd0\xbc\xd0\xbe\xd0\xb9 \xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb9 \xd1\x81\xd0\xb2\xd1\x8f\xd0\xb7\xd0\xb8</a>.</p>\n <p>f4cef8fe-18d05aca-acc2eae5-4ae58dec</p>\n</div><div class=\'footer\'><span class=\'footer__copyright\'>\xc2\xa9&nbsp;\xd0\xaf\xd0\xbd\xd0\xb4\xd0\xb5\xd0\xba\xd1\x81</span></div><script type="text/javascript">(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)}; m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)}) (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(15897442, "init", { clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, ut:"noindex", params:{ "service": "web", "req_id": "1639693077197203-6651761258189714097-sas2-0798-sas-l7-balancer-8080-BAL", "ident_type": "1", "unique_key": "f4cef8fe-18d05aca-acc2eae5-4ae58dec" } });</script><noscript><div><img src="https://mc.yandex.ru/watch/15897442?ut=noindex" style="position:absolute; left:-9999px;" alt="" /></div></noscript></body></html>'; Retrying in background

Несколько раз удалял интеграцию и устанавливал но проблема всё та же.
Недавно обновлял НА до версии 2021.12.2
Yandex.Station мастер версия

**Comment by AlexxIT** [comment]
#218
