### ISSUE TITLE
Не удалось вызвать службу media_player/volume_up '<' non suported between instances of 'Nonetype' and 'int'

### ISSUE THREAD

**Issue by dangerdanik** [AlexxIT/YandexStation#220]
Добрый день. После обновления на последнюю версию. При изменении громкости ошибка - Не удалось вызвать службу media_player/volume_up '<' non suported between instances of 'Nonetype' and 'int'. Возможно ли исправить? Или я могу сам как то это исправить? 

У меня так же в сценарии прописано что бы Алиса говорила, например при открытии двери. Но теперь громкость не регулируется. Вот мой сценарий:
`alice_say_door_unlocked:
    alias: Алиса скажет дверь открыта
    sequence:
    - service: tts.yandex_station_say
      entity_id: media_player.yandex_station_myToken  # замените на вашу колонку
      data_template:
        message: Внимание! Входная дверь открыта
        options:
          volume_level: 0.6`
Раньше громкость возвращалась к тому параметру как и была, сейчас переключается на 6 и так остается.

**Comment by AlexxIT** [comment]
Вероятно поправлено в последнем релизе

**Comment by dangerdanik** [comment]
Добрый день.

Обновил интеграцию. Проблема решена. Спасибо большое за Ваш труд!

С уважением, Бутин Данил.


вс, 19 дек. 2021 г. в 18:30, Alex X ***@***.***>:
