### ISSUE TITLE
Добавить поддержку от устройств Hite Pro

### ISSUE THREAD

**Issue by kolek15** [AlexxIT/YandexStation#226]
API: https://drive.google.com/file/d/1CwbzVhRAUJBeNN8zK5XFdYasFg8l9Mfq/view

**Comment by kolek15** [comment]
Я добавил реле Hite Pro F1 в яндекс станицю, оно отобразилось у меня там как лампа, но в HA не пробрасывается.

**Comment by kolek15** [comment]
А вот сейчас каким то чудом пробросилось в виде лампы отобразилось.

**Comment by AlexxIT** [comment]
Какие-то конкретные устройства поддерживать не планирую. Их должен поддерживать Яндекс, а не этот компонент
