### ISSUE TITLE
Cannot connect to host yandex.ru:443 ssl:default [Try again]

### ISSUE THREAD

**Issue by Mitjay** [AlexxIT/YandexStation#227]
Добрый день! Некоторое время назад появилась ошибка "Повторная настройка: Cannot connect to host yandex.ru:443 ssl:default [Try again]". Перепробовал все возможные способы авторизации при добавлении интеграции, и логин/пароль и QR и токен (меняя разумеется настройки авторизации в учетке yandex). Но результат один и тот же. Пробовал отключать антивирус, не помогло. Интеграция перестала работать больше месяца назад. Ошибка из лога ниже.
Буду благодарен за помощь в решении данной проблемы.

Ошибки из лога:
2022-01-02 04:48:08 INFO (MainThread) [homeassistant.setup] Setting up yandex_station
2022-01-02 04:48:08 INFO (MainThread) [homeassistant.setup] Setup of domain yandex_station took 0.0 seconds
2022-01-02 04:48:13 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Мой_Логин' for yandex_station integration not ready yet: Cannot connect to host yandex.ru:443 ssl:default [Try again]; Retrying in background

**Comment by AlexxIT** [comment]
Проблема простая - сервер ХА не может подключиться к Яндексу. А почему он не может это сделать только вам виднее

**Comment by OlegPitsenko** [comment]
А какие есть варианты для Украины с такой ошибкой, vpn на роутере настроено, доступ к yandex есть?

**Comment by Mitjay** [comment]
> Проблема простая - сервер ХА не может подключиться к Яндексу. А почему он не может это сделать только вам виднее

Спасибо за наводку! ) Сменил настройки фильтрации на роутере и интеграция вновь заработала.
Сменил Cloudflare DNS на Яндекс.DNS
![image](https://user-images.githubusercontent.com/88985194/154473091-241dfff7-f628-4f4a-b3e9-a4a62e8ce7b2.png)

**Comment by OlegPitsenko** [comment]
Спасибо большое, помогло.

**Comment by Alex-Pereput** [comment]
Спасибо, [Mitjay], тоже помогло.
