### ISSUE TITLE
Качество при стриминге музыки

### ISSUE THREAD

**Issue by degorychev** [AlexxIT/YandexStation#228]
Во первых, огромное спасибо за такую возможность! Наконец то есть возможность удобного прослушивания музыки на ресивере.
На сколько я могу судить, принцип работы такой:

1. Яндекс станция сообщает HA текущий воспроизводимый трек
2. НА идет в яндекс музыку и скачивает эту песню
3. НА шарит эту песню по сети и по длна кидает ссылку другому плееру и та начинает играть просто песню по факту с сервера умного дома

Через костыли глянул что воспроизводится на колонки и был разочарован, оказывается если стриминг был включен с яндекс станции макс - то воспроизводится mp3 файл с битрейтом 320кбит/с, а с яндекс станции мини - 128кбит/с.
Полагаю, что это связано напрямую с тем, какое именно качество играет та или иная колонка, но в случае с хорошей аудиосистемой хотелось бы слушать треки в максимально возможном качестве, а включать треки с простенькой Мини. 
Нельзя ли во втором пункте скачивать песню в максимальном качестве?

PS: телевизор Samsung UE32F4500AK при активации стриминга ведет себя странно, сначала говорил что для функции timeshift нужно подключить usb диск(!?) А теперь жалуется на настройки сети, покопаю еще, ибо с компьютеров он файлы читает довольно четко...

**Comment by AlexxIT** [comment]
ХА ничего не скачивает, а напрямую транслирует песню, через себя. Средствами этого компонента нет возможности получить эту же песню другого качества.

Возможно для задачи подойдёт такой компонент:
https://github.com/alryaz/hass-yandex-music-browser

С старыми телевизорами Samsung известная проблема, я писал такое в документации.

**Comment by sbvitok** [comment]
Чисто для истории, перепроверил сейчас качество mp3 с мини 2 станции, стремится 320кибт/с
Станция 2 тоже 320кбит/с стримит.
Вангую что сейчас все колонки стримят 320кбит/с

Проверял через DLNA ресивер который говорит какой файл в него загрузили.

**Comment by AlexxIT** [comment]
Сейчас качество не зависит от колонки и всегда максимальное
