### ISSUE TITLE
HA не перезагружается из web-интерфейса: Station connect error

### ISSUE THREAD

**Issue by aatemes** [AlexxIT/YandexStation#23]
...а из systemctl перезагружается, но только через 1-2 минуты по SIGKILL. 
Конфигурация: homeassistant-0.109.2 in a Virtual Environment (до этого был 108.6 с теми же симптомами) 
Версия Python: 
Package: python3.7
Version: 3.7.3-2+deb10u1

Последние строки в "syslog | grep hass":

May  2 00:09:23 pi-redarmy hass[15021]: 2020-05-02 00:09:23 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
May  2 00:09:23 pi-redarmy hass[15021]: Traceback (most recent call last):
May  2 00:09:23 pi-redarmy hass[15021]:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
May  2 00:09:23 pi-redarmy hass[15021]:     result = self.fn(*self.args, **self.kwargs)
May  2 00:09:23 pi-redarmy hass[15021]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zeroconf/__init__.py", line 111, in stop_zeroconf
May  2 00:09:23 pi-redarmy hass[15021]:     zeroconf.close()
May  2 00:09:23 pi-redarmy hass[15021]:   File "/srv/homeassistant/lib/python3.7/site-packages/zeroconf/__init__.py", line 2654, in close
May  2 00:09:23 pi-redarmy hass[15021]:     # on send errors, log the exception and keep going
May  2 00:09:23 pi-redarmy hass[15021]:   File "/srv/homeassistant/lib/python3.7/site-packages/zeroconf/__init__.py", line 1239, in del_reader
May  2 00:09:23 pi-redarmy hass[15021]: KeyError: <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0>
May  2 00:09:23 pi-redarmy hass[15021]: 2020-05-02 00:09:23 ERROR (MainThread) [custom_components.yandex_station.utils] Station connect error:

(последняя строчка отсутствует в логе HA, но есть в syslog, поэтому приложил именно его)

**Comment by AlexxIT** [comment]
Слышал о такой проблеме. Не использую venv, поэтому сложно повторить. Попытаюсь что-то сделать

**Comment by Beetle-II** [comment]
Подтверждаю. Аналогичная проблема.
Venv, HA версии 0.109.6

**Comment by AlexxIT** [comment]
Вроде починил, проверьте

**Comment by aatemes** [comment]
Подтверждаю, проблема не воспроизводится, HA перезагружается корректно. Спасибо!
