### ISSUE TITLE
Яндекс не появляется на дашборде  и на entity

### ISSUE THREAD

**Issue by Umarkhabiliy** [AlexxIT/YandexStation#232]
Всем привет я сделал все по инструктцю, но у меня на дашборде не пойевляется яндекс, несколко раз перезапускал но ничего не изменился

<a href="https://imgbb.com/"><img src="https://i.ibb.co/HD91wrY/hacs.png" alt="hacs" border="0" width=300></a>
<a href="https://ibb.co/1nPGb7s"><img src="https://i.ibb.co/wLPhYBJ/yaml.png" alt="yaml" border="0" width=300></a>
<a href="https://ibb.co/ZJwdShL"><img src="https://i.ibb.co/KGQ6D90/all.png" alt="all" border="0" ></a>

**Comment by AlexxIT** [comment]
А почему вы добавляете компонент устаревшим способом? Возможно Яндекс от вас капчу хочет

**Comment by Umarkhabiliy** [comment]
Можете по подробно дать информацию

**Comment by Umarkhabiliy** [comment]
кто нибудь знает?

**Comment by Umarkhabiliy** [comment]
Алекс можете по этапно объяснять

**Comment by degorychev** [comment]
> кто нибудь знает?

Читайте ридми, пункт "Настройка". Там все подробно расписано, к тому же автор ее недавно переработал.

**Comment by Umarkhabiliy** [comment]
> > кто нибудь знает?
> 
> Читайте ридми, пункт "Настройка". Там все подробно расписано, к тому же автор ее недавно переработал.


    QR-код - рекомендуется, самый удобный способ
    Пароль - при обычной авторизации
    Одноразовый пароль - из приложения Яндекс.Ключ, при включенной двухфакторной авторизации
    Ссылка на E-mail - поддерживается не на всех аккаунтах
    Cookies - компонент подскажет, что нужно сделать
    Токен - можно скопировать ТОЛЬКО из другого сервера Home Assistant, где уже была пройдена авторизация
    
    вы этих имеете в виду? то если да не одного из них не понел

**Comment by degorychev** [comment]
> > > кто нибудь знает?
> > 
> > 
> > Читайте ридми, пункт "Настройка". Там все подробно расписано, к тому же автор ее недавно переработал.
> 
> ```
> QR-код - рекомендуется, самый удобный способ
> Пароль - при обычной авторизации
> Одноразовый пароль - из приложения Яндекс.Ключ, при включенной двухфакторной авторизации
> Ссылка на E-mail - поддерживается не на всех аккаунтах
> Cookies - компонент подскажет, что нужно сделать
> Токен - можно скопировать ТОЛЬКО из другого сервера Home Assistant, где уже была пройдена авторизация
> 
> вы этих имеете в виду? то если да не одного из них не понел
> ```

При добавлении интеграции в HA (В настройках, кнопочками, без всяких правок файлов) вас там спросят какой способ авторизации вам предпочтительнее

**Comment by Umarkhabiliy** [comment]
спасибо вам все получился
