### ISSUE TITLE
Platform yandex_station does not generate unique ID

### ISSUE THREAD

**Issue by mr-dxdy** [AlexxIT/YandexStation#233]
После перезапуска HA в логах проскакивает эта ошибка

```
Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:592
Integration: Медиаплеер (documentation, issues)
First occurred: 14:49:22 (1 occurrences)
Last logged: 14:49:22

Platform yandex_station does not generate unique IDs. ID <ID code> is already used by media_player.yandex_station_<ID code> - ignoring media_player.yandex_station_<ID code>
```

Куда копать? Почему в логах эта ошибка? На работоспособность колонки это не влияет.

**Comment by AlexxIT** [comment]
Какой версии интеграция и ХА? Интеграция настроена через YAML?

**Comment by mr-dxdy** [comment]
- Home Assistant 2021.12.10  
- YandexStation 3.8.0. 

Да, через YAML.

**Comment by AlexxIT** [comment]
Логин/пароль из YAML нужно убрать

**Comment by mr-dxdy** [comment]
@AlexxIT спасибо. Помогло.

**Comment by AlexxIT** [comment]
Нужно починить создание интеграции из YAML
