### ISSUE TITLE
Не корректно работает установка громкости extra в режиме dialog 

### ISSUE THREAD

**Issue by RestOp** [AlexxIT/YandexStation#239]
Добрый день, 

большое спасибо за Ваш аддон!

Выявил баг.
![image](https://user-images.githubusercontent.com/46259141/151426531-6cfdce2e-e720-4883-aaf9-cdd0cc68a61f.png)
В этом варианте, но в режиме dialog некорректно срабатывает установка extra громкости.
Первый текст колонка говорит с обычной громкостью, и только если не дожидаясь завершения слушания колонкой диалога запустить второй текст, он говорится с extra громкостью.
Я всегда использую dialog из-за ограничения в 100 символов, и хотелось бы использовать функцию extra громкости, поэтому прошу поправить ее.

Спасибо большое заранее.

PS
Верно же я понимаю, что нет варианта обойти ограничение в 100 символов, кроме как dialog?

**Comment by moskovskiy82** [comment]
Тоже самое. Но не работает повышение громкости и в режиме диалог. Логи пустые

**Comment by dext0r** [comment]
Аналогично. Скорее всего связано с неверным порядком команд из-за отсутствия await на изменение громкости.
```
2022-02-28 20:00:26 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Мини Комната => local | {'command': 'serverAction', 'serverActionEventPayload': {'type': 'server_action', 'name': 'update_form', 'payload': {'form_update': {'name': 'personal_assistant.scenarios.repeat_after_me', 'slots': [{'type': 'string', 'name': 'request', 'value': 'бла-бла-бла'}]}, 'resubmit': True}}}
2022-02-28 20:00:26 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Мини Комната => local | {'command': 'setVolume', 'volume': 0.9}
```

**Comment by RestOp** [comment]
Я кажется понял почему, на одной кологке лайте у меня прошивка последняя. А одну не использовал. Последнее время стал зпмечать, что когда посылаешь команду колонке на ттс, она гачинает произносить текст сразу, а сиатус speaking появляется только через несколько секунд. Вся логика работы страдает. Ну и с громкостью тоже самое , не успевает ее ставить. Нужно что-то кооректировать в аддоне видимо

**Comment by golds69** [comment]
> Я кажется понял почему, на одной кологке лайте у меня прошивка последняя. А одну не использовал. Последнее время стал зпмечать, что когда посылаешь команду колонке на ттс, она гачинает произносить текст сразу, а сиатус speaking появляется только через несколько секунд. Вся логика работы страдает. Ну и с громкостью тоже самое , не успевает ее ставить. Нужно что-то кооректировать в аддоне видимо

Подтверждаю. Колонки Мини и Лайт. На обеих не работает громкость extra в режиме dialog. Статус SPEAKING появляется через 2-3 сек. после начала воспроизведения

**Comment by RestOp** [comment]
> Подтверждаю. Колонки Мини и Лайт. На обеих не работает громкость extra в режиме dialog. Статус SPEAKING появляется через 2-3 сек. после начала воспроизведения

Но дело не громкости extra, а в этой задержке, которая рушит всю работу, в частности создает проблему с громкостью

**Comment by tuxamat** [comment]
аналогично

**Comment by dext0r** [comment]
Предпринял попытку отрефакторить установку громкости, для моих кейсов проблема решилась. Можете пробовать подменить `media_player.py` на этот файл - https://github.com/dext0r/YandexStation/blob/refactor-tts-volume/custom_components/yandex_station/media_player.py


> Подтверждаю. Колонки Мини и Лайт. На обеих не работает громкость extra в режиме dialog. Статус SPEAKING появляется через 2-3 сек. после начала воспроизведе

Похоже что-то изменилось в прошивке станции, что она стала отдавать первое обновление статуса с большой задержкой, а `SPEAKING` для коротких фраз иногда вообще не появляется. Сам компонент тут не причём. Выглядит это примерно так (см. время):

```
2022-04-04 23:14:23 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Мини Комната => local | {'command': 'serverAction', 'serverActionEventPayload': {'type': 'server_action', 'name': 'update_form', 'payload': {'form_update': {'name': 'personal_assistant.scenarios.repeat_after_me', 'slots': [{'type': 'string', 'name': 'request', 'value': 'Погода в Москве ожидается пасмурная и холодная'}]}, 'resubmit': True}}}
2022-04-04 23:14:29 DEBUG (MainThread) [custom_components.yandex_station.media_player] IDLE -> SPEAKING
2022-04-04 23:14:29 DEBUG (MainThread) [custom_components.yandex_station.media_player] SPEAKING -> LISTENING
2022-04-04 23:14:29 DEBUG (MainThread) [custom_components.yandex_station.media_player] LISTENING -> IDLE

2022-04-04 23:22:30 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Мини Комната => local | {'command': 'serverAction', 'serverActionEventPayload': {'type': 'server_action', 'name': 'update_form', 'payload': {'form_update': {'name': 'personal_assistant.scenarios.repeat_after_me', 'slots': [{'type': 'string', 'name': 'request', 'value': 'раз'}]}, 'wait': False}}}
2022-04-04 23:22:36 DEBUG (MainThread) [custom_components.yandex_station.media_player] IDLE -> LISTENING
2022-04-04 23:22:36 DEBUG (MainThread) [custom_components.yandex_station.media_player] LISTENING -> IDLE
```

**Comment by RestOp** [comment]
Что же делать?

**Comment by RestOp** [comment]
Кстати, если что-то сказать Алисе, то статус LISTENING появляется сразу!

**Comment by RestOp** [comment]
> Предпринял попытку отрефакторить установку громкости, для моих кейсов проблема решилась. Можете пробовать подменить `media_player.py` на этот файл - https://github.com/dext0r/YandexStation/blob/refactor-tts-volume/custom_components/yandex_station/media_player.py

И тут не совсем понял, как может решится проблема, если есть вышеописанное запаздывание? Я заменил этот файл у себя, но ничего не поменялось

**Comment by dext0r** [comment]
> И тут не совсем понял, как может решится проблема, если есть вышеописанное запаздывание? Я заменил этот файл у себя, но ничего не поменялось
 
Мои правки решают не запаздывание, а установку и возвращение громкости в режиме `dialog` (этот ишью ведь об этом). Решить проблему запаздывания со стороны компонента невозможно.

**Comment by RestOp** [comment]
> Мои правки решают не запаздывание, а установку и возвращение громкости в режиме `dialog` (этот ишью ведь об этом). Решить проблему запаздывания со стороны компонента невозможно.

Так оно и так работало, если текст был длинный и он успевал это сделать)))

**Comment by dext0r** [comment]
> Так оно и так работало, если текст был длинный и он успевал это сделать)))

Он должен быть супер-длинным :) Большинство моих уведомлений укладываются в 7 секунд, которые она тупит после отправки команды `personal_assistant.scenarios.repeat_after_me`. Причем в этот момент станция даже на вебсокетные пинги не отвечает:
```
> websocat_linux64 --ping-interval=1 -vk wss://192.168.0.30:1961
{"conversationToken": "***", "id": "1edb789e-1546-44bc-b003-7caf07b8b323", "payload": {"command": "serverAction", "serverActionEventPayload": {"type": "server_action", "name": "update_form", "payload": {"form_update": {"name": "personal_assistant.scenarios.repeat_after_me", "slots": [{"type": "string", "name": "request", "value": "ку"}]}, "resubmit": true}}}, "sentTime": 1649152807775}
[INFO  websocat::ws_peer] Sending WebSocket ping
[INFO  websocat::ws_peer] Received WebSocket ping
[INFO  websocat::ws_peer] Sending WebSocket ping
[INFO  websocat::ws_peer] Sending WebSocket ping
[INFO  websocat::ws_peer] Sending WebSocket ping
[INFO  websocat::ws_peer] Sending WebSocket ping
[INFO  websocat::ws_peer] Sending WebSocket ping
[INFO  websocat::ws_peer] Sending WebSocket ping
# тут куча изменений aliceState пришедших пачкой
[INFO  websocat::ws_peer] Received a pong from websocket; RTT = 6.041992338s
[INFO  websocat::ws_peer] Received a pong from websocket; RTT = 5.041966512s
[INFO  websocat::ws_peer] Received a pong from websocket; RTT = 4.042293013s
[INFO  websocat::ws_peer] Received a pong from websocket; RTT = 3.042762338s
[INFO  websocat::ws_peer] Received a pong from websocket; RTT = 2.042284714s
[INFO  websocat::ws_peer] Received a pong from websocket; RTT = 1.042757881s
[INFO  websocat::ws_peer] Received a pong from websocket; RTT = 42.177838ms
```

**Comment by dext0r** [comment]
На данный момент тормоза в обновлении alice_state у меня пропали. А у вас? Скорее всего ишью можно закрывать.

**Comment by RestOp** [comment]
Слушайте, вроде бы действительно стало лучше, но все равно местами задержка есть. Вроде бы она была когда я после долгого времени отправил Алисе TTS, после этого статсы работали нормально.
Но сейчас нужно дождаться, чтобы она снова ушла в слип и проверить именно "первое слово"

**Comment by AlexxIT** [comment]
Немного подкрутил в последнем мастере. Не факт, что будет идеально из-за случайных задержек в выполнении команд колонкой.
