### ISSUE TITLE
MediaPlayerDevice is deprecated

### ISSUE THREAD

**Issue by allmoney** [AlexxIT/YandexStation#24]
Log Details (WARNING)
Logger: homeassistant.components.media_player
Source: components/media_player/__init__.py:938
Integration: Media player (documentation, issues)
First occurred: 9:46:58 PM (2 occurrences)
Last logged: 9:46:58 PM

MediaPlayerDevice is deprecated, modify YandexStation to extend MediaPlayerEntity
MediaPlayerDevice is deprecated, modify YandexStationHDMI to extend MediaPlayerEntity

**Comment by AlexxIT** [comment]
Поправлено
