### ISSUE TITLE
Message malformed: extra keys not allowed @ data['sequence'][0]['script']

### ISSUE THREAD

**Issue by msazanov** [AlexxIT/YandexStation#242]
Я сразу извиняюсь за глупый вопрос, но я уже долго не могу разобраться с тем как заставить алису сказать что-то шепотом, скрипты из примеров у меня к сожалению не работают, появляется ошибка Message malformed: extra keys not allowed @ data['sequence'][0]['script']
данную проблему обошел тем что воспроизвожу речь через сервис. Подскажите что я делаю не так
![Снимок экрана от 2022-02-13 16-20-10](https://user-images.githubusercontent.com/4469838/153755241-5d5bef4b-67ea-4441-a941-6c774f5f8567.png)
?

**Comment by NikitaKorneev** [comment]
Пожалуйста, на будущее – во-первых нужен ваш код чтобы посмотреть что вы, возможно, вводите не так.

**Comment by msazanov** [comment]
Код брал с главной странице
script:
  yandex_tts:
    alias: TTS c эффектами
    sequence:
    - service: media_player.play_media
      entity_id: media_player.yandex_station  # замените на вашу колонку
      data:
        media_content_id: <speaker audio="alice-sounds-game-win-1.opus"> sil <[500]> Объявление погоды на сегодня...
        media_content_type: dialog  # работает только на локальной колонке

Подставил только свою колонку, пастил этот код я в разделе автоматизации/скрипты в редакторе yaml.
Проблема в том что такая ошибка у меня возникает практически при любом скрипте, возможно я нуб и просто его использую не в том месте, и по этому прошу помощи

**Comment by NikitaKorneev** [comment]
@msazanov я не хочу показаться токсичным, но давай ещё раз.

Можно увидеть **ТВОЙ** код. То как ты делаешь запрос? Не надо копировать код из инструкции. 

Потом, прикрепи сюда то что выдаёт лог по этой ошибке. Найдёшь в логах.
