### ISSUE TITLE
'В сценарии должно быть хотя бы одно действие с устройствами'

### ISSUE THREAD

**Issue by dikodim** [AlexxIT/YandexStation#244]
Здравствуйте, помогите разобраться.
переустанавливал и перезаходил по разному, но станция никак не подключатся, в устройствах интеграции пусто.

Logger: homeassistant.components.media_player
Source: custom_components/yandex_station/core/yandex_quasar.py:158
Integration: Медиаплеер ([documentation](https://www.home-assistant.io/integrations/media_player), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22))
First occurred: 19:16:53 (1 occurrences)
Last logged: 19:16:53

Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 84, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 104, in load_speakers
    await self.add_scenario(device_id)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 158, in add_scenario
    assert resp['status'] == 'ok', resp
AssertionError: {'request_id': 'bae16137-b3b6-459a-acef-8213b2c44fc8', 'status': 'error', 'code': 'INVALID_VALUE', 'message': 'В сценарии должно быть хотя бы одно действие с устройствами'}

**Comment by mega-d** [comment]
Точно то же самое сегодня произошло, ждём решения

**Comment by BopoH1978** [comment]
Аналогично. Похоже что то поменялось у яндекса. С утра работало.

**Comment by AlexxIT** [comment]
#243

**Comment by ikey-ru** [comment]
Та же история. 
Потратил час в поисках проблемы, пока не залез сюда и не увидел, что это не только у меня.

**Comment by korolevsv** [comment]
У меня аналогичное сообщение при вызове как службы tts.yandex_station_say, так и tts.google_translate_say.
Раньше (по крайней мере tts.google_translate_say) работало
