### ISSUE TITLE
Дублируется название испольнителя в media_title

### ISSUE THREAD

**Issue by esavich** [AlexxIT/YandexStation#245]
в поле media_title кроме названия песни прилетает еще и и артист, через точку, вот как-то примерно так
```
media_title: Wonderwall. Oasis
media_artist: Oasis
```
или там 
```
media_title: Pretty Fly (For a White Guy). The Offspring
media_artist: The Offspring
```
и так со всеми треками, это не какой-то единичный глюк, выглядит на мой взгляд как-то не правильно, да и громоздко, особенно в карточке плеера. 

![image](https://user-images.githubusercontent.com/3369102/154853643-ebb6e14a-e868-422c-a8ca-fcc96fe0fcaf.png)
Или это фича ? мб тогда настройку какую прикрутить ?

я нашел где руками это выпилить (https://github.com/AlexxIT/YandexStation/blob/master/custom_components/yandex_station/media_player.py#L553) там к title подклеивается subtitle, убрал - работает, но хочется то и обновляться, на python не пишу, так чо PR не запилю (

**Comment by AlexxIT** [comment]
Поправлено в последней мастер-версии
