### ISSUE TITLE
TTS issue Не работает TTS

### ISSUE THREAD

**Issue by baronrustamov** [AlexxIT/YandexStation#247]
В логе: 

**aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host iot.quasar.yandex.ru:443 ssl:default [Try again]**

В меню колонки на главной странице вместо поля ввода текста/команды теперь:
**Text to speech has moved to the media browser.**

А автоматизациях работают только команды, текста теперь нет.

**Comment by baronrustamov** [comment]
In automation type **text** stoped working, only **command** works

**Comment by inferusvv** [comment]
@baronrustamov по какой причине тике закрыли? Как через UI теперь запустить TTS?

**Comment by baronrustamov** [comment]
can't start TTS over UI

**Comment by moskovskiy82** [comment]
Тоже самое. В списке браузера есть Yandex TTS но колонок там нет

**Comment by PhantoMMM** [comment]
Можно откатиться на версию HA 2022.2.9- там всё работает.

**Comment by baronrustamov** [comment]
@AlexxIT  Any fix planned?

**Comment by jehy** [comment]
Вот тут автор отписал https://github.com/AlexxIT/YandexStation/issues/260 - это обновление Home Assistant, а не интеграции с колонкой. Оторвали это поле :(
Там же пишет, что попробует восстановить.

**Comment by AlexxIT** [comment]
`Cannot connect to host` это проблема с интернетом. Второй вопрос это дубликат #260
