### ISSUE TITLE
Команда cancelVoiceDialog не работает?

### ISSUE THREAD

**Issue by dmitry-korolev** [AlexxIT/YandexStation#25]
Кажется, что команда cancelVoiceDialog либо не работает, либо её вообще нет. По-крайней мере, [тут](https://documenter.getpostman.com/view/525400/SWLfd8et?version=latest) она не встречается.

В качестве замены можно использовать media_player.play_media с данными 
```
{
    "media_content_id": "Хватит",
    "media_content_type": "command"
}
```
Не уверен, что это лучшее решение =)

**Comment by AlexxIT** [comment]
Да, её поломали в последних прошивках
