### ISSUE TITLE
Некорректно работает extra: volume_level

### ISSUE THREAD

**Issue by IvanGavrilenko** [AlexxIT/YandexStation#253]
Станция Yandex mini

Пример из описания:
```script:
  alice_custom_volume2:
    sequence:
    - service: media_player.play_media
      entity_id: media_player.yandex_station  # замените на вашу колонку
      data:
        media_content_id: Внимание! Важное сообщение...
        media_content_type: text  # поддерживается text и dialog
        extra:
          volume_level: 0.8
```
При попытке вызвать с media_content_type: text выдает ошибку "Не удалось вызвать службу media_player.play_media. Unknown error"

При вызове с media_content_type: text :
- Включается колонка (фиолетовый кружок на станции)
- проговаривается текст
- ЗАТЕМ меняется уровень звука (показывается зеленой подсветкой)
- звук возвращается на прежний уровень.

То есть не проговаривается фраза на новом уровне громкости, а проговаривается на текущем уровне, громкость меняется и откатывается обратно.

**Comment by tuxamat** [comment]
у меня с text нормально работает, с dialog игнорирует extra volume, проговаривает на системной громкости.

**Comment by djudev** [comment]
У меня с dialog такая же ситуация, как описано выше

**Comment by dredius** [comment]
А у меня никак не реагируют на громкость, всегда стандартная

**Comment by AlexxIT** [comment]
#239
