### ISSUE TITLE
Ошибка работы conversation и telegram

### ISSUE THREAD

**Issue by peleccom** [AlexxIT/YandexStation#255]
Текстовый ввод работает. Но ответ колонка озвучивает голосом. 
![image](https://user-images.githubusercontent.com/899242/159643601-c33f941e-135b-441c-9aeb-cd14bef80f3d.png)

Такое же поведение в telegram боте

В логе появляются сообщения 

```
DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Яндекс Лайт c8a7 => local | {'command': 'sendText', 'text': 'Привет'}


DEBUG (MainThread) [custom_components.yandex_station.media_player] Яндекс Лайт c8a7 | Empty response on request: 6f625bc7877c05fa502540bfbc3bc91d
```

https://github.com/AlexxIT/YandexStation/blob/e45df0d548ec6966d5bd786445a70b3d94064be0/custom_components/yandex_station/media_player.py#L832

Тут вызов  `await self.glagol.send ` возвращает None, и card будет None

Версия компонента 3.9.1
Версия HA 2022.2.9 (Аналогично на 2022.3.5 Но там еще из медиаплеера tts убрали)}

Колонка в локальном режиме, по крайней мере обложки отображаются. Также не работает shopping_list

**Comment by Zuz666** [comment]
Это проблема с локальным протоколом какая-то. Т.е. сама колонка не отвечает корректно (у меня есть все модели, на всех проблема, все перезагружал на всякий случай, с VPN  и без VPN проверялась работа).
В логах есть ещё таймаут помимо строк выше (между этими строками):
```
2022-04-01 09:15:43 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139824725492448] Error handling message: Error handling media_player.yandex_station

```

**Comment by Zuz666** [comment]
@peleccom а для Telegram как настроено? У меня тригер на yandex_station_response не срабатывает.

**Comment by peleccom** [comment]
@Zuz666 В телеграм по инструкции https://github.com/AlexxIT/YandexStation#%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%B0%D0%BB%D0%B8%D1%81%D0%B0-%D0%B2-telegram

На сообщения реагирует и отвечает, но да триггер yandex_station_response не срабатывает и ответ не посылает текстом

**Comment by peleccom** [comment]
@Zuz666 сейчас просто случайно решил проверить. Все заработало, наверно починили в прошивке

**Comment by Zuz666** [comment]
@peleccom, да, всё работает, тикет этот можно закрывать.

**Comment by peleccom** [comment]
Исправилось со стороны Яндекса

**Comment by peleccom** [comment]
Исправилось со стороны Яндекса
