### ISSUE TITLE
Возможность установки Proxy url

### ISSUE THREAD

**Issue by alexkutsan** [AlexxIT/YandexStation#257]
Было бы круто иметь возможность указать proxy для этого расширения.
Яндекс не работает в Украине, но не хочется ставить vpn на весь трафик, а иметь возможность установить прокси только для расширения Яндекса было бы очень удобно

**Comment by AlexxIT** [comment]
Такой функционал есть, но некоторые пользователи говорят, что не помогает
https://github.com/AlexxIT/YandexStation/releases/tag/v3.1.0

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.14.0
