### ISSUE TITLE
Text to speech has moved to the media browser.

### ISSUE THREAD

**Issue by dangerdanik** [AlexxIT/YandexStation#260]
Добрый день. 
Зачем убрали возможность отправлять Алисе текст из карточки? 
Сейчас там уведомление - Text to speech has moved to the media browser.
Было очень удобно! Верните, пожалуйста.

**Comment by AlexxIT** [comment]
Вы это авторам Home Assistant пишите, а не сюда :)

**Comment by dangerdanik** [comment]
Извините) Я решил что Вы как разработчик это сами правите. Хорошо. Но наверное тогда бесполезно. Спасибо за Ваши старания!

**Comment by dangerdanik** [comment]
Понятно. Ну если у Вас будет время и желание, посмотрите, может можно туда
тоже прикрутить отправку сообщений на яндекс станцию.

С уважением, Бутин Данил.


пт, 1 апр. 2022 г. в 13:38, Alex X ***@***.***>:

**Comment by jehy** [comment]
Было бы здорово посмотреть, без поля ввода не получается из виджета давать команды станции, это очень грустно :(

**Comment by jehy** [comment]
Судя по большому треду на реддите, что я читал, там считают, что это не бага а фича, и мнение пользователей не очень интересует.

**Comment by TheUserDead** [comment]
Всё для людей!
Извернулся так, поставил из HACS [text-input-row ](https://github.com/gadgetchnnel/lovelace-text-input-row)
Сделал скрипт принимающий текст с этого поля ввода в качестве параметра.
`alias: AliceTransmittertext
sequence:
  - service: media_player.play_media
    entity_id: media_player.ИМЯ_ВАШЕЙ_КОЛОНКИ
    data:
      media_content_id: '{{ states(''input_text.text1'') }}'
      media_content_type: text 
mode: single

`
command вместо text делает команду соответвенно (ваш КЭП)
а сделать это можно открыв scripts.yaml и найдя скрипт, изменив его id с цифр на что-то вменяемое, так для кошерности...

создаем пару вспомогательных элементов после вкладки скриптов
`input_text.text1`

Добавляем карточку в дашборд в режиме YAML
`type: entities
entities:
  - entity: input_text.text1
    type: custom:text-input-row
  - type: call-service
    name: ' '
    icon: mdi:voice
    action_name: отправить
    service: script.AliceTransmittertext

`
И помним о том что в последней строке имя скрипта вызывается по id а не по friendly_name поэтому его надо поправить или знать этот id (например с инструментов разработчика в службах) и вбить их.
Реализация команды и текста сделал халтурно, ибо тонкостей ХА не знаю. Это двумя скриптами с разницей полей и command\text в скриптах двумя отдельными карточками. 
Функцию выполняет. Если есть варик по причесаннее, делитесь)

**Comment by AndrejShabanov** [comment]
Похоже необходимо добавить колонки в раздел 
https://www.home-assistant.io/integrations/media_source/

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation#медиа-браузер

**Comment by smmoroz** [comment]
У меня не работает вместе с [Yandex Media Browser](https://github.com/alryaz/hass-yandex-music-browser). 

Сделал как в [документации](https://github.com/AlexxIT/YandexStation#%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80). Без Yandex Media Browser - источники для TTS появились и работают. С Yandex Media Browser - есть только его источники, а источников для TTS нет.
