### ISSUE TITLE
Во время стриминга музыки на apple tv при переключении треков для apple tv выставляется громкость 0

### ISSUE THREAD

**Issue by cron13** [AlexxIT/YandexStation#262]
Привет, подскажите, в чем может быть проблема?
Пытаюсь стримить со станции Яндекс Станция мини 2 на apple tv 4k второго поколения
Первая песня играет хорошо, но при переключении трека(после завершения, из плеера или голосовой командой Алисе), громкость apple tv выставляется в значение 0
Записал небольшой скринкаст что бы было понятнее - https://www.youtube.com/watch?v=Vb7rOuts1Ec

**Comment by AlexxIT** [comment]
У меня нет свежей Apple TV для отладки. Но в последнюю мастер-версию добавил возможность отключить синхронизацию громкости при стриминге. Читать в readme. Должно помочь.
