### ISSUE TITLE
SSLCertVerificationError  

### ISSUE THREAD

**Issue by andrey-kovalev** [AlexxIT/YandexStation#263]
Привет! в Латвии недавно словил такую ошибку, похоже что провайдеры блочат. Может есть возможность скипать недействтельный SSL серт? 

![Снимок экрана 2022-04-17 в 17 43 50](https://user-images.githubusercontent.com/72339204/163719622-56bd1a3b-d7c9-4982-a739-7b8133933c9e.png)

**Comment by kideg20** [comment]
Я тоже из Латвии, такая-же ошибка. 
Похоже в Латвии заблочили домен yandex.ru

**Comment by AlexxIT** [comment]
Скорее всего они подменяют сайт. Нужно пользоваться proxy

**Comment by andrey-kovalev** [comment]
Пока по супер тупому решил, цепанулся по OpenVPN к DE серваку с роутера, и зарестартил автоматизацию, видимо эта ошибка приходит только на какой то хендшейк, наверное токен получают какой то. Ну поглядим сколько времени будет жить. Пока день стабильно работает... 
В любом случае пасиб!
