### ISSUE TITLE
у яндекс розетки пропали сенсоры

### ISSUE THREAD

**Issue by mobilegoha** [AlexxIT/YandexStation#264]
у яндек розетки пропали сенсоры мощности можно только управлять реле.
раньше все работало по моему сломалось с версии 3.9

**Comment by bsod777** [comment]
Аналогично
Отвалилась завязанная автоматизация

**Comment by Zuz666** [comment]
Фикс тут: https://github.com/AlexxIT/YandexStation/pull/235/files#

**Comment by AlexxIT** [comment]
Принял фикс в мастер-версию
