### ISSUE TITLE
Не появляется колонка

### ISSUE THREAD

**Issue by Nesterovich2797** [AlexxIT/YandexStation#265]
Была добавлена колонка Яндекс мини. Потом обратил внимание, что она стала недоступна. Я переустановил интеграцию, авторизовался с помощью QR кода и устройство даже не появилось. Станцию перезапускал.

```
Logger: homeassistant.components.media_player
Source: custom_components/yandex_station/core/yandex_quasar.py:50
Integration: Медиаплеер (documentation, issues)
First occurred: 09:08:09 (1 occurrences)
Last logged: 09:08:09

Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 84, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 103, in load_speakers
    scenarios = await self.load_scenarios()
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 132, in load_scenarios
    return {
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 133, in <dictcomp>
    decode(d['name']): d
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 50, in decode
    return ''.join([MASK_EN[MASK_RU.index(s)] for s in uid[3:]])
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 50, in <listcomp>
    return ''.join([MASK_EN[MASK_RU.index(s)] for s in uid[3:]])
ValueError: substring not found
```

**Comment by gekenson** [comment]
Аналогично. Вчера купил вторую станцию "мини 2" с часами, в интеграции она не появилась. Переустановил интеграцию, теперь нет ни мини, ни старой. В логах то же самое.

**Comment by Alexxx113** [comment]
> 
упало что-то со сценариями со стороны яндекса   )

не создается сценарий и все падает

Лечим, пока так...
колонки появятся, но не будут говорить

https://iot.quasar.yandex.ru/m/user/scenarios 

custom_components/yandex_station/core/yandex_quasar.py

    async def load_speakers(self) -> list:
        speakers = self.speakers

        # Яндекс начали добавлять device_id и platform с полным списком
        # устройств
        # for speaker in speakers:
        #     await self.load_speaker_config(speaker)

        scenarios = await self.load_scenarios()
        for speaker in speakers:
            device_id = speaker['id']

            if device_id not in scenarios:
                #await self.add_scenario(device_id)
                scenarios = await self.load_scenarios()

            #speaker['scenario_id'] = scenarios[device_id]['id']

        return speakers

**Comment by Alexxx113** [comment]
починил у себя, заморочка не слабая когда не знаешь.....
тот пост что выше в решит проблему, но станции будут молчать!

пошел другим путем, создал ему те сценарии что он хотел

custom_components/yandex_station/core/yandex_quasar.py

меняем

`    async def add_scenario(self, device_id: str):
        """Добавляет сценарий-пустышку."""
        name = encode(device_id)
        payload = {
            'name': name,
            'icon': 'home',
            'triggers': [{
                'type': 'scenario.trigger.voice',
                'value': name[3:]
            }],
            'requested_speaker_capabilities': [],
            'devices': [{
                'id': device_id,
                'capabilities': [{
                    'type': 'devices.capabilities.quasar.server_action',
                    'state': {
                        'instance': 'phrase_action',
                        'value': 'пустышка'
                    }
                }]
            }]
        }
        r = await self.session.post(f"{URL_USER}/scenarios", json=payload)
        resp = await r.json()

        _LOGGER.error(payload)

        _LOGGER.error(r)

        _LOGGER.error(resp)

        assert resp['status'] == 'ok', resp
`


в логах появится

`{'name': 'ХА яияеисикынмнаынлклылокяыпаиеампквноа', 'icon': 'home', 'triggers': 
[{'type': 'scenario.trigger.voice', 'value': 'яияеисикынмнаынлклылокяыпаиеампквноа'}],
 'requested_speaker_capabilities': [],
 'devices': [{'id': '************************************',
 'capabilities': [{'type': 'devices.capabilities.quasar.server_action',
 'state': {'instance': 'phrase_action', 'value': 'пустышка'}}]}]}`


создаем сценарий 'ХА яияеисикынмнаынлклылокяыпаиеампквноа'
если
я скажу 'яияеисикынмнаынлклылокяыпаиеампквноа'

тогда 
станция 1
выполнит 'пустышка'
станция 2
выполнит 'пустышка'

у меня она хотела создать два сценария.
второй аналогично

работает )

**Comment by Alexxx113** [comment]
> Так же не подключается, но ошибка другая:
> 
> ```
> Logger: homeassistant.config_entries
> Source: custom_components/yandex_station/core/yandex_session.py:445
> Integration: Yandex.Station ([documentation](https://github.com/AlexxIT/YandexStation), [issues](https://github.com/AlexxIT/YandexStation/issues))
> First occurred: 18:52:32 (1 occurrences)
> Last logged: 18:52:32
> 
> Error setting up entry Den-media for yandex_station
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
>     hosts = await asyncio.shield(host_resolved)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 880, in _resolve_host
>     addrs = await self._resolver.resolve(host, port, family=self._family)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
>     infos = await self._loop.getaddrinfo(
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
>     return await self.run_in_executor(
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -3] Try again
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/yandex_station/__init__.py", line 103, in async_setup_entry
>     await quasar.init()
>   File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 75, in init
>     r = await self.session.get(f"{URL_USER}/devices")
>   File "/config/custom_components/yandex_station/core/yandex_session.py", line 420, in get
>     return await self._request('get', url, **kwargs)
>   File "/config/custom_components/yandex_station/core/yandex_session.py", line 445, in _request
>     r = await getattr(self.session, method)(url, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
>     conn = await self._connector.connect(
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
>     proto = await self._create_connection(req, traces, timeout)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
>     _, proto = await self._create_direct_connection(req, traces, timeout)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
>     raise ClientConnectorError(req.connection_key, exc) from exc
> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host iot.quasar.yandex.ru:443 ssl:default [Try again]
> ```

к этой проблеме не относится

**Comment by Nesterovich2797** [comment]
> 

Спасибо. Станция появилась.

**Comment by AlexxIT** [comment]
Дубликат #236

**Comment by udavst** [comment]
Есть вариант сделать нормально? 
- Первый вариант работает - где колонка не будет говорить, 
- Второй - изменил файл - ничего не поменялось, колонок нет. Или я не понял как делать.
Полгода прошло, а всё костыли (
