### ISSUE TITLE
Ошибка при общении со станцией через телеграм бота

### ISSUE THREAD

**Issue by morlz** [AlexxIT/YandexStation#266]
Настройки не менял, раньше работало

[media_content_type: xxx  # тип не важен, но должен быть!](https://github.com/AlexxIT/YandexStation#%D0%BF%D1%80%D0%BE%D0%B8%D0%B3%D1%80%D1%8B%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0-%D0%BF%D0%BE-%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B0%D0%BC)

```
Logger: custom_components.yandex_station.media_player
Source: C:\hass\config\custom_components\yandex_station\media_player.py:861
Integration: Yandex.Station ([documentation](https://github.com/AlexxIT/YandexStation), [issues](https://github.com/AlexxIT/YandexStation/issues))
First occurred: 09:37:52 (1 occurrences)
Last logged: 09:37:52

Unsupported cloud media: question:7662929322
```

integration: v3.9.1

**Comment by AlexxIT** [comment]
Станция в облачном режиме. question работает только в локальном режиме
