### ISSUE TITLE
Возможно перехватить что говорит станция

### ISSUE THREAD

**Issue by Alexxx113** [AlexxIT/YandexStation#268]
есть желание, получить от станции ответ какие включены будильники
это возможно?

если возможно, пожалуйста  пример скрипта

**Comment by AlexxIT** [comment]
Возможно. Собственно общение через Телеграм это и реализует. Примеры скриптов лучше спрашивать в тематических чатах Телеграм

**Comment by Alexxx113** [comment]
Спасибо за подсказку!
Телеграм не нужен )
Единственное написать обработку ответов
Сам спросил сам отвечу )

alias: вопрос
description: ''
trigger:
  - platform: state
    entity_id:
      - update.appdaemon_update
condition: []
action:
  - service: media_player.play_media
    data:
      media_content_type: question:1
      media_content_id: Какие будильники?
    target:
      entity_id: media_player."ваша станция"
mode: single

Ответ

alias: ждем ответ # событие yandex_station_response
description: ''
trigger:
  - platform: event
    event_type: yandex_station_response
condition: []
action:
  - service: media_player.play_media
    data:
      media_content_type: text
      media_content_id: '''{{ trigger.event.data.text }}'''
    target:
      entity_id: media_player."ваша станция". # просто проговорит ответ, как его разобрать другой вопрос )
mode: single
