### ISSUE TITLE
CAPTCHA required

### ISSUE THREAD

**Issue by remarkua** [AlexxIT/YandexStation#27]
> Уровень: ERROR
> Logger: custom_components.yandex_station.yandex_quasar
> Source: custom_components/yandex_station/yandex_quasar.py:124
> Integration: yandex_station (documentation)
> First occurred: 16:35:31 (1 occurrences)
> Last logged: 16:35:31
> 
> Init
> Traceback (most recent call last):
>   File "/config/custom_components/yandex_station/yandex_quasar.py", line 48, in init
>     self.main_token = await self.get_main_token(username, password)
>   File "/config/custom_components/yandex_station/yandex_quasar.py", line 124, in get_main_token
>     assert 'access_token' in resp, resp
> AssertionError: {'error': '403', 'error_description': 'CAPTCHA required', 'x_captcha_key': '00AkMIvlxCsrus1DatF2sVVkJLc5C4Iw', 'x_captcha_url': 'https://ext.captcha.yandex.net/image?key=00AkMIvlxCsrus1DatF2sVVkJLc5C4Iw'}

**Comment by AlexxIT** [comment]
Ага. Иногда бывает капча. Ещё не сделал простой способ её ввести.
Некоторым помогает смена IP адреса.
Нужно успешно провести хотябы один логин.

**Comment by remarkua** [comment]
У меня, я думаю сыграл злую шутку тунель IPv6 в IPv4. По IPv6 я нахожусь в UK. Это возможно и насторожило и вызвало капчу.
Отключил тунель, нормально прошла авторизация, включил тунель обратно. 
Работает.

**Comment by profx5015** [comment]
Столкнулся с подобной проблемой. Решения, как понимаю, нет до сих пор? ip сменить не имею возможности, тк нет резервного канала, а провайдер выдает статический адрес. Вариантов ни каких больше?

**Comment by dmitry-korolev** [comment]
Опытным путем обнаружил, что может помочь смена пароля.

**Comment by rkakrik** [comment]
Та же проблема, ip менял несколько раз. Пароль менять проблематично - слишком много сервисов, где придется заново входить(

**Comment by AlexQuaken** [comment]
Подтверждаю проблему, у меня IP динамический, одолела эта капча не могу с ней залогинится тех поддержка яндекса отмораживается, чтобы ее мне принудительно отключить.

**Comment by AlexxIT** [comment]
https://t.me/AlexxIT_SmartHome/394

**Comment by AlexxIT** [comment]
Поправлено в версии 3
