### ISSUE TITLE
Виснет супервизор из-за стриминга

### ISSUE THREAD

**Issue by 007Nexus** [AlexxIT/YandexStation#270]
Raspberry 4B 2Gb, Raspbian GNU/Linux 10 (buster), Kernel: Linux 5.10.35-v7l+
Home assistant 2022.3.2, supervisor 2022.05.1

Через некоторое время (~1-3 часа) стриминга на сторонний mpd(на raspberry с home assistant или androidtv, не важно) прекращается воспроизведение на стороннем mpd(всегда во время паузы между песнями и никогда на середине песни) и виснет супервизор с сопутствующей невозможностью перезагрузить home assistant штатными средствами. 
`ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /homeassistant/restart request`
В лог каждые 10 секунд пишется:
`WARNING (MainThread) [homeassistant.components.media_player] Updating mpd media_player took longer than the scheduled update interval 0:00:10`
После перезагрузки по ssh  или по питанию можно опять включить стриминг, и все повторится.

Изменение свободной памяти от начала стриминга до зависания супервизора:
![2022-05-11_22-57-00](https://user-images.githubusercontent.com/82052230/167935328-b5a4bc59-04b6-4749-9ee1-ebff0581972f.png)
Ошибки:
![2022-05-11_21-53-43](https://user-images.githubusercontent.com/82052230/167931213-c9d195ba-4878-4778-84c9-e00ecf7b174b.png)
![2022-05-11_21-53-20](https://user-images.githubusercontent.com/82052230/167931264-0d60c110-f659-4070-b21a-a7231f014073.png)
![2022-05-11_21-52-01](https://user-images.githubusercontent.com/82052230/167931282-b07ac825-a8af-4de0-9ff6-3e593615cf75.png)
![2022-05-11_21-50-50](https://user-images.githubusercontent.com/82052230/167931300-299d9f6b-ef75-47c5-a692-1145126b137f.png)
![2022-05-11_21-48-33](https://user-images.githubusercontent.com/82052230/167931321-6f6953b7-eff0-4c72-91a5-4d4abba46dd9.png)

**Comment by AlexxIT** [comment]
Утечки памяти вероятно поправлены в последней версии
