### ISSUE TITLE
Сannot import name 'DeviceInfo' from 'homeassistant.helpers.entity' 3.10

### ISSUE THREAD

**Issue by 2053950** [AlexxIT/YandexStation#273]
После обновления на 3.10 YandexStation после добавления интеграции (по QR коду) выдает такую ошибку: Unable to prepare setup for platform yandex_station.media_player: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/[entity.py](http://entity.py/)))

**Comment by AlexxIT** [comment]
Возможно используется очень старая версия ХА
