### ISSUE TITLE
Не корректно работает управление кондиционером Daichi подключенным по wi fi

### ISSUE THREAD

**Issue by Druidblack** [AlexxIT/YandexStation#279]
Облачный кондиционер Daichi.
Кондиционер добавлен в HA. Нужно откорректировать логику управления.
Кондиционер из системы умный дом яндекс включается по команде (или нажатию) на кнопку выключения (получается логика как у обычного выключателя вкл/выкл.
Отсюда несколько проблем. 
1. После добавления в HA кондиционера как термостата, при нажатии на необходимые режимы (холод, обогрев) кондиционер не включается, а только переключает режимы работы. Его предварительно нужно включить кнопкой выключение (но логика кнопки его пытается выключить)
2.  Если кондиционер включить в интерфейсе яндекса или голосовой командой  то информация в HA не обновляется (например остается статус "Выключено". Нет обратной связи.
3. При переключении режимов работы кондиционера происходит двойное нажатие команды (идет звуковой сигнал два раза) и при этом в карточке термостата информация о включенном режиме не обновляется (в интерфейсе умного дома яндекс информация обновляется сразу). Если на тот же режим нажать еще раз, то информация становится корректной.
Выключение и корректировка температуры происходит корректно.
P.S.Так как для кондиционеров Daichi нет интеграций для проброски его в HA, вся надежда на решение этих проблем.

**Comment by AlexxIT** [comment]
Боюсь удалённо будет сложно починить работу. Даже не знаю, что тут можно придумать для отладки.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.0
