### ISSUE TITLE
Доступы в аккаунте Яндекса

### ISSUE THREAD

**Issue by kuznetsss** [AlexxIT/YandexStation#283]
Привет! Большое спасибо за компонент, я давно хотел связать умную колонку с Home Assistant.

Расскажите, пожалуйста, (может быть даже было бы полезно добавить это в README) какие права получает компонент при авторизации в аккаунте Яндекса?

Кажется, что логин происходит как в браузере, то есть потенциально есть полный доступ ко всему аккаунту. Можно ли как-то это ограничить или выписать только необходимые токены?

**Comment by kuznetsss** [comment]
Я нашел [запись](https://t.me/AlexxIT_SmartHome/238) на телеграмм канале, где говорится, что компонент хранит два главных токена (видимо, с полным доступом к аккаунту), чтобы обновлять токены доступа до станции. Это всё еще так или что-то изменилось?

**Comment by AlexxIT** [comment]
Верно. У компонента максимальный доступ к аккаунту пользователя. Это нужно для выполнения команд через облако Яндекса. А также для получения музыкального токена и локальных токенов колонок.

Старая версия интеграции могла пользоваться только музыкальным токеном. При этом были доступны только локальные API колонок.

Локальные API это лишь небольшая часть от всех функции компонента. Поддерживать исключительно локальный режим без облачного подключения стало очень сложно. И в последних версиях пришлось отказаться от этого подхода.

Если бы была возможность максимально ограничить права - я бы ей воспользовался.

**Comment by kuznetsss** [comment]
Подскажите, пожалуйста, была ли попытка использовать OAuth токен для доступа вместо полного доступа?
Вроде бы на странице https://oauth.yandex.ru/client/new можно выбрать нужные права или там чего-то не хватает?

**Comment by AlexxIT** [comment]
Если найдёте такой токен, который позволяет использовать абсолютно все API компонента, сообщите, я переделаю компонент.

**Comment by kuznetsss** [comment]
Мне сложно сказать, что именно нужно компоненту. Но, если на странице https://oauth.yandex.ru/client/new чего-то не хватает, у меня есть возможность передать ваши пожелания разработчикам Яндекса
