### ISSUE TITLE
feature request: Добавить поддержку мультиварок из Яндекс

### ISSUE THREAD

**Issue by vring0** [AlexxIT/YandexStation#284]
@AlexxIT  Было бы неплохо реализовать поддержку мультиварок из умного дома Яндекс в Home Assistant. Например имеется такой вариант, который добавляется в Яндекс - https://www.polar.ru/catalog/multivarki/multivarka-polaris-pmc-0526-iq-home/

Я понимаю, что нет поддерживаемой сущности, можно собрать устройство из нескольких. Самое основное: выбор программы, термостат, управление питанием и подогревом. Возможно я смогу поучаствовать в PR, если подскажите с чего лучше начать.

**Comment by AlexxIT** [comment]
Чайники то тут причём? Они давно поддерживаются

**Comment by dmunsh** [comment]
Подскажите, через что поддерживается чайник Polaris PWK 1775CGLD. Год не могу найти.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation#%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%83%D0%BC%D0%BD%D1%8B%D0%BC-%D0%B4%D0%BE%D0%BC%D0%BE%D0%BC-%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81%D0%B0

**Comment by dmunsh** [comment]
Доброе утро. С чайником разобрался (БОЛЬШОЕ СПАСИБО), а как быть с бризером ballu open air asp 200, который есть в УД Яндекса (интеграция HOMMYN), а через Ваш компонент не пробрасывается в HA. Есть в планах такая доработка?

**Comment by whakru** [comment]
Присоединюсь к поддержке мультиварок polaris.

**Comment by gromilllla** [comment]
> Доброе утро. С чайником разобрался (БОЛЬШОЕ СПАСИБО), а как быть с бризером ballu open air asp 200, который есть в УД Яндекса (интеграция HOMMYN), а через Ваш компонент не пробрасывается в HA. Есть в планах такая доработка?

Не подскажете, как разобрались с чайником? Чайник проброшен через IQHome в УДЯ, но HA его не видит(

**Comment by sskokorin** [comment]
> > Доброе утро. С чайником разобрался (БОЛЬШОЕ СПАСИБО), а как быть с бризером ballu open air asp 200, который есть в УД Яндекса (интеграция HOMMYN), а через Ваш компонент не пробрасывается в HA. Есть в планах такая доработка?
> 
> Не подскажете, как разобрались с чайником? Чайник проброшен через IQHome в УДЯ, но HA его не видит(

Тоже интересует как увидеть устройства в HA, которое добавлено в УДЯ через IQ Home. У Вас получилось?

**Comment by gromilllla** [comment]
> Тоже интересует как увидеть устройства в HA, которое добавлено в УДЯ через IQ Home. У Вас получилось?

Да, получилось. Внимательно в пятый раз прочитав инструкцию, дописал в configuration.yaml следующие строки:

yandex_station:
  include:
    - Чайник  # имя устройства УДЯ

После перезагрузки HA чайник появился

**Comment by Gusev-Alex** [comment]
Присоединяюсь  к вопросу

**Comment by AlexxIT** [comment]
В новой версии можно управлять любым устройством
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.0

**Comment by ChapayTv** [comment]
> @AlexxIT Было бы неплохо реализовать поддержку мультиварок из умного дома Яндекс в Home Assistant. Например имеется такой вариант, который добавляется в Яндекс - https://www.polar.ru/catalog/multivarki/multivarka-polaris-pmc-0526-iq-home/
> 
> Я понимаю, что нет поддерживаемой сущности, можно собрать устройство из нескольких. Самое основное: выбор программы, термостат, управление питанием и подогревом. Возможно я смогу поучаствовать в PR, если подскажите с чего лучше начать.

Поделитесь пожалуйста конфиком для мультиварки, если не жалко?

**Comment by vring0** [comment]
> > @AlexxIT Было бы неплохо реализовать поддержку мультиварок из умного дома Яндекс в Home Assistant. Например имеется такой вариант, который добавляется в Яндекс - https://www.polar.ru/catalog/multivarki/multivarka-polaris-pmc-0526-iq-home/
> > Я понимаю, что нет поддерживаемой сущности, можно собрать устройство из нескольких. Самое основное: выбор программы, термостат, управление питанием и подогревом. Возможно я смогу поучаствовать в PR, если подскажите с чего лучше начать.
> 
> Поделитесь пожалуйста конфиком для мультиварки, если не жалко?

Я в итоге отказался от покупки этой модели, купил от Xiaomi индукционную, но пока все руки не доходят с интеграцией в Алису, там тоже не все так просто.
