### ISSUE TITLE
Возможности локальных колонок

### ISSUE THREAD

**Issue by shmateyev** [AlexxIT/YandexStation#286]
Добрый день. Подскажите пожалуйста, что значит формулировка (из документации) - Возможности локальных колонок?
Мы хотели бы, чтобы Алиса по триггеру датчика движения, воспроизводила определенную фразу - без интернета.  
Это возможно? Это ли является локальным режимом или что-то иное?

**Comment by glebsterx** [comment]
Без интернета колонки не могут говорить ничего, кроме зашитых в них фраз об ошибке и приветственной речи при настройке. TTS так не работает -- только через интернет.
**Но это пока** -- есть предположение, что в данный момент все еще ведется работа над локальным режимом в ЯС2, чтобы было как в этом предложении -- без интернета по датчику произносилась фраза.

**Comment by AlexxIT** [comment]
Без интернета колонки Яндекса не работают вообще
