### ISSUE TITLE
Не включить свой плейлист

### ISSUE THREAD

**Issue by allmoney** [AlexxIT/YandexStation#287]
Вот так работает (album):
![image](https://user-images.githubusercontent.com/939594/175248544-2b0794b0-e528-4a72-94cc-78d29bd0ec79.png)

А вот так нет (свой playlist):
![image](https://user-images.githubusercontent.com/939594/175248295-34e06d96-4977-4fce-8477-031bd1258661.png)

Баг? Или что-то делаю не так? Help!

p.s. ранее писали что заработало, но так и не работает :) https://github.com/AlexxIT/YandexStation/issues/15

**Comment by AlexxIT** [comment]
В плейлисте пользователя должен участвовать ID пользователя. Нужно пользоваться этой функцией, она умеет находить и подставлять ID пользователя для плейлистов:

https://github.com/AlexxIT/YandexStation#%D0%BF%D1%80%D0%BE%D0%B8%D0%B3%D1%80%D1%8B%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0-%D0%BF%D0%BE-%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B0%D0%BC
