### ISSUE TITLE
Бесшумно Включи мою любимую музыку вперемешку

### ISSUE THREAD

**Issue by allmoney** [AlexxIT/YandexStation#288]
Есть возможность бесшумно "Включи мою любимую музыку вперемешку"? Чтобы не было перед запуском музыки алисиного "Включаю ваши любимые песни вперемешку"...

**Comment by AlexxIT** [comment]
Если только колхозить с уменьшением громкости колонки в ноль на пару секунд при выполнении команды. Других способов - неизвестно
