### ISSUE TITLE
После обновления на 2022.6.7 перестал видеться Модуль 2

### ISSUE THREAD

**Issue by danilkis** [AlexxIT/YandexStation#291]
Недавно обновился на 2022.6.7 и Модуль 2 просто постоянно показывается как недоступный. Пробовал скидывать до заводских и перенастраивать интеграцию. Но не помогло
Единственное сообщение в логах от компонента
![image](https://user-images.githubusercontent.com/26576621/176971622-9d3759f0-3db2-4551-a9d5-d963f82de6e5.png)

**Comment by funtik039** [comment]
У меня похожая проблема с яндекс.станция мини.
На днях наводил порядок в сценариях УД Яндекса и случайно удалил служебный сценарий. 
Перезагрузка не помогла, переустановка интеграции тоже. 
![Screenshot_2022-07-14-08-24-49-141-edit_io homeassistant companion android](https://user-images.githubusercontent.com/64101494/178915976-16616e38-b661-44d6-85cf-757e36046727.jpg)
Теперь HA вообще не видит станцию.

**Comment by funtik039** [comment]
Свою проблему решил. Нашел в сценариях УД Яндекс сценарий, который использовал фразу активации. Удалил сценарий, перезагрузил интеграцию и всё заработало.

**Comment by danilkis** [comment]
Мне помогла установка предыдущей версии интеграции

**Comment by AlexxIT** [comment]
В огрызок скриншота с ошибкой не попало точное место ошибки
