### ISSUE TITLE
Дочерние устройства Яндекс станция 2

### ISSUE THREAD

**Issue by re-id** [AlexxIT/YandexStation#292]
Добрый день. Планируется ли реализация проброса дочерних устройств с zigbee шлюза ЯСтанции 2?
Нужна ли помощь в тестировании?

**Comment by AlexxIT** [comment]
Совершенно нет времени изучать Станцию 2. Да и вероятность, что в ней в принципе существуют локальные API - минимальна.

Облачное управление устройствами из умного дома Яндекса возможно. И для некоторых типов устройств давно реализовано. По свободе буду развивать это направление. Но не в ближайшие месяцы.

**Comment by freefelt** [comment]
Привет! Есть какие-то новости?

**Comment by wadealer** [comment]
Здравствуйте. Тоже очень интересует работа с зигби от яндекс. У меня станция макс зигби, и управление зигби устройствами, подключенными к станции - это, пожалуй, самое лучшее, что могло бы быть в хом асистант

**Comment by AlexxIT** [comment]
Устройства умного дома Яндекса поддерживаются через облако.
Других технических возможностей управлять дочерними устройствами нет.
