### ISSUE TITLE
Как выполнить авторизацию и работать со станцией не из Home Assistant?

### ISSUE THREAD

**Issue by MrSmitix** [AlexxIT/YandexStation#294]
Цель в следующем, я не использую Home Assistant, но хочу что б при определенных действиях на домашнем сервере колонка о них сообщала. Вытащил файлы из core и начал колдовать. Но столкнулся с тем что всегда возвращаются пустые устройства.

session: YandexSession = YandexSession(session=ClientSession())
login_response: LoginResponse = await session.login_cookies(cookies=COOKIES)
quasar: YandexQuasar = YandexQuasar(session=session)
await quasar.init()

Но выбивает ошибку Login with token error: {'status': 'error', 'errors': ['oauth_token.invalid']}

В случае если явно добавляю 

await session.login_token(login_response.raw.get('x_token'))

Всё работает, но возвращается пустой список устройств. Хотя открыв в браузер /devices всё возвращается нормально.

Подскажите пожалуйста как можно выполнить авторизацию на станций и отправлять ей фразы что б она их проговорила. В открытых/закрытых issues ответа не нашел. Возможно не совсем понимаю формат работы.

**Comment by MrSmitix** [comment]
Ошибка была в том что в кушах была информаций о нескольких аккаунтах, и подтягивался не тот что нужен. Удалил все куки связанный с яндексом, авторизовался и получил их снова.

**Comment by MrSmitix** [comment]
Вопрос до сих пор актуальный и открытый. Понял что для отправки команды нужно использовать YandexGlagol, но вот только если передавать туда девайс quasar.devices[0] или quasar.get_device(quasar.devices[0]['id']) то в объекте device нет host и port. Добавлял их руками, найдя IP в админка роутера и используя порт 8080 но подключиться так же не получается. glagol.url = 'wss://192.168.1.135:8080'. Ошибка TypeError: 'NoneType' object is not callable (self.update_handler(None)). Продолжаю копать потихоньку когда есть время. Буду очень рад если кто нибудь присоединится)

**Comment by glebsterx** [comment]
А проще поставить ха в докер или венв и подключить колонки и горстку автоматизаций =)
но я так понимаю у самурая нет цели -- есть только путь))

**Comment by MrSmitix** [comment]
> А проще поставить ха в докер или венв и подключить колонки и горстку автоматизаций =)
> но я так понимаю у самурая нет цели -- есть только путь))

Ну типо того) А можно чуть подробнее? Куда копать? С HA ни разу не работал и ни разу его не поднимал. Куда там копать что б заставить колонку говорить? Как и куда из вне дергать HA что б он дергал колонку?

**Comment by glebsterx** [comment]
"Копать" чтобы заставить говорить -- установить туда компонент в гите которого собственно общаемся =)
А сам ХА можно попробовать в виде HassWP если windows, или в docker (есть на докерхабе) если нет =)
По поводу "дергать" -- в ХА есть автоматизации по триггерам, а компонент позволяет отправлять произвольные (но с ограничениями) фразы на колонку, более того в интерфейсе УДЯ есть такая функция, но автоматизация там замороченной (через навыки)

в общем способов масса, думаю Вам будет удобнее спросить подробности в тг-чате @station_yandex =)

**Comment by AlexxIT** [comment]
Согласен с @glebsterx , код не ориентирован на использование без ХА. Если у вас есть навыки python и web, то вполне сможете отдебажить код. Если не получается - рекомендую всё же разобраться и добиться своего. Решение таких задач поможет в профессиональном плане.
