### ISSUE TITLE
Стрим на колонки

### ISSUE THREAD

**Issue by akarpych** [AlexxIT/YandexStation#300]
После очередного обновления колонок Яндексом, перестал работать стрим на mpd, yamaha и скорее всего на все колонки

**Comment by sar2t** [comment]
Голову сломал разбираться что случилось. Перестал работать стрим на саундбар yamaha

**Comment by trytocry** [comment]
стрим по Chromecast и DLNA на AndroidTV перестал работать

**Comment by Kirorus** [comment]
> стрим по Chromecast и DLNA на AndroidTV перестал работать при откате на прошлые версии тоже не работает. Похоже проблема на стороне ПО яндекса

подтверждаю... впервые решил настроить, второй день ковыряния, а оно оказывается у всех не работает...

**Comment by donskoyv** [comment]
Тоже не работает стрим на Chromecast

**Comment by booroondookZ** [comment]
У меня тоже не работает

**Comment by yroboros** [comment]
Да, аналогично.
Ресивер Yamaha RX-V675 добавлен через DLNA Digital Media Renderer.
Text to Speech - воспроизводится.
При выборе ресивера в качестве источника, в виджете станции, на экране ресивера "[No comtent]", но громкость успешно регулируется.

**Comment by cpsskipper** [comment]
Стриминг на Kodi не работает!
