### ISSUE TITLE
Случайно удалил одну ентети

### ISSUE THREAD

**Issue by Serhioromano** [AlexxIT/YandexStation#304]
Я пренастраивал колонку, и в ХА мне сказали что нужно заново сделать подключение. Ну я хотел удалить сатрое подключение, нажал удалить но у меня была открыто не интеграция а entety. Ну я ее удалил их было 2 а устройств одно. Потом я удалил колонку, заново все подключил а Entety теперь одна, и все время одна. 

Как мне вернуть удаленную Entety?

**Comment by AlexxIT** [comment]
Мало понял, что произошло
