### ISSUE TITLE
Бризер Tion 4S через УД Rubetek hvac_modes: null

### ISSUE THREAD

**Issue by kirill-sh** [AlexxIT/YandexStation#307]
Бризер Tion 4S через УД Rubetek добавлен в УДЯ и проброшен в HA.
hvac_modes: null - соответственно невозможно включить/выключить в HA.

![tion-quasar](https://user-images.githubusercontent.com/25672311/185746092-d1fbbecd-416c-4270-b347-2d248103a5b6.png)
![tion-attr](https://user-images.githubusercontent.com/25672311/185746089-06d780f3-5e5d-4837-b984-00dba921dad5.png)
![tion-ha](https://user-images.githubusercontent.com/25672311/185746091-07198e8c-8342-43b9-9f28-f9bc2f7cc03d.png)

json из УДЯ:
`
{
    "status": "ok",
    "request_id": "c08d8d55-2649-4c74-817c-fc11b244793e",
    "updates_url": "wss://push.yandex.ru/v2/subscribe/websocket?client=searchapp\u0026filter=%7B%22rules%22%3A%5B%7B%22if%22%3A%7B%22device_id%22%3A%7B%22%24eq%22%3A%5B%22def0ba97-727f-48f4-a7ea-8ed6f9ee8c50%22%5D%7D%7D%2C%22do%22%3A%22send_bright%22%7D%2C%7B%22do%22%3A%22skip%22%7D%5D%2C%22vars%22%3A%7B%7D%7D\u0026service=alice-iot\u0026session=c08d8d55-2649-4c74-817c-fc11b244793e\u0026sign=647cd6a6afb5414dd55cb2ef83109af2\u0026ts=1659563040\u0026user=15440116",
    "id": "def0ba97-727f-48f4-a7ea-8ed6f9ee8c50",
    "name": "Вентиляция",
    "names": [
        "Вентиляция"
    ],
    "type": "devices.types.thermostat",
    "icon_url": "https://avatars.mds.yandex.net/get-iot/icons-devices-devices.types.thermostat.svg/orig",
    "state": "online",
    "groups": [],
    "room": "Спальня",
    "capabilities": [
        {
            "retrievable": true,
            "type": "devices.capabilities.on_off",
            "state": {
                "instance": "on",
                "value": true
            },
            "parameters": {
                "split": false
            }
        },
        {
            "retrievable": true,
            "type": "devices.capabilities.range",
            "state": {
                "instance": "temperature",
                "value": 25
            },
            "parameters": {
                "instance": "temperature",
                "name": "температура",
                "unit": "unit.temperature.celsius",
                "random_access": true,
                "looped": false,
                "range": {
                    "min": 0,
                    "max": 25,
                    "precision": 1
                }
            }
        },
        {
            "retrievable": true,
            "type": "devices.capabilities.mode",
            "state": {
                "instance": "fan_speed",
                "value": "low"
            },
            "parameters": {
                "instance": "fan_speed",
                "name": "скорость вентиляции",
                "modes": [
                    {
                        "value": "low",
                        "name": "Низкая"
                    },
                    {
                        "value": "medium",
                        "name": "Средняя"
                    },
                    {
                        "value": "high",
                        "name": "Высокая"
                    }
                ]
            }
        }
    ],
    "properties": [],
    "skill_id": "c43a5814-508b-44aa-afde-10442c10e7ba",
    "external_id": "7095759c-c7e7-11ec-8c45-0242ac130007:0",
    "favorite": false
}`

**Comment by DrSchmurge** [comment]
Сложная схема, я пользуюсь напрямую через интеграцию https://github.com/TionAPI/HA-tion по Bluetooth

**Comment by dentra** [comment]
Или стик на esp32 прямо в бризер (будет как рубетек), esphome и [кастом под тион](https://github.com/dentra/esphome-tion), залетит нативно в HA.
