### ISSUE TITLE
Не находит Irbis

### ISSUE THREAD

**Issue by kisaev83** [AlexxIT/YandexStation#31]
Привет. Подскажи, никак не могу подключить Irbis к HA. В паспорте яндекса устройство есть. И устройство заново отвязывал-привязывал и пароли менял. Ни в какую не хочет.
![2020-06-10_18-48-51](https://user-images.githubusercontent.com/65431434/84289472-2e8b4f00-ab4b-11ea-8ef1-95567ddb3a91.png)
![2020-06-10_18-50-27](https://user-images.githubusercontent.com/65431434/84289541-4662d300-ab4b-11ea-95b5-45df314dcfc2.png)

**Comment by kisaev83** [comment]
Есть предположения что может быть?

**Comment by AlexxIT** [comment]
Мне нужно переписать логирование, чтоб понять, что там произошло. Пока нет на это времени.
Пока попробуйте удалить yandex station json в папке конфигов. И перезапустить ХА

**Comment by kisaev83** [comment]
Спасибо. Помогло удаление json. Irbis завелся
