### ISSUE TITLE
Создание скрипта в HA

### ISSUE THREAD

**Issue by kirush0280** [AlexxIT/YandexStation#315]
При создании скрипта и выборе TTS не появляется поле "Данные службы" для заполнения.
![image](https://user-images.githubusercontent.com/13412942/191067013-12dc488b-2030-48c1-b76c-aa3d1491c905.png)

Если заполнить через configuration.yaml, то оно есть:
![image](https://user-images.githubusercontent.com/13412942/191067411-427740dc-c0c8-413f-9e1b-734ad9e4f807.png)

выход пока заполнять через "три точки" -> "Текстовый редактор".
При вызове "Yandex.Station: send_command" поле "Данные службы" появляется нормально.

**Comment by Opontios** [comment]
Я во всех скриптах пользуюсь службой "media_player.play_media" для TTS, с ней нет проблем.

**Comment by kirush0280** [comment]
Попробовал воспользоваться, в UI не дает заполнять Данные службы
Home Assistant 2022.9.6
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest

![image](https://user-images.githubusercontent.com/13412942/192064958-b5a70646-3116-4298-9f34-27ddd4006153.png)

**Comment by Opontios** [comment]
@kirush0280 
Это потому, что Вы не ту службу вызываете. Есть "media_player.media_play", это служба для того чтобы послать команду "Play" медиа плееру, а есть "media_player.play_media", это то что нужно для TTS.

**Comment by AlexxIT** [comment]
Бестолковый сервис, не планирую ему создавать описание. Если есть желание - можете сделать PR.
