### ISSUE TITLE
Не добавляются устройства если в умный дом добавлены люди

### ISSUE THREAD

**Issue by urtaevS** [AlexxIT/YandexStation#317]
Яндекс добавил возможность(наконец!) добавлять людей в дом для совместного управления. Но теперь интеграция в HA не видит устройств: не из добавленного дома, не из основного.
Получится ли сделать чтобы добавлялись колонки когда дом расшарен?

**Comment by eratnik** [comment]
> Яндекс добавил возможность(наконец!) добавлять людей в дом для совместного управления. Но теперь интеграция в HA не видит устройств: не из добавленного дома, не из основного.
> Получится ли сделать чтобы добавлялись колонки когда дом расшарен?

У меня три колонки на двух разных аккаунтах. Дом не расшаривал, но детская колонка, которая на отдельном аккаунте, больше как устройство недоступен - остался только эквалайзер, который, к слову, работает. Попробовал удалить аккаунт и добавить заново - добавляется только эквалайзер. Переустановил интеграцию - не помогло. 
Причем две остальные колонки (Макс и лайт), которые на другом аккаунте, работают как ни в чем не бывало.
Проблема обнаружил тоже сегодня, хотел расшарить дом, создал ссылку, но так как в Беларуси пишут недоступна эта функция - не стал заканчивать.

**Comment by panfmik** [comment]
Logger: homeassistant.components.media_player
Source: custom_components/yandex_station/core/yandex_quasar.py:171
Integration: Медиаплеер (documentation, issues)
First occurred: 09:28:42 (1 occurrences)
Last logged: 09:28:42

Error while setting up yandex_station platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_station/media_player.py", line 97, in async_setup_entry
    for speaker in await quasar.load_speakers():
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 112, in load_speakers
    await self.add_scenario(device_id)
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 171, in add_scenario
    assert resp['status'] == 'ok', resp
AssertionError: {'request_id': 'd3015ce1-51be-49ac-b5fd-d65f009adaa8', 'status': 'error', 'code': 'SHARED_DEVICE_USED_IN_SCENARIO', 'message': 'Нельзя добавлять в сценарии чужие устройства. Пожалуйста, удалите их из сценария и попробуйте еще раз.'}

**Comment by eratnik** [comment]
> > Яндекс добавил возможность(наконец!) добавлять людей в дом для совместного управления. Но теперь интеграция в HA не видит устройств: не из добавленного дома, не из основного.
> > Получится ли сделать чтобы добавлялись колонки когда дом расшарен?
> 
> У меня три колонки на двух разных аккаунтах. Дом не расшаривал, но детская колонка, которая на отдельном аккаунте, больше как устройство недоступен - остался только эквалайзер, который, к слову, работает. Попробовал удалить аккаунт и добавить заново - добавляется только эквалайзер. Переустановил интеграцию - не помогло. Причем две остальные колонки (Макс и лайт), которые на другом аккаунте, работают как ни в чем не бывало. Проблема обнаружил тоже сегодня, хотел расшарить дом, создал ссылку, но так как в Беларуси пишут недоступна эта функция - не стал заканчивать.

Исправляюсь - вчера обнаружил в проблемном аккаунте два дома. Каким-то образом я все-таки расшарил дом. После удаления второго дома в интеграции пропавшая станция вернулась. Так что дело действительно только во втором доме.

**Comment by AlexxIT** [comment]
> Доброе утро.
@AlexxIT, рассказываю о проблеме в интеграции Yandex Station, связанной с недавними обновлениями в Яндексе.
У меня есть работающий профиль, на котором 6 устройств (модуль и 5 колонок). Если принять приглашение через "Дом с Алисой" и присоединиться к другому дому (уточнение - в этом другом доме тоже есть колонки), то в профиль добавляются колонки из второго дома, но при этом все устройства уходят в статус "недоступно".
Вчера я специально проверила: 
> 1. Отказалась от совместного управления вторым домом, через некоторое время после этого колонки как медиаплееры заработали в ХА (кроме эквалайзеров, эти остались недоступными).
> 2. Снова приняла приглашение на совместное управление другим домом. Интеграцию не перезагружала. Мои 6 устройств продолжали работать.
> 3. Сегодня утром нажала "Перезагрузить интеграцию". В тот же момент в списке устройств их стало 8 (добавились две колонки), но все 8 ушли в статус "недоступно".
Прошло два часа - устройства не приходят в себя.

**Comment by seredaneo** [comment]
Такая же ситуация, на аккаунте 2 дома, один свой, второй приглашенный. В каждом по колонке, в HA добавились только эквалайзеры.

**Comment by semikor** [comment]
> > Доброе утро.
> > @AlexxIT, рассказываю о проблеме в интеграции Yandex Station, связанной с недавними обновлениями в Яндексе.
> > У меня есть работающий профиль, на котором 6 устройств (модуль и 5 колонок). Если принять приглашение через "Дом с Алисой" и присоединиться к другому дому (уточнение - в этом другом доме тоже есть колонки), то в профиль добавляются колонки из второго дома, но при этом все устройства уходят в статус "недоступно".
> > Вчера я специально проверила:
> > 
> > 1. Отказалась от совместного управления вторым домом, через некоторое время после этого колонки как медиаплееры заработали в ХА (кроме эквалайзеров, эти остались недоступными).
> > 2. Снова приняла приглашение на совместное управление другим домом. Интеграцию не перезагружала. Мои 6 устройств продолжали работать.
> > 3. Сегодня утром нажала "Перезагрузить интеграцию". В тот же момент в списке устройств их стало 8 (добавились две колонки), но все 8 ушли в статус "недоступно".
> >    Прошло два часа - устройства не приходят в себя.

Т.е. чтобы добавить колонки в НА отменить ВСЕ раздачи домов, на ВСЕХ аккаунтах?
Добавились только эквалайзеры, причем каким-то чуднЫм образом (на разных аккаунтах - разное количество и разный список колонок, но не на одном нет всех 4х колонок (ну или хотя бы эквалайзеров...))

**Comment by YaLiC** [comment]
Присоединяюсь, проблема есть. После расшаривания в ХА, все колонки недоступны...

**Comment by udavst** [comment]
Проблема есть, хотя меня просто пригласили в другой дом. В HA появились колонки второго дома, но нет возможности управления никакой, в том числе и своей.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.12.0
