### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by pterodaktil02** [AlexxIT/YandexStation#32]
`aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host yandex.ru:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1076)')]`

Steps  to reproduse -  install   and try to make something  with  station

**Comment by AlexxIT** [comment]
У вас с и-нетом проблемы. Кто-то пытается перехватить ваш трафик. Или сервер ХА или роутер или провайдер.

**Comment by pterodaktil02** [comment]
Вы правы.  виноват adguard фильтр

**Comment by zimenkoigor** [comment]
Алекс доброго дня, подскажите пожалуста у меня проблема с подобной надпись...
Cannot connect to host yandex.ru:443 ssl:True [SSLCertVerificationError....
Вопрос возникает в том что у меня все сети 2 home ассистента, на одном работает безупречно на 2 выдаёт такую ошибку, подскажете как можно решить.?

**Comment by AlexxIT** [comment]
Кто-то перехватывает трафик и пытается внедрится в него

**Comment by zimenkoigor** [comment]
Дуброво времени суток , продолжи тему с наблюдения... 
Если установить HA на основе debian 11- работает без нариканий, если установить HA на разбиан по инструкций Alex Kvasiz интеграция либо сразу ругается либо выдает подобную ошибку после одной или двух перезагрузок... 
(Извините если это не интересно) 
Большое спасибо за ваши труды
