### ISSUE TITLE
Невозможно пробросить колонку в НА после перепривязки

### ISSUE THREAD

**Issue by ZeBriD** [AlexxIT/YandexStation#320]
Доброго дня.
Решил попробовать разделить колонки между членами семьи после введения возможности расшаривать УДЯ на другие аккаунты.
Отвязал колонку от своего аккаунта.
В НА удалил объект media_player, т.к. он стал недоступным (эквалайзер остался, ввиду отсутствия такой возможности, тут подробнее https://github.com/AlexxIT/YandexStation/issues/319)
Привязал к новому аккаунту.
Добавил новый аккаунт вторым в НА.
Второй аккаунт принёс только эквалайзер, но не саму колонку.

Что более печально, при попытке откатить изменения, перепривязал колонку на старый аккаунт. Перезапустил интеграцию. Но колонка так и не появилась в НА.

Подскажите, как её таки вернуть к жизни ?

**Comment by alphasixtyfive** [comment]
Подтверждаю, та же беда.

**Comment by AlexNetYT** [comment]
Такая же проблема, поддержу вопрос!

**Comment by AlexNetYT** [comment]
#265 Проблему решил с помощью способа в этом issue! Спасибо за здоровье моих нервов @alexxx113!

**Comment by seredaneo** [comment]
У меня два аккаунта, и соответственно тоже колонки не добавлялись.
Я добавил try/except в load_speakers в yandex_quasar.py и колонки из основного аккаунта добавились нормально.

    async def load_speakers(self) -> list:
        speakers = self.speakers

        # Яндекс начали добавлять device_id и platform с полным списком
        # устройств
        # for speaker in speakers:
        #     await self.load_speaker_config(speaker)

        scenarios = await self.load_scenarios()
        for speaker in speakers:
            device_id = speaker['id']
            try:
                if device_id not in scenarios:
                    await self.add_scenario(device_id)
                    scenarios = await self.load_scenarios()

                speaker['scenario_id'] = scenarios[device_id]['id']
            except:
                print('bad')

        return speakers

**Comment by seredaneo** [comment]
> У меня два аккаунта, и соответственно тоже колонки не добавлялись. Я добавил try/except в load_speakers в yandex_quasar.py и колонки из основного аккаунта добавились нормально.
> 
> ```
> async def load_speakers(self) -> list:
>     speakers = self.speakers
> 
>     # Яндекс начали добавлять device_id и platform с полным списком
>     # устройств
>     # for speaker in speakers:
>     #     await self.load_speaker_config(speaker)
> 
>     scenarios = await self.load_scenarios()
>     for speaker in speakers:
>         device_id = speaker['id']
>         try:
>             if device_id not in scenarios:
>                 await self.add_scenario(device_id)
>                 scenarios = await self.load_scenarios()
> 
>             speaker['scenario_id'] = scenarios[device_id]['id']
>         except:
>             print('bad')
> 
>     return speakers
> ```

Добавил удаление колонки, которая находится в другом аккаунте(приглашение в другой дом). Теперь у меня привязано 2 аккаунта, и все колонки видны.

        for speaker in speakers:
            device_id = speaker['id']
            try:
                if device_id not in scenarios:
                    await self.add_scenario(device_id)
                    scenarios = await self.load_scenarios()

                speaker['scenario_id'] = scenarios[device_id]['id']
            except:
                print('bad')
                speakers.remove(speaker)

**Comment by udavst** [comment]
> У меня два аккаунта, и соответственно тоже колонки не добавлялись.

Спасибо [seredaneo](https://github.com/seredaneo), правка действительно рабочая. Пробовал их других веток - то разговаривать перестаёт, то ничего не меняется, а Ваши пара строк, вернула к жизни интеграцию!

**Comment by eratnik** [comment]
> > У меня два аккаунта, и соответственно тоже колонки не добавлялись. Я добавил try/except в load_speakers в yandex_quasar.py и колонки из основного аккаунта добавились нормально.
> > 
> > ```
> > async def load_speakers(self) -> list:
> >     speakers = self.speakers
> > 
> >     # Яндекс начали добавлять device_id и platform с полным списком
> >     # устройств
> >     # for speaker in speakers:
> >     #     await self.load_speaker_config(speaker)
> > 
> >     scenarios = await self.load_scenarios()
> >     for speaker in speakers:
> >         device_id = speaker['id']
> >         try:
> >             if device_id not in scenarios:
> >                 await self.add_scenario(device_id)
> >                 scenarios = await self.load_scenarios()
> > 
> >             speaker['scenario_id'] = scenarios[device_id]['id']
> >         except:
> >             print('bad')
> > 
> >     return speakers
> > ```
> 
> Добавил удаление колонки, которая находится в другом аккаунте(приглашение в другой дом). Теперь у меня привязано 2 аккаунта, и все колонки видны.
> 
>         for speaker in speakers:
>             device_id = speaker['id']
>             try:
>                 if device_id not in scenarios:
>                     await self.add_scenario(device_id)
>                     scenarios = await self.load_scenarios()
> 
>                 speaker['scenario_id'] = scenarios[device_id]['id']
>             except:
>                 print('bad')
>                 speakers.remove(speaker)

Может сделаете PR Алексу?

**Comment by udavst** [comment]
Где?

**Comment by eratnik** [comment]
> Где?

Ну, здесь. Создать ветку, сделать коммит с изменениями и сделать pull request

**Comment by AlexxIT** [comment]
#317
