### ISSUE TITLE
Пропали обложки альбомов в карточках

### ISSUE THREAD

**Issue by Alex2030S** [AlexxIT/YandexStation#322]
Доброго дня.
После замены колонки Мини с часами по гарантии и привязки новой - в карточке Mini Media Player перестали отображаться обложки альбомов (прошивка 1.141.1.15.1503698103.20221031.97). После сегодняшнего обновления прошивки Макс (1.141.1.15.1503698103.20221031.97) - в карточке тоже не отображаются обложки.
Подскажите как поправить или проверьте баг.
Up - после перезагрузки колонок: на Макс обложки заработали; на Мини 2 - нет и пропал статус бар проигрывания мелодии(((

**Comment by osnwt** [comment]
Та же история с Мини 2. Ощущение, что заблокировали локальный протокол, или что-то поменялось с обнаружением. Рестарт не помогает. 3 колонки, на всех обновленная прошивка 0.139.1.19.1479560459.20221011.84. Одна ведет себя как-то иначе (обложка осталась). Остальные - увы.

**Comment by osnwt** [comment]
Почему-то одна из трех мини2 сообщает о себе по mDNS, а две других - нет.

Если перезагрузить по питанию колонку, то она сообщает о себе в mDNS, но только имя устройства без остальных параметров. А спустя небольшое время исчезает из mDNS браузера. При этом та, что работала, продолжает работать (выключать не хочется, вдруг тоже пропадет).

Прошивки везде одинаковые.

**Comment by Alex2030S** [comment]
Не знаю что произошло, кто когда и где оправил - с сегодня (2022-11-09) обложка на Мини 2 появилась....

**Comment by Alex2030S** [comment]
перегрузил колонку (отключением питания) обложка продолжает отображаться....

**Comment by Alex2030S** [comment]
> Подтверждаю. Вторая из моих трех колонок, что была в сети, тоже стала вещать mDNS. А вот третья, что стояла выключенной сутки, после подключения по прежнему не вещает и, соответственно, работает только в облачном режиме.
> 
> Буду наблюдать дальше.

Подскажи - как проверить вещание mDNS?

**Comment by osnwt** [comment]
Полчаса постояла - и заработала тоже.

**Comment by Alex2030S** [comment]
> Полчаса постояла - и заработала тоже.

Допили втихаря)))))

**Comment by osnwt** [comment]
> Подскажи - как проверить вещание mDNS?

Я на Mac использую утилиту Discovery: https://apps.apple.com/ru/app/discovery-dns-sd-browser/id1381004916?mt=12

Что-то подобное есть и на другие OS.

![image](https://user-images.githubusercontent.com/1081613/200685185-f029c16a-62cb-4719-8254-01219cf2f43d.png)

**Comment by AlexxIT** [comment]
Колонка не нашлась локально. Интеграция не может с этим что-то поделать. Можно попробовать указать колонке IP адрес.
