### ISSUE TITLE
Поломался уровень громкости в Яндекс Станция 2

### ISSUE THREAD

**Issue by XseonLD** [AlexxIT/YandexStation#329]
Появилась проблема пару дней назад.
Есть две станции Лайт и Яндекс Станция 2. В одной из автоматизаций используется сервис media_player.volume_down|up. Если запустить сервис указав обе колонки, то атрибут volume_level меняется только на Лайте(раньше работало и на Яндекс Станция 2).
Отсюда появилась проблема, из HA при вызове вышеуказанной службы она может ОДИН РАЗ прибавить или отнять громкость на 0.1 от текущего (0.5), который не изменяется на Яндекс Станция 2. Повторюсь, ранее работало от 0 до 1 и на Лайт и на Яндекс Станция 2.

**Comment by AlexxIT** [comment]
У вас или отвалился локальный режим для Станции 2. Что обычно решается перезагрузкой станции.
Или в новой прошивке Станции 2 поломали уровень громкости через локальные API. Что собственно на уровне компонента не починить.
