### ISSUE TITLE
Будильник

### ISSUE THREAD

**Issue by TonTon-Macout** [AlexxIT/YandexStation#333]
Есть ли возможность узнать что на станции сработал будильник, что бы запустить разного рода автоматизации?

**Comment by AlexxIT** [comment]
Можно закостылить на основе автоматизаций из интеграции с Телеграмом:
https://github.com/AlexxIT/YandexStation#%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%B0%D0%BB%D0%B8%D1%81%D0%B0-%D0%B2-telegram
