### ISSUE TITLE
Алиса в Telegram через Node-Red

### ISSUE THREAD

**Issue by urtaevS** [AlexxIT/YandexStation#334]
Как можно сделать отправку ответов от Алисы в Telegram но в Node-Red?
Не могу найти как указать _trigger_ **yandex_station_response**.

**Comment by urtaevS** [comment]
Пичалько((
Я вроде сам накопал как это можно сделать, тут нет смысла делиться?

**Comment by AlexxIT** [comment]
Можете написать. Вдруг кто-то по вашим стопам нагуглит.
