### ISSUE TITLE
2023.3 Bug

### ISSUE THREAD

**Issue by alphasixtyfive** [AlexxIT/YandexStation#345]
Looks like something has changed in 2023.3 as following error started showing up  in logs and all Yandex devices became unavailable. 

```
Config entry 'XXXXX' for yandex_station integration not ready yet: too many values to unpack (expected 2); Retrying in background
```

Deleting the integration completely, adding it again and restarting HA appears to resolve the issue. Rebooting is necessary for entities to appear under each of the device.

**Comment by ezhische** [comment]
The same error, will try workaround with reinstall

**Comment by TolianIPB** [comment]
The same. I removed the integration. Installed again. Now I can not log in one of the ways. 
https://github.com/AlexxIT/YandexStation/issues/347

**Comment by zzaal** [comment]
2023.3
I have the same error
not working

**Comment by kot-925** [comment]
Тоже самое, интеграция перестала работать

**Comment by ShammanIT** [comment]
The same problem.

**Comment by misha1183** [comment]
Просто добавил интеграцию снова. Именно без удаления. Было сообщение данные обновлены, перезапустить и порядок.

**Comment by zzaal** [comment]
> Просто добавил интеграцию снова. Именно без удаления. Было сообщение данные обновлены, перезапустить и порядок.

спасибо! заработало!!!

**Comment by notabene00** [comment]
Solved by reauthentication (`add` again without removing)

**Comment by TolianIPB** [comment]
У меня второй день не хочет авторизовываться никаким способом.
![Ya](https://user-images.githubusercontent.com/36660653/222384680-ccd7fdb9-a6e8-4afb-baf7-abb6f8b97321.jpg)

**Comment by TolianIPB** [comment]
Чёртов Тындекс... Только по QR коду удалось пойти. Спасибо!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.12.0

**Comment by Alex2030S** [comment]
> https://github.com/AlexxIT/YandexStation/releases/tag/v3.12.0

Все заработало!!!!
