### ISSUE TITLE
Retrying setup: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by dobriys** [AlexxIT/YandexStation#348]
После обновления до Home Assistant 2023.3.0 не стартует. Пишет ошибку `Retrying setup: too many values to unpack (expected 2)`
![Снимок экрана 2023-03-02 в 10 18 46](https://user-images.githubusercontent.com/49061466/222358385-34586f5b-ce97-4f1f-a4e4-1f836e5c17cf.png)

**Comment by AlexxIT** [comment]
#345
