### ISSUE TITLE
Отвалилась интеграция в ХА

### ISSUE THREAD

**Issue by andrey170183** [AlexxIT/YandexStation#350]
Видимо после последнего обновления ядра ХА не запускается интеграция. 
![Screenshot_20230303-013335064 (1)](https://user-images.githubusercontent.com/42129962/222493166-2848bee0-f263-4a7c-a9ed-7e0ec41c5f31.jpg)
У меня две колонки ругается в логе:
Logger: homeassistant.config_entries
Source: config_entries.py:1244
First occurred: 01:18:39 (1 occurrences)
Last logged: 01:18:39

Config entry '*******83' for yandex_station integration not ready yet: too many values to unpack (expected 2); Retrying in background

**Comment by glazkovigor** [comment]
Проблема такая же и у меня, пять колонок - все отвалились!

Logger: homeassistant.config_entries
Source: config_entries.py:1244
First occurred: 20:03:19 (1 occurrences)
Last logged: 20:03:19

Config entry '________________' for yandex_station integration not ready yet: too many values to unpack (expected 2); Retrying in background

**Comment by glazkovigor** [comment]
также появилась такая ошибка в логе

Logger: homeassistant.helpers.integration_platform
Source: custom_components/yandex_station/intent.py:20
Integration: Yandex.Station ([documentation](https://github.com/AlexxIT/YandexStation), [issues](https://github.com/AlexxIT/YandexStation/issues))
First occurred: 20:04:10 (1 occurrences)
Last logged: 20:04:10

Error processing platform yandex_station.intent
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 51, in _async_process_single_integration_platform_component
    await integration_platform.process_platform(hass, component_name, platform)
  File "/usr/src/homeassistant/homeassistant/components/intent/__init__.py", line 203, in _async_process_intent
    await platform.async_setup_intents(hass)
  File "/config/custom_components/yandex_station/intent.py", line 20, in async_setup_intents
    platform = device['quasar_info']['platform']
KeyError: 'quasar_info'

**Comment by AlexQuaken** [comment]
Аналогично, три колонки после обновления все сломалось, видимо проблема затрагивает только тех у кого больше одной.

**Comment by glazkovigor** [comment]
обновите интеграцию, версия 3.12.0 решила проблему.
