### ISSUE TITLE
Вопрос: Можно ли обернуть яндекс алису в chromecast устройство.

### ISSUE THREAD

**Issue by WeslyG** [AlexxIT/YandexStation#360]
Не нашел нигде ответа на вопрос, спрошу тут, но может быть не по теме. 
Можно ли обернуть яндекс станции в хромкаст девайс через ha? 
Т.е чтобы в списке девайсов на воспроизведение в телефоне могли отображаться алисы. А работало это все через ha? 
Ну т.е медиа плеер у нас есть, воспроизводить на нем мы можем. Почему мы не можем налепить на него виртуальный интерфейс chromecast, дабы всякие яндекс музыки с телефона, корректно работали у всех членов семьи например, также как они работают на телевизоре через chomecast.

**Comment by AlexxIT** [comment]
Я не встречал рабочей технологии "притворится Chromecast устройством".
Для AirPlay это можно сделать. А вот Chromecast приёмник эмулировать нельзя.

PS. Существуют довольно сложные инструкции с получением каких-то ключей с серверов Google в реальном режиме времени 24/7. Я такие не рассматриваю.

**Comment by nick2525** [comment]
Это делается по-другому, берется хромкаст аудио (если найдете) либо обычный, только с hdmi to av + звук, потом звук подключается к jack 3.5 в bluetooth, таких много. А через HA можно сделать включение/выключение bluetooth

**Comment by akarabach** [comment]
@AlexxIT а есть смысл притворяться AirPlay устройством ? Если мы не можем передать стрим на колонку напряпую (не через ble и jack 3.5)

**Comment by AlexxIT** [comment]
1. AirPlay протокол поддерживает проигрывание аудио по ссылкам, там не обязательно поток
2. Я недавно видел API ЯДиалогов с проигрыванием аудио по ссылкам, но ещё не успел их попробовать

**Comment by akarabach** [comment]
Интересно, почитаю, попробую и отпишусь. Интересно было бы выводить любой звук по AirPlay через колонку, будет это нативная интеграция Spotify в HA или звук напрямую из Apple TV, это очень сильно развязало бы руки. Начну с API ЯДиалогов и Spotify, потом тут отпишусь

**Comment by AlexxIT** [comment]
Ну совершенно любой звук это уже про bluetooth соединение. И это в принципе возможно, только сильно заморочно.

**Comment by akarabach** [comment]
есть еще интересная идея https://habr.com/ru/articles/479242/ - но старая, у меня в плеере нет этой кнопки, можно было бы напрямую попробовать тригернуть а не через диалоги

**Comment by nick2525** [comment]
Кстати, в поиске видео в Яндексе появилась кнопка транслировать на станцию или на модуль. Там возможно, какое-то новое Api появилось

**Comment by WeslyG** [comment]
Да, осознал что это проприетарная технология, с ключами гугла, и тут так просто не сделать. Спасибо за обьяснения!
