### ISSUE TITLE
Unsupported url

### ISSUE THREAD

**Issue by Furrypaw** [AlexxIT/YandexStation#363]
Logger: custom_components.yandex_station.media_player
Source: custom_components/yandex_station/media_player.py:938
Integration: Yandex.Station ([documentation](https://github.com/AlexxIT/YandexStation), [issues](https://github.com/AlexxIT/YandexStation/issues))
First occurred: 2:19:45 PM (1 occurrences)
Last logged: 2:19:45 PM

Unsupported url: https://s120vlx.storage.yandex.net/get-mp3/b40ceb0f49fcf0399fd453b9aa8087a4/0005f8be0a66eda2/rmusic/U2FsdGVkX1_mFsNd8JHP_cd93G8BTGee7779NCMa4eAQoOsYrN7kO5_giHdimeHsfGRk9FydmL9KgyGx11svaCYnZTBNVxrxf3yg5u2ljJY/5918f9f90792e3e1092b22414acf303c2590cc85628ca9afc5abca69cb6e8d81/30867

Opening URL in browser works just fine. Any way to fix it?

**Comment by AlexxIT** [comment]
Станции не поддерживают проигрывание аудио по произвольным ссылкам.
