### ISSUE TITLE
Для управления устройствами из Яндекса требуется несколько действий

### ISSUE THREAD

**Issue by JaybeRF** [AlexxIT/YandexStation#364]
Из Яндекса проброшены 2 розетки. При включении/отключении розетки из HA требуется повторить это действие несколько раз, прежде чем статус устройства в HA изменится. Само включение/отключение происходит сразу же. Перезагрузка интеграции ничего не даёт.

**Comment by JaybeRF** [comment]
В результате, переключаю розетки кнопкой в HA, по которой действие повторяется несколько раз через паузу. Только так можно гарантировать, что устройство включится и статус в HA будет актуальным.

**Comment by AlexxIT** [comment]
Статус устройств Яндекса обновляется раз в 30 секунд

**Comment by Air4L1fe** [comment]
Этот тайм-аут в 30 секунд можно где-то настраивать?

**Comment by AlexxIT** [comment]
Исправление кода компонента.

Или переписыванием всей логики компонента на мгновенное обновление статусов. Не планируется в ближайшее время.
