### ISSUE TITLE
Не проходят команды сценариев после обновления до 3.12.2

### ISSUE THREAD

**Issue by MrAlyr** [AlexxIT/YandexStation#367]
Не проходят команды в HA от станций после обновления до версии 3.12.2
Пробовал на HA 2023.3.1 и 2023.4.6
После восстановления из бекап на версии 3.12.1 все вновь работает
События yandex_speaker не видны в HA

**Comment by AndrePV88** [comment]
Здравствуйте! То же последнее обновление (3.12.2) через некоторое время приводит к зависанию НА, помогает перезагрузка. После отката на резервную копию проблема ушла, НА стал стабильно работать.

**Comment by Regressor** [comment]
У меня вообще колонки пропали после обновления до 2023.5.4 - одни эквалайзеры остались. Просто пишет устройство не предоставляется интеграцией. Было 2 колонки и 4 устройства (плер + эквалайзер), стало 2 устройства. Обновился чтобы интеграцию roborock поставить, которая с 2023.4.6 работает...
