### ISSUE TITLE
Алиса зависает на фразах с точкой

### ISSUE THREAD

**Issue by mihail4anov** [AlexxIT/YandexStation#37]
Собственно после произнесения фразы  **Какая температура в комнате: .**
Алиса продолжает крутить фиолетовую подсветку и ничего не происходит.
![1](https://user-images.githubusercontent.com/66550669/86531569-206eeb00-becb-11ea-839e-e2e4d65e532d.jpg)
Полная строка Data из node red {"media_content_id":"Повторяю вашу фразу","media_content_type":"text"}

Чтобы остановить фиолетовый индикатор нажимаю на Алисе кнопку команды, и она произносит "Повторяю вашу фразу"

UPD
Много экспериментировал. Видимо проблема в 
  _intents:
    Романтический вечер: приятно провести время
    Какая температура в комнате: ._

**Романтический вечер** отрабатывает и фиолетовая индикация гаснет.
**Какая температура в комнате**  Индикация продолжает крутиться.
Алиса не может произнести **.** (точка). Из за этого и продолжает гореть индикатор.

**Comment by mihail4anov** [comment]
Решение предоставил сам **AlexxIT**
_intents:
    Какая температура в комнате: sil <[500]>
    Какая влажность в комнате: sil <[500]>_

**Comment by AlexxIT** [comment]
Проблема с точкой давно не актуальна
