### ISSUE TITLE
Странные правила для проигрывания TTS

### ISSUE THREAD

**Issue by MakarovIncorporated** [AlexxIT/YandexStation#371]
После использования третьего способа проиграть TTS (т.е. media_content_type: dialog) ИИ начал сам выбирать какое предложение сказать, а какое проигнорировать: ("Пфф","Неа", "Да вы оригинал" или "Ой, всё").

Если в media_content_id передать строку 

> Пользователи Сети обратили внимание, что в App Store изменилась ожидаемая дата глобального релиза Call of Duty Warzone Mobile. Ранее в магазине указывалось 15 мая, теперь написано, что игра выйдет 1 ноября. Activision не подтвердила эту дату, но и не стала опровергать.

то она ее отлично произнесет.
Но стоит передать в этот же параметр строку:
> Electronic Arts спустя год после анонса выпустила мобильную условнобесплатную ролевую игру The Lord of the Rings Heroes of Middleearth. В Сети также выложили релизный трейлер проекта.

То Алиса ее читать не станет, даже если уменьшать строку до тех пор, пока от нее не останется: 
> Electronic Arts спустя год после анонса вы

Эту же строку с меньшим кол-вом символов Алиса читает отлично.

Дело явно не в длине сообщения, да и сам способ подразумевает что ограничения по длине нет. Что было проверено передачей первой строки 3 раза через запятую. также если в media_content_type: передать параметр text, то колонка отлично справится с прочтением строки, но вот только длинной не более 100 символов, как и сказано в документации.

Далее будут примеры строк которые не читает Алиса:

НЕ читает:
> В 2006 году по роману Агаты Кристи (Agatha Christie) уже выходила игра Agatha Christie Murder on the Orient Express. Теперь нас ждёт новая адаптация детектива — издательство Microids готовится выпустить более свежую версию квеста.

Читает:
> В 2006 году по роману Агаты Кристи (Agatha Christie) уже выходила игра Agatha Christie Murder on the Orient Express. Теперь нас ждёт новая адаптация детектива — издательство Microids готовится вы

НЕ читает:
>Студия Final Strike Games выпустила полумёртвый онлайнэкшена Rocket Arena и занимается liveсервисами Fortnite. Её следующей игрой должен был стать AAAшутер с PvP по новой франшизе — для ПК и консолей. Но, похоже, не станет.

Читает:
> Студия Final Strike Games вы

Прямо во время написания проблемы было выяснено что у Алисы "аллергия" на сочетание букв "вып", не смотря на то что они могут стоять в любой части слова. Это обуславливает проблемы с строками, т.к. по идее каждая содержит "вып". Интересно на чей стороне косяк? У Яндекса или у интеграции?

**Comment by AlexxIT** [comment]
На стороне Яндекса конечно. Единственное что делает интеграция, это обрезает текст до 100 символов, если команда облачная. Иначе команда просто упадёт.
