### ISSUE TITLE
Не работает кнопка "donate Yandex"

### ISSUE THREAD

**Issue by l3zha** [AlexxIT/YandexStation#382]
Яндекс деньги отъехали же

<img width="662" alt="Screenshot 2023-09-06 at 22-52-18" src="https://github.com/AlexxIT/YandexStation/assets/134725565/79b570a6-269c-40e8-a269-1993c5e89531">

**Comment by l3zha** [comment]
@alryaz у вас тоже

**Comment by AlexxIT** [comment]
Спасибо, убрал. Нет кнопки - нет проблемы :)
