### ISSUE TITLE
Установка громкости через скрипт Home Assistant

### ISSUE THREAD

**Issue by booroondook-eng** [AlexxIT/YandexStation#388]
Использую Яндекс-станцию, в частности, для проговаривания оповещений.
В скрипте HA задается громкость - примерно так (фрагмент скрипта):
```
  - service: media_player.volume_set
    data:
      volume_level: 0.7

```
Проблема состоит в том, что если на колонке до выполнения скрипта была установлена громкость, **равная** той, что задает скрипт, то колонка вначале произносит фразу типа "уже установлено" или "окей" или еще какую-нибудь - то есть, "дает понять", что нужная громкость уже была до команды.
Вопрос: как с этим можно бороться?

**Comment by stuffmsksu** [comment]
Добрый день.
Может проще использовать extra



service: media_player.play_media
data:
  media_content_id: Напоминаю выпить воду.
  media_content_type: text
  extra:
    volume_level: 0.8
target:
  entity_id:
    - media_player.yandex_station

чт, 21 сент. 2023 г., 21:55 booroondook ***@***.***>:

**Comment by booroondook-eng** [comment]
> Добрый день. Может проще использовать extra service: media_player.play_media data: media_content_id: Напоминаю выпить воду. media_content_type: text extra: volume_level: 0.8 target: entity_id: - media_player.yandex_station> […](#)

Спасибо! Помогло!
