### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype

### ISSUE THREAD

**Issue by DieMetRik** [AlexxIT/YandexStation#389]
Сегодня заметил вот такое:

```
Эта ошибка возникла в пользовательской интеграции.

Logger: custom_components.yandex_station.core.yandex_glagol
Source: helpers/aiohttp_client.py:72
Integration: Yandex.Station (documentation, issues)
First occurred: 08:05:26 (45 occurrences)
Last logged: 08:52:57

Яндекс Спальня | Station connect
Яндекс гостининая | Station connect
Яндекс Кухня | Station connect
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 89, in _connect
    self.device_token = await self.get_device_token()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_glagol.py", line 59, in get_device_token
    resp = await r.json()
           ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 72, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://quasar.yandex.net/glagol/token?device_id=LP000000000000067686000034bb0901&platform=yandexmicro')

```
```
Home Assistant 2023.9.2
Supervisor 2023.09.2
```

**Comment by DIMMonchik** [comment]
У меня интеграция перестала показывать состояние всех станций, но управляет ими.

> sound_mode_list: Произнеси текст, Выполни команду
volume_level: 0.5
is_volume_muted: false
source: Станция
sound_mode: Произнеси текст
entity_picture_local: null
assumed_state: true
device_class: tv
icon: yandex:station-max
friendly_name: Яндекс Станция Макс
supported_features: 214973

**Comment by KAPACb1988** [comment]
Тоже сейчас вижу эту проблему, в Lovelace, плеер стал синий, без обложки..
![Screenshot_20230923_133906_io homeassistant companion android](https://github.com/AlexxIT/YandexStation/assets/91968865/cc65fbd2-6418-4404-af10-4130e241e2de)
если вручную на станции сказать Алиса продолжить играть, состояние не обновиться на playing, только если нажму кнопку play в ha, тогда статус поменяется... Из-за этого многие сценарии некорректно работают, которые просматривает статус станции, playing, paused, или idle..

**Comment by dext0r** [comment]
Быстрый фикс:
1. Открываем custom_components/yandex_station/core/yandex_glagol.py
2. Меняем `resp = await r.json()` на `resp = json.loads(await r.text())` (строка 59)

**Comment by DieMetRik** [comment]
Попробую спасибо

**Comment by Nedjumiiro** [comment]
У меня сегодня такая же ошибка вылетает в логе

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.12.4

**Comment by osnwt** [comment]
Если у кого-то после выхода обновления не починилось, то попробуйте принудительно переустановить компонент. У меня по прежнему стояла версия 3.12.3, но обновление не прилетало. Переустановил 3.12.4 (HACS -> Скачать повторно), и все пофиксилось.
