### ISSUE TITLE
После обновления в "Источниках" - только Станция

### ISSUE THREAD

**Issue by str-ms** [AlexxIT/YandexStation#393]
После обновления в "Источниках" - только Станция, раньше была возможность стриминга со станции Яндекс-Мини с часами, хотя бы по одной композиции, на Heos ресивера Denon AVR-x2700H. В чём может быть дело, куда копать?

**Comment by AlexxIT** [comment]
Нужно вручную источники прописать через YAML. Автоматическое определение источников зависит от порядка старта разных интеграций. Если Яндекс стартует раньше других - она другие источники не заметит
