### ISSUE TITLE
Ошибка "A custom component is preventing service data from loading" при создании виджета с вызовом сервиса на андрйоде

### ISSUE THREAD

**Issue by denis0706** [AlexxIT/YandexStation#396]
При создании виджета с вызовом сервиса нет возможности выбрать сервис из выпадающего списка, отображается сообщение "A custom component is preventing service data from loading"
Решение - добавить  значения к пустым полям description в сервисах в /config/custom_components/yandex_station/services.yaml

**Comment by AlexxIT** [comment]
Вероятно исправлено в последних версиях
