### ISSUE TITLE
Не видит станции в других локальных сетях

### ISSUE THREAD

**Issue by SahaReRa** [AlexxIT/YandexStation#398]
Добрый день!
Дня три назад перестали быть доступными яндекс станции в локальной сети, отличной от локальной, где расположен Home assistant. Видит только одну станцию, которая расположена в той же подсети.

В главном интерфейсе станции подсвечены серым и пишет, что недоступны. Соответственно запросы на них не отправляются, хотя все станции подключены к интернету и работают. 
![image](https://github.com/AlexxIT/YandexStation/assets/127118669/e12f95b3-359a-41f2-8d7a-739055a08e45)

При попытке переустановки модуля пишет ошибку:
Logger: homeassistant.setup
Source: setup.py:191
First occurred: 12:26:50 (1 occurrences)
Last logged: 12:26:50

Setup failed for yandex_station: Integration not found.

Кто-нибудь сталкивался с подобной проблемой?

доп от 13.10.23:
Сделал чистую установку HA и всех интеграций на новую машину, проблема аналогичная осталась..
Пинговал напрямую с НА на яндекс станции (vpn поднят между сетями) - пинг проходит. И из подсетей тоже пинг проходит до машины с HA.

**Comment by SahaReRa** [comment]
Проблема исправилась сама собой... 
![image](https://github.com/AlexxIT/YandexStation/assets/127118669/acdfc019-1100-460e-a5ae-89ea2a119dc4)
Вопрос можно закрыть.

**Comment by AlexxIT** [comment]
Была какая-то проблема на серверах Яндекса
