### ISSUE TITLE
поведение "воспроизвести текст" в медиаплеере

### ISSUE THREAD

**Issue by svsolopov** [AlexxIT/YandexStation#4]
Сейчас оно работает как и задумывалось - воспроизводит текст, однако для алисы ИМХО удобнее чтобы это было полноценной командой для нее (у себя я в коде просто убрал "повторяй за мной").
Это позволяет запустить любую композицию/видео удаленно.
Предлагаю добавить параметр в конфиг, который это регулирует (по умолчанию пусть воспроизводит текст, для совместимости)

**Comment by AlexxIT** [comment]
Уже в релизе (2 часа назад)

**Comment by svsolopov** [comment]
:) Спасибо

**Comment by iswitch** [comment]
После появления переключателя и выбора режима "Выполни команду", поломался tts.yandex_station_say, в место проговаривания, выполняются команды.

**Comment by AlexxIT** [comment]
@iswitch к сожалению это именно так и работает. Переключатель влияет на вызов сервиса `tts.yandex_station_say`. Откуда он вызывается - технически невозможно понять.

Если хочется пользоваться переключателем - в автоматизациях можно использовать `send_command`.
