### ISSUE TITLE
Подключение оплаченных голосов Яндекса

### ISSUE THREAD

**Issue by AlexeyHimki** [AlexxIT/YandexStation#40]
Если у меня есть api key к оплаченным голосам Яндекса, я могу их использовать с вашим компонентом?

https://cloud.yandex.ru/docs/speechkit/tts/voices

**Comment by AlexxIT** [comment]
Нет. Тут есть только Яндекс Алиса.
Для ХА есть другой компонент для TTS через SpeechKit. У меня нет на него ссылки. Но он не работает с колонками Яндекса.
