### ISSUE TITLE
Увлажнитель постоянно включён в HA вне зависимости от актуального состояния

### ISSUE THREAD

**Issue by JaybeRF** [AlexxIT/YandexStation#400]
Проблема замечена после обновления НА до 2023.10.3

**Comment by JaybeRF** [comment]
Остальные устройства - пылесос, розетки, лампочки - без изменений

**Comment by JaybeRF** [comment]
Теперь состояние увлажнителя всегда Недоступно, хотя температура и влажность с него доступны
![Screenshot_20231102_174245_Home Assistant](https://github.com/AlexxIT/YandexStation/assets/29609561/117d41aa-1c8f-49aa-b03c-c94c81f1b986)

**Comment by JaybeRF** [comment]
`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:696
First occurred: 15:57:23 (463 occurrences)
Last logged: 23:42:39

Update for humidifier.uvlazhnitel fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/yandex_station/humidifier.py", line 147, in async_update
    data = await self.quasar.get_device(self.device["id"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 329, in get_device
    r = await self.session.get(f"{URL_USER}/devices/{deviceid}")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 465, in get
    return await self._request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 493, in _request
    r = await getattr(self.session, method)(url, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 400, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed`

**Comment by JaybeRF** [comment]
Logger: homeassistant.components.humidifier
Source: helpers/entity_platform.py:610
Integration: Увлажнитель ([documentation](https://www.home-assistant.io/integrations/humidifier), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+humidifier%22))
First occurred: 15:57:13 (7 occurrences)
Last logged: 20:39:40

Platform yandex_station does not generate unique IDs. ID *** already exists - ignoring humidifier.uvlazhnitel

**Comment by JaybeRF** [comment]
Удаление интеграции и перепривязка на данный момент решили проблему

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.0
