### ISSUE TITLE
Пропала строка ввода текста для TTS

### ISSUE THREAD

**Issue by misha1183** [AlexxIT/YandexStation#404]
Из карточки плеера, mini-media-pleer пропала строка ввода текста доя TTS / Команд.

**Comment by Hipokys** [comment]
![3](https://github.com/AlexxIT/YandexStation/assets/25736915/d6a549cf-7439-4573-9e57-ce10da5ba1a5)
Внутрь карточки провалитесь.

**Comment by misha1183** [comment]
Спасибо. Имел ввиду, что эта строка прямо на карточке была. Рядом с кнопкой отправить.
