### ISSUE TITLE
Обновление списка покупок

### ISSUE THREAD

**Issue by Krabalex** [AlexxIT/YandexStation#405]
После обновления HA до версии 2023.11.0 перестал синхронизироваться с Алисой список покупок 
Видимо, это связано с изменением формата ведения списка покупок и появление "Todo-листов"

**Comment by Krabalex** [comment]
в общем, оказалось, что нужно просто карточку новую выставить в дашборде.. старая карточка не работала :)

**Comment by dankarization** [comment]
У меня после этого новые товары добавляются в алису, удаленные через алису удаляются в HA, но вот вычеркнутые в HA не удаляются из нее
