### ISSUE TITLE
Есть ограничение на произнесение текста... Как можно обойти?

### ISSUE THREAD

**Issue by andrey170183** [AlexxIT/YandexStation#406]
Здравствуйте.

Есть ли ограничение на длину текста, переменной text?
Когда делаю воспроизведение текста через media_player.play_media конец сообщения отсекается. Как можно убрать ограничение?

service: media_player.play_media
target:
  entity_id: "{{ trigger.event.data.entity_id }}" 
data:
  media_content_type: text
  media_content_id: "{{ text }}"

**Comment by AlexxIT** [comment]
Ограничение есть. Все ответы в документации
