### ISSUE TITLE
Поддержка Smart Display 10R X10G

### ISSUE THREAD

**Issue by Glowar** [AlexxIT/YandexStation#408]
Добрый день! Возможна ли? И планируется ли поддержка Smart Display 10R X10G?

**Comment by AlexxIT** [comment]
Если я правильно понимаю, оно поддерживается. Но лично у меня его нет, не могут сказать, насколько там всё хорошо или плохо

https://github.com/AlexxIT/YandexStation/blob/52f6316b59ec4d96debc602c6eeaae8b099bc5bd/custom_components/yandex_station/media_player.py#L118
