### ISSUE TITLE
Пропала возможность ввода команд в Mini Media Player

### ISSUE THREAD

**Issue by floingnom** [AlexxIT/YandexStation#409]
Пропало поле ввода, но при нажатии на то место, где оно раньше было, можно получить такое:
Не удалось вызвать службу media_player/media_seek. Entity media_player.yandex_station_xxxxxx does not support this service.

**Comment by andrew-yu** [comment]
![screenshot-2023 11 10-21_25_27](https://github.com/AlexxIT/YandexStation/assets/27214373/c15adf9e-7d1e-405d-b910-fefe55ed121f)
Пропала возможность отправлять сообщения на колонки.

**Comment by andrew-yu** [comment]
Это решает проблему (не забудьте почистить кэш!) https://github.com/kalkih/mini-media-player/issues/785

**Comment by zenderman** [comment]
> Это решает проблему (не забудьте почистить кэш!) [kalkih/mini-media-player#785](https://github.com/kalkih/mini-media-player/issues/785)

Ничего не понял там из описания.

**Comment by floingnom** [comment]
Помогло.
С помощью **File Editor** отредактировал _/config/www/community/mini-media-player/mini-media-player-bundle.js_ следующим образом: поменял `paper-input` на `ha-textfield` в этом блоке:
```
      <ha-textfield
        id="tts-input"
        class="mmp-tts__input"
        no-label-float
        placeholder="${this.label}..."
        @click=${t=>t.stopPropagation()}
      >
      </ha-textfield>
```
Удалил файл _/config/www/community/mini-media-player/mini-media-player-bundle.js.gz_
Затем перезагрузил Home Assistant, почистил кэш приложения в андроиде и в браузере компьютера.

Надеюсь, это исправление внесут таки в очередной релиз **Mini Media Player**.
