### ISSUE TITLE
Unsupported media: question

### ISSUE THREAD

**Issue by raskariaka** [AlexxIT/YandexStation#41]
Logger: custom_components.yandex_station.media_player
Source: custom_components/yandex_station/media_player.py:444
Integration: YandexStation (documentation)
First occurred: 13:54:29 (1 occurrences)
Last logged: 13:54:29

Unsupported media: question

**Comment by AlexxIT** [comment]
Или облачный режим вместо локального на колонке. Или старая версия компонента.

**Comment by 2053950** [comment]
Добрый день! Та же проблема. Яндекс большая станция. Компонент Yandex.Station 2.3.0  Как включить локальный режим?

**Comment by 2053950** [comment]
> Добрый день! Та же проблема. Яндекс большая станция. Компонент Yandex.Station 2.3.0 Как включить локальный режим?
При этом это происходит только при триггере из телеграмм. Управление колонкой из lovelace работает

**Comment by AlexxIT** [comment]
question работает только на локальных колонках. Возможно проблемы с мультикастом в локальной сети, раз локальный режим не включился. Можно прописать у колонки IP-адрес в конфиге
