### ISSUE TITLE
Не отображается статус колонки при воспроизведении.

### ISSUE THREAD

**Issue by desolaris** [AlexxIT/YandexStation#413]
Нет отображения состояния устройства ( обложки/название трека) 
Музыка играет, управлять ей можно, громкость меняется, а карточка ничего не отображает. Ни mini-media-player, ни стандартная
Перезапуск интеграции результата не дает.
Версия HA 2023.11.2
Интеграция v3.12.5

Нет отображения только для Мини 2 с часами
на Мини - ОК
на Лайт - ОК

**Comment by AlexxIT** [comment]
Перезагрузите колонку

**Comment by desolaris** [comment]
Заработало, не думал что проблема может быть в колонке. Спасибо!
