### ISSUE TITLE
Получение идентификатора устройства для ответа на него в intent

### ISSUE THREAD

**Issue by krom** [AlexxIT/YandexStation#42]
Хотелось бы иметь возможность задать вопрос Алисе и получить на него динамический ответ
Например:

- Алиса, какая температура на сенсоре
- action: trigger: yandex_intent
- action: call_service: tts entity_id: {{trigger.id}} message: сейчас температура {%states('sensor')%} градусов

В идеале вообще вызывать сервис типа `intent_replay`, который бы отвечал обратно.

Но и в первом случае иметь информацию о колонке тоже было бы полезно, например, для определения комнаты, в которой была произнесена команда.

Но судя по тому, что вообще функционал `indent` реализован через ~жопу~ громкость, то можно на это особо не надеяться на это до тех пор, пока яндекс не прикрутит полноценную апишку.

**Comment by AlexxIT** [comment]
Такое вот решение:
https://github.com/AlexxIT/YandexDialogs
