### ISSUE TITLE
Количество запросов с серверу.

### ISSUE THREAD

**Issue by kolek15** [AlexxIT/YandexStation#420]
Добрый день. Подключил интеграцию умного дома HitePro в яндекс. В итоге разработчики HitePro написали мне следующее:
Api умного дома яндекса умеет в запрос всех устройств сразу. Модуль сейчас делает циклические запросы отдельно каждого устройства в короткий промежуток времени, из-за этого могут накладываться санкции на количество таких запросов.

Т.е. у меня автоматом блокируется доступ к интеграции HitePro из за частых запросов. Можно ли как-то увеличить интервал этих запросов?

**Comment by AlexxIT** [comment]
Не очень понимаю, при чём тут эта интеграция

**Comment by kolek15** [comment]
да вот я тоже не совсем понял, пришлось пока из интеграции убрать именно устройства HitePro

**Comment by kolek15** [comment]
Вот еще они ответили:
Мы не знаем как точно работает интеграция, но только через нее идут запросы в яндекс, а из него к нам и их слишком много. Мы можем точно утверждать, что запросы идут именно от интеграции, ТП яндекса это подтверждает.

В яндексе есть запрос сразу всех устройств, а не каждого отдельно, что сократит количество запросов в сотни раз.

Сейчас идет запрос на состояние каждого конкретного устройства

**Comment by AlexxIT** [comment]
Я понял. Переделывать данную архитектуру в ближайшее время не планируется.
