### ISSUE TITLE
Пропал увлажнитель после обновления до НА Core 2024.1.0

### ISSUE THREAD

**Issue by misha1183** [AlexxIT/YandexStation#429]
После обновления до НА Core 2024.1.0 пропал увлажнитель, был проброшен из Яндекса в HA, но датчики от него остались, температура и влажность.

**Comment by JaybeRF** [comment]
То е самое

**Comment by misha1183** [comment]
НА Core 2024.1.1 исправило эту проблему

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.0
