### ISSUE TITLE
LG XBOOM

### ISSUE THREAD

**Issue by uPagge** [AlexxIT/YandexStation#43]
Привет

Я владею LG XBOOM и яндекс мини. Удачно смог запустить локальный режим на мини.

Локальный режим на XBOOM не запускается, могу помочь потестировать, если есть желание допилить функционал для LG

**Comment by uPagge** [comment]
И офтоп вопрос, можно ли с интеграцией в спотифай прокинуть так музыку на яндекс мини например

**Comment by AlexxIT** [comment]
Привет. Это Яндексу нужно допиливать, не мне.

Нет известного способа запустить на мини что-то помимо Яндекс музыки.

**Comment by uPagge** [comment]
Эх, ну ладно, очень жаль, звук из нее хороший идет, обидно, что не поддерживается и ничего с этим не сделать

**Comment by uPagge** [comment]
> Нет известного способа запустить на мини что-то помимо Яндекс музыки.

Я думал можно направить поток из спотифая на любое подключенное звуковое устройство к HA

![изображение](https://user-images.githubusercontent.com/40397740/89108854-ab98bd80-d444-11ea-8a58-98cea51bba89.png)
