### ISSUE TITLE
После обновления до НА Core 2024.1.0 пропали некоторые устройства

### ISSUE THREAD

**Issue by kostik8922** [AlexxIT/YandexStation#434]
Три телевизора добавленные в алису через ик пульт пропали после обновления 
yandex_station:
  include:
  - Чайник
  - Кондиционер на кухне
  - Кондиционер в зале
  - Кондиционер в детской
  - Лампочка 1
  - Лампочка 2
  - Лампочка 3
  - Лампочка 4
  - Лампочка 5
  - Лампочка 6
  - Телевизор детская
  - Телевизор зал
  - Телевизор кухня

**Comment by IndeecDen** [comment]
да, кондиционер остался, пульты телевизора пропали

**Comment by ser3ga** [comment]
Та же самая проблема, кондиционер остался, телевизор пропал

**Comment by grizzlylife** [comment]
+1, три пульта пропали

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.0
