### ISSUE TITLE
Проблемы в работе ИК телевизора на версии v3.13.0

### ISSUE THREAD

**Issue by MikhailTeddy** [AlexxIT/YandexStation#436]
Большое спасибо за новое обновление, которое полноценно работает в новых версиях HA!
Описанное в заголовке возможно не проблема, а фича. Но так как ИК управление не имеет обратной связи, то эта "фича" превращается в проблему.
Карточка телевизора стандартно подставляемая, в прошлых версиях не являлась переключателем "вкл. выкл.", и все кнопки всегда были на месте и на карточке не писалось состояние - включено, выключено.
Как это можно обойти?

**Comment by AlexxIT** [comment]
Скачайте диагностику устройства из ХА

**Comment by MikhailTeddy** [comment]
"data": {
    "device": {
      "id": "........-....-....-....-............",
      "name": "\u0422\u0435\u043b\u0435\u0432\u0438\u0437\u043e\u0440 \u0432 \u0434\u0435\u0442\u0441\u043a\u043e\u0439",
      "type": "devices.types.media_device.tv",
      "icon_url": "https://avatars.mds.yandex.net/get-iot/icons-devices-devices.types.media_device.tv.svg/orig",
      "capabilities": [
        {
          "reportable": false,
          "retrievable": false,
          "type": "devices.capabilities.on_off",
          "state": null,
          "parameters": {
            "split": false
          }
        },
        {
          "reportable": false,
          "retrievable": false,
          "type": "devices.capabilities.range",
          "state": null,
          "parameters": {
            "instance": "volume",
            "name": "\u0433\u0440\u043e\u043c\u043a\u043e\u0441\u0442\u044c",
            "unit": "",
            "random_access": false,
            "looped": false
          }
        },
        {
          "reportable": false,
          "retrievable": false,
          "type": "devices.capabilities.range",
          "state": null,
          "parameters": {
            "instance": "channel",
            "name": "\u043a\u0430\u043d\u0430\u043b",
            "unit": "",
            "random_access": true,
            "looped": true
          }
        },
        {
          "reportable": false,
          "retrievable": false,
          "type": "devices.capabilities.mode",
          "state": null,
          "parameters": {
            "instance": "input_source",
            "name": "\u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u0441\u0438\u0433\u043d\u0430\u043b\u0430",
            "modes": [
              {
                "value": "one",
                "name": "\u041e\u0434\u0438\u043d"
              },
              {
                "value": "two",
                "name": "\u0414\u0432\u0430"
              },
              {
                "value": "three",
                "name": "\u0422\u0440\u0438"
              },
              {
                "value": "four",
                "name": "\u0427\u0435\u0442\u044b\u0440\u0435"
              },
              {
                "value": "five",
                "name": "\u041f\u044f\u0442\u044c"
              },
              {
                "value": "six",
                "name": "\u0428\u0435\u0441\u0442\u044c"
              }
            ]
          }
        },
        {
          "reportable": false,
          "retrievable": false,
          "type": "devices.capabilities.toggle",
          "state": null,
          "parameters": {
            "instance": "mute",
            "name": "\u0431\u0435\u0437 \u0437\u0432\u0443\u043a\u0430"
          }
        },
        {
          "reportable": false,
          "retrievable": false,
          "type": "devices.capabilities.toggle",
          "state": null,
          "parameters": {
            "instance": "pause",
            "name": "\u043f\u0430\u0443\u0437\u0430"
          }
        }
      ],
      "properties": [],
      "item_type": "device",
      "skill_id": "T",
      "room_name": "\u0414\u0435\u0442\u0441\u043a\u0430\u044f",
      "state": "online",
      "created": "2022-12-17T08:23:26Z",
      "parameters": {
        "device_info": {
          "manufacturer": "Yandex",
          "model": "YNDX-0006"
        }
      }
    }
  }

**Comment by kostik8922** [comment]
таже проблема

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.1

**Comment by MikhailTeddy** [comment]
Ура!
В новой версии v3.13.1 карточка телевизора теперь в статусе "бездействие" и кнопки управления всегда на месте!
Спасибо!!!
