### ISSUE TITLE
Не получает температуру со стороннего датчика (кондиционер) при старте интеграции

### ISSUE THREAD

**Issue by lmorningstar116** [AlexxIT/YandexStation#437]
При старте интеграции нет отображения текущей температуры, если используется сторонний датчик.
После включения/выключения показания появляются.

**Comment by AlexxIT** [comment]
Данные датчика обновляются при обновлении любых параметров самого кондиционера. Проверьте, что это работает

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.1
