### ISSUE TITLE
Поддержка сенсоров с типом event

### ISSUE THREAD

**Issue by denis-samsonov** [AlexxIT/YandexStation#439]
Уровень заряда или освещенности как сенсоры определяются, а сенсор события нет

**Comment by AlexxIT** [comment]
События не поддерживаются. Это проблемные датчики, которые не имеют состояния и требуют другой подход

**Comment by denis-samsonov** [comment]
При просмотре диагностических данных, датчики события определяются автоматически по положено.

 "capabilities": [],
      "properties": [
        {
          "type": "devices.properties.float",
          "retrievable": false,
          "reportable": true,
          "parameters": {
            "instance": "battery_level",
            "name": "\u0443\u0440\u043e\u0432\u0435\u043d\u044c \u0437\u0430\u0440\u044f\u0434\u0430",
            "unit": "unit.percent"
          },
          "state": {
            "percent": 100,
            "status": "normal",
            "value": 100
          },
          "state_changed_at": "2023-11-27T14:03:51Z",
          "last_updated": "2024-01-15T03:34:20Z"
        },
        {
          "type": "devices.properties.event",
          "retrievable": false,
          "reportable": true,
          "parameters": {
            "instance": "motion",
            "name": "\u0434\u0432\u0438\u0436\u0435\u043d\u0438\u0435",
            "events": [
              {
                "value": "detected",
                "name": "\u0434\u0432\u0438\u0436\u0435\u043d\u0438\u0435"
              },
              {
                "value": "not_detected_within_1m",
                "name": "\u043d\u0435\u0442 \u0434\u0432\u0438\u0436\u0435\u043d\u0438\u044f \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u044e\u044e \u043c\u0438\u043d\u0443\u0442\u0443"
              },
              {
                "value": "not_detected_within_2m",
                "name": "\u043d\u0435\u0442 \u0434\u0432\u0438\u0436\u0435\u043d\u0438\u044f \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0435 2 \u043c\u0438\u043d\u0443\u0442\u044b"
              },
              {
                "value": "not_detected_within_5m",
                "name": "\u043d\u0435\u0442 \u0434\u0432\u0438\u0436\u0435\u043d\u0438\u044f \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0435 5 \u043c\u0438\u043d\u0443\u0442"
              },
              {
                "value": "not_detected_within_10m",
                "name": "\u043d\u0435\u0442 \u0434\u0432\u0438\u0436\u0435\u043d\u0438\u044f \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0435 10 \u043c\u0438\u043d\u0443\u0442"
              }
            ]
          },
          "state": {
            "instance": "motion",
            "status": "normal",
            "value": "detected"
          },

**Comment by AlexxIT** [comment]
Добавить их не проблема. Только боюсь пользоваться ими будет невозможно

**Comment by notabene01** [comment]
Я верно понимаю, что сюда относятся, например, дверные звонки?
Было бы удобно интегрировать в Home Assistant событие от нажатия кнопки на Aqara G4 более адекватным способом.
<details>
  <summary>Как сделано сейчас...</summary>
В Home Assistant создан <i>input_boolean.doorbell_button</i>, прокинут в HomeKit.
Включен режим энергосбережения на G4 (он тогда отключает "датчик движения", остаётся только нажатие кнопки).
В Apple Home (куда добавлен G4), настроена автоматизация по "обнаружению движения", которая фактически срабатывает теперь по нажатию кнопки. Автоматизация включает тот самый `input_boolean` и выключает его через минуту. 
По событию его включения в Home Assistant триггерим всё что надо.

<img src="https://github.com/AlexxIT/YandexStation/assets/129467976/b3cac923-a71b-49b3-851d-1c24bd383086" width="300">

</details>

**Comment by AlexxIT** [comment]
Да. Звонки тоже относятся. Но Aqara проще и лучше добавлять как раз через HomeKit. Это локальная и довольно надёжная интеграция. Плюс у меня были пока безуспешные попытки достать уведомление по конкретному лицу, которое обнаружили камеры Aqara

**Comment by AlexxIT** [comment]
Я добавил поддержку событий. Будут в следующей версии. Но, подозреваю, ими невозможно будет пользоваться потому что события и состояния это разные вещи.

**Comment by notabene01** [comment]
А можно же событие (в случае, напрмиер, кнопок) интерпретировать как кратковременное переключение состояния бинарного сенсора на 'on'? Видеть его и не нужно, а вот стриггериться уже будет возможно.
А вообще, почему бы не пробросить события именно как события?
Сущности для этого варианта вообще не нужны, как я понимаю.

**Comment by AlexxIT** [comment]
Кнопка, движение, открытие - в Яндексе всё события. Ещё и со статусом последнего значения.

Для кнопки не нужно срабатывать при старте ХА, но нужно срабатывать в процессе работы.

Для открытия вообще нужен просто бинарный сенсор.

Для движения вообще сложная история. Потому что старые датчики шлют только давление. А состояние без движения разные платформы обрабатывают самостоятельно. Как тут действует Яндекс - я не знаю.

С другими сенсорами тоже приключения.

**Comment by notabene01** [comment]
Может, стоит рассмотреть возможность проброса этих событий именно как [события](https://www.home-assistant.io/docs/configuration/events/)?
Тогда, вместо state-триггера датичка движения `to: 'on'` будет событие типа `yandex_event`, а в данных события - ID устройства, instance (motion) и value (detected).
Я когда-то использовал интеграцию [deCONZ](https://github.com/home-assistant/core/blob/dev/homeassistant/components/deconz/deconz_event.py) и у них многое было завязано на события.
А потом они, кажется, накрутили поверх событий [device triggers](https://developers.home-assistant.io/docs/device_automation_trigger/). И понизили тем самым порог использования.

![](https://user-images.githubusercontent.com/43333120/146923708-4af7a38a-60bd-458c-9649-8d0483b1f205.png)

**Comment by notabene01** [comment]
Кажется, именно об этом Вы выше и писали - будет в следующей версии. И да. 
Это не слишком удобно для выведения в dashboard - придется плодить вспомогательные (input/template) сущности, создавая их вручную. Но уже даст возможность триггериться по ранее недоступным событиям.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.1
