### ISSUE TITLE
Алиса в телеграм многопользовательский режим

### ISSUE THREAD

**Issue by uPagge** [AlexxIT/YandexStation#44]
А есть воможность сделать так, чтобы с алисой могли в телеге общаться несоклько человек и она отвечала конкретно тому, кто ее спрашивал. Пытался сделать через 

data_template:
        target: '{{ trigger.event.data.user_id }}'

но этот вариант не взлетел

**Comment by AlexxIT** [comment]
Добавил в последнем релизе
