### ISSUE TITLE
Проблемы с кондиционером и климатическими датчиками

### ISSUE THREAD

**Issue by Leviann** [AlexxIT/YandexStation#442]
После последнего обновления стало невозможно менять режимы HVAC на кондиционере, подключенным через инфракрасный хаб Яндекса (хотя статус отображается корректно, если через УДЯ менять режимы).
Так же полностью пропали из доступа климатические датчики и датчик двери/окна от Aqara, хотя в импорте они были указаны и работали до последнего обновления.

[config_entry-yandex_station-50b939c30d9a114415335266aa53b90f.json.txt](https://github.com/AlexxIT/YandexStation/files/13946921/config_entry-yandex_station-50b939c30d9a114415335266aa53b90f.json.txt)
[home-assistant_yandex_station_2024-01-16T07-52-16.745Z.log](https://github.com/AlexxIT/YandexStation/files/13946924/home-assistant_yandex_station_2024-01-16T07-52-16.745Z.log)

**Comment by alexanderznamensky** [comment]
в дополнение: команды кондиционеру через ИК-пульт передаются корректно. В HA не возвращается статус, поэтому кондиционер выглядит так:
![image](https://github.com/AlexxIT/YandexStation/assets/65254375/7636b245-1ba5-48d4-a359-cbc31d572afc)
и, как следствие, при выключении его из НА, он не выключается.

Но если зайти в quasar и обновить страницу, то статус сразу прилетает в HA:
![image](https://github.com/AlexxIT/YandexStation/assets/65254375/a29d61f9-79bc-4d64-97ba-730c2300ec2c)

Если управлять кондеем из приложения Яндекс (или из qusaar, что одно и тоже), то в НА все отображается корректно.

**Comment by AlexxIT** [comment]
Да, тоже заметил, когда Квазар открыт - состояние кондиционера обновляется норм. Сперва думал показалось. Видимо нужно реализовать принудительный запрос нового состояния. Какой-то локальный баг реализации ИК пульта.

**Comment by alexanderznamensky** [comment]
в моем случае открытого Квазара не достаточно - нужно принудительно обновлять страницу (F5) или заходить в сам кондиционер на Квазаре

**Comment by KirillShzzzzzz** [comment]
Кондиционер подключени к УДЯ по wifi, проброшен в ХА с  " capabilities: [ "program", "temperature", "fan_speed", "thermostat" ]", версии Yandexstation 3.13.1 и ХА 2024.1.3.
Не работает управление программами "Не удалось вызвать службу climate/set_hvac_mode. 'program'"
Невозможно из ХА включить кондиционер (вообще нет реакции), но выключение той же кнопкой работает.
После перезагрузки ХА все недоступно пока не будет действия в УДЯ

**Comment by AlexxIT** [comment]
Программы поправлены в мастер версии

**Comment by alexanderznamensky** [comment]
Алексей, все работает! Спасибо Вам большое за Ваш труд!

**Comment by alexanderznamensky** [comment]
В мастере уже есть все фиксы, в том числе и кондиционеров (при управлении через ИК-пульт).

**Comment by AlexxIT** [comment]
Должно быть поправлено в прошлом релизе
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.3

**Comment by popstas** [comment]
Спрошу здесь, у меня вроде похожий случай: чайник в январе перестал обновлять температуру.

Я понял, что это можно поправить ручным вызовом `homeassistant.update_entity`, это работает.

Вопрос в том, как часто это можно делать без последствий? Я поставил раз в 10 секунд, но, возможно, стоит увеличить до 60 секунд.

**Comment by AlexxIT** [comment]
Стоит конечно увеличить. Можно из обновлений исключить ночное время. Всё в ваших руках
