### ISSUE TITLE
Как на счет интеграции ChatGPT + Yandex

### ISSUE THREAD

**Issue by timoff-timon** [AlexxIT/YandexStation#449]
Добрый день.
Сейчас уже есть интеграция ChatGPT в HA, в формате чата. А вы не планируете ее связать и интегрировать с колонками Yandex, что бы голосом можно было вести диалог через Yandex колонку, а ответы получать от ChatGPT? Помимо этого можно будет и управлять через ChatGPT приборами в доме. Это уже совсем другой уровень экспириенса, управления домом ну и ведение диалогов с ChatGPT, будет куда увлекательнее чем с Yandex. 
Спасибо.

**Comment by AlexxIT** [comment]
Это можно сделать через https://github.com/AlexxIT/YandexDialogs
