### ISSUE TITLE
Перестали работать все виды TTS

### ISSUE THREAD

**Issue by BoOmka** [AlexxIT/YandexStation#45]
При использовании любого из трёх вариантов TTS колонка молчит. При этом возможность управлять музыкой и громкостью сохраняется (по локальному протоколу).
Проверено на двух Яндекс Мини.

Я заметил, что интерфейс сценариев в Квазаре слегка изменился, может, и в апи изменения какие-то произошли? Однако это не объяснит нерабочий TTS по локальному протоколу.

В логах ошибок нет, только штатные дебаг-выводы.

**Comment by AlexxIT** [comment]
Да, API у Яндекса поменялись. Вечером поправлю

**Comment by AlexeyHimki** [comment]
Да, тоже перестало все работать. Irbis через облако

**Comment by AlexxIT** [comment]
Да, в 2.2.7 всё ОК :)
