### ISSUE TITLE
Ошибка в HA при попытке выполнения "update_scenario"

### ISSUE THREAD

**Issue by g0nschik** [AlexxIT/YandexStation#450]
Возникает ошибка, соответственно сброс не работает, и активация голосом срабатывает только однократно.

<img width="400" alt="123" src="https://github.com/AlexxIT/YandexStation/assets/157726885/77eaebce-b0b1-449b-9c01-8f57653c1b34">

YandexStation обновлена до последней версии.

**Comment by AlexxIT** [comment]
Так нужно смотреть подробности ошибки в логе

**Comment by AlexxIT** [comment]
Видимо подробностей не будет
