### ISSUE TITLE
Можно ли через автоматизацию запустить список любимых песен?

### ISSUE THREAD

**Issue by andrey170183** [AlexxIT/YandexStation#458]
Здравствуйте

Можно ли через автоматизацию запустить список любимых песен?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation#%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4-%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D0%B5%D0%B9
