### ISSUE TITLE
Methods without setting the proper ClimateEntityFeature

### ISSUE THREAD

**Issue by avbor** [AlexxIT/YandexStation#459]
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Климат ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 16:27:06 (1 occurrences)
Last logged: 16:27:06

Entity None (<class 'custom_components.yandex_station.climate.YandexClimate'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/AlexxIT/YandexStation/issues

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.14.0
