### ISSUE TITLE
hass..agent

### ISSUE THREAD

**Issue by ops244** [AlexxIT/YandexStation#460]
привет, перестала работать команда "выключи компьютер" через hass.agent
https://github.com/hass-agent/HASS.Agent
не работает только голосом (но при этом делает вид, что выполнила команду, звук издает), при этом в самом home assistant работает и в приложении умный дом яндекса вручную работает

**Comment by stuffmsksu** [comment]
Выключает без ошибок

чт, 15 февр. 2024 г., 18:50 ops244 ***@***.***>:
