### ISSUE TITLE
 устройство сообщает что оно этого не умеет

### ISSUE THREAD

**Issue by Ptiolerwud** [AlexxIT/YandexStation#463]
После отправки голосовой команды "Сделай громче на 0" колонка сперва сообщает фразу " устройство сообщает что оно этого не умеет" а после этого выполняет сценарий. Если в сценарии присутствует голосовой ответ, то колонка сперва говорит " устройство сообща..." а после сразу произносит ответ поступающий с ХА
Core 2024.2.3
Supervisor 2024.02.0

**Comment by AlexxIT** [comment]
Новая фраза - "ничего не делай"
