### ISSUE TITLE
429 status, Too Many Requests

### ISSUE THREAD

**Issue by vlad36N** [AlexxIT/YandexStation#468]
Core 2024.2.5
Supervisor 2024.02.1
Operating System 12.0
Пользовательский интерфейс 20240207.1

Эта ошибка возникла в пользовательской интеграции.

Logger: custom_components.yandex_station.core.yandex_session
Source: custom_components/yandex_station/core/yandex_session.py:512
Integration: Yandex.Station (documentation, issues)
First occurred: 3 марта 2024 г. в 06:22:21 (**197** occurrences)
Last logged: 00:28:55

https://quasar.yandex.ru/get_device_config return 429 status

**Comment by EvgenyBash** [comment]
Подтверждаю.

Эта ошибка возникла в пользовательской интеграции.

Logger: custom_components.yandex_station.core.yandex_session
Source: custom_components/yandex_station/core/yandex_session.py:512
Integration: Yandex.Station (documentation, issues)
First occurred: 6 марта 2024 г. в 22:33:28 (63 occurrences)
Last logged: 03:02:29

https://quasar.yandex.ru/get_device_config return 429 status
