### ISSUE TITLE
Создать автоматизацию  с TTS в HA

### ISSUE THREAD

**Issue by madspeed** [AlexxIT/YandexStation#470]
Добрый день!
Подскажите как правильно создать автоматизацию по событию в HA:
Если:
-срабатывает датчик
То: 
 Если: Колонка проигрывает медиа
 То: Поставить на паузу, Проиграть TTS на заданной громкости, продолжить воспроизведение на той громкости, которая была изначально (основная проблема???)
 Если: Колонка не проигрывает медиа
 То: Проиграть TTS на заданной громкости, вернуться в предыдущее состояние

Сейчас при проигрывании TTS происходит так, что громкость увеличивается чуть раньше и уменьшается чуть позже, тоесть 1 секунду до фразы и 1 секунду после фразы музыка играет очень громко.

**Comment by AlexxIT** [comment]
Общие вопросы по ХА лучше задавать в соотвествующих сообществах. Например, в Телеграм
