### ISSUE TITLE
Не добавляется репозиторий дополнений AlexxIT/YandexStation

### ISSUE THREAD

**Issue by A8536** [AlexxIT/YandexStation#474]
При добавлении появляется ошибка:
Unknown error, see supervisor logs

В логах:
Регистратор: homeassistant.components.hassio
Источник: components/hassio/websocket_api.py:138
интеграция: Home Assistant Supervisor ([документация](https://www.home-assistant.io/integrations/hassio), [проблемы](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
Первое сообщение: 02:21:54 (6 сообщений)
Последнее сообщение: 11:02:08

Failed to to call /store/repositories -

**Comment by DieMetRik** [comment]
А вы какой репозиторий куда пытаетесь добавить?

**Comment by AlexxIT** [comment]
Это не аддон
