### ISSUE TITLE
Fix sets invalid supported color modes

### ISSUE THREAD

**Issue by DParadoxus** [AlexxIT/YandexStation#475]
Регистратор: homeassistant.components.light
Источник: components/light/__init__.py:1165
интеграция: Освещение (документация, проблемы)
Первое сообщение: 15:35:44 (6 сообщений)
Последнее сообщение: 15:35:44

None (<class 'custom_components.yandex_station.light.YandexLight'>) sets invalid supported color modes {<ColorMode.HS: 'hs'>, <ColorMode.BRIGHTNESS: 'brightness'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/AlexxIT/YandexStation/issues

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.14.0
