### ISSUE TITLE
Не работает локальное управл

### ISSUE THREAD

**Issue by mike02spb** [AlexxIT/YandexStation#48]
Добрый день! Почему-то перестало нормально работать локальное упр на всех колонках (2 мини и одна станция)
Сначала неск дней локалка (обложки и обратная связь) работала на одной мини, а на второй и на станции не работало, а сегодня локалка стала на второй мини, а на первой перестало. На станции также не работает. Подскажите, в чем может быть причина? Спасибо большое!

**Comment by mike02spb** [comment]
Перестановка интеграции помогла.

**Comment by AlexxIT** [comment]
В документации написано, почему могут быть проблемы с локальным управлением
