### ISSUE TITLE
Не работает удаление из списка покупок

### ISSUE THREAD

**Issue by Vinndimon** [AlexxIT/YandexStation#482]
@AlexxIT спасибо за апдейт!

Синхронизация заработала, но только частично. Если в HA отметить пункт выполненным или удалить, при синхронизации Алиса попробует удалить его у себя, но у неё не получится. В итоге удалённый пункт добавится обратно в HA.

_Originally posted by @Vinndimon in https://github.com/AlexxIT/YandexStation/issues/471#issuecomment-2027061797_

**Comment by AlexxIT** [comment]
Поправил в мастере. Видимо с приходом YandexGPT поменялись фразы для работы со списком покупок.

**Comment by Vinndimon** [comment]
@AlexxIT установил мастер. Исправление помогло, спасибо!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.14.0

**Comment by Glip** [comment]
Наблюдаю проблему в v3.14.0 и v3.14.1.
Изначально тестировал Бетой алисы, пару часов назад отключил - проблема сохранилась.
