### ISSUE TITLE
Mp3 файл для MPD не содержит metadata

### ISSUE THREAD

**Issue by Kotgoth** [AlexxIT/YandexStation#486]
Файл, передаваемый на mpd (с именем типа 013412d6312739481248caa6e6a3d082.mp3) не содержит metadata.
Это видно в карточке mpd или при открытии файла локально любым плеером (AIMP, например).

К примеру, произвольный локальный файл с metadata:
![image](https://github.com/AlexxIT/YandexStation/assets/49398621/560ad447-0e76-4b39-99f5-80f0f74e75aa)

Файл от YandexStation:
![image](https://github.com/AlexxIT/YandexStation/assets/49398621/879bfeda-d9db-4dee-be2e-7888794d9023)

**Comment by AlexxIT** [comment]
Не содержит. В облаке Яндекса у музыки нет метаданных внутри файлов
