### ISSUE TITLE
В новой версии интергации сломано отображение автора в карточке медиаплеера.

### ISSUE THREAD

**Issue by QAstron** [AlexxIT/YandexStation#494]
Собственно сабж. После обновления Yandex.Station до версии 3.15.0 из всех стандартных карточек медиаплееров lovelace, относящихся к яндекс станциям пропало отображение названия музыкальной группы. Теперь пишется только название трека. Мне такое категорически не нравится, пришлось откатываться на предыдущую версию. Исправьте, пожалуйста, как было.

**Comment by AlexxIT** [comment]
Покажите атрибуты медиаплеера с проблемой

**Comment by QAstron** [comment]
![Yandex station 3 14 1](https://github.com/AlexxIT/YandexStation/assets/42620366/6148b4f0-ff37-4730-a0d4-7e73c575cbe2)
![Yandex station 3 15 0](https://github.com/AlexxIT/YandexStation/assets/42620366/1f193fba-1cac-474b-9c03-7b743ada3193)
Пожалуйста. Скриншот окна медиаплеера, на версии интеграции 3.14.1 отображается название группы/исполнителя и название трека, а на версии 3.15.0 только название трека. И так на карточках медиаплееров всех яндекс-станций. Настройки по умолчанию везде, ничего не трогал ни до, ни после обновления.

**Comment by AlexxIT** [comment]
Я просил атрибуты. Но уже не нужно. Разобрался
https://github.com/home-assistant/frontend/blob/25c702ad2bb1fb7d1f93a2237b2e0035e81d3dc4/src/data/media-player.ts#L237-L268

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.15.1
