### ISSUE TITLE
Не работает удаление из списка покупок

### ISSUE THREAD

**Issue by Glip** [AlexxIT/YandexStation#496]
Проблема аналогичная - https://github.com/AlexxIT/YandexStation/issues/482
Покупки добавляются в обе стороны, но после удаления в HA и запуска скрипта удаление покупок в яндексе не происходит.

**Comment by AlexxIT** [comment]
Не могу подтвердить. Всё работает. Возможно завязано на какие-то определённые элементы списка в Яндексе и/или ХА.

Могу повторить тест, если скажете, что именно есть в списках покупок
