### ISSUE TITLE
Группа устройств из ламп не управляется 404 

### ISSUE THREAD

**Issue by stdian** [AlexxIT/YandexStation#499]
Имеется группа устройств из ламп яндекса. При попытке управления получаю 404. 
![Снимок экрана 2024-04-29 в 01 55 19](https://github.com/AlexxIT/YandexStation/assets/15340847/ade0e3c4-31cd-40c7-a569-66f207f4c8ae)
![Снимок экрана 2024-04-29 в 01 55 24](https://github.com/AlexxIT/YandexStation/assets/15340847/7a5f974a-17e1-4f35-88b7-b55142beb1ba)

**Comment by DParadoxus** [comment]
Открою страшную тайну, Яндекс настолько "продвинут", что даже в их собственном приложении "умного" дома нельзя добавить в сценарий группу устройств. Есть подозрение, что поэтому и здесь не получится

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/pull/500

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.16.0
