### ISSUE TITLE
Из HACS исчез компонент - AlexxIT/YandexStation  

### ISSUE THREAD

**Issue by Securond** [AlexxIT/YandexStation#50]
Из HACS исчез компонент - AlexxIT/YandexStation . 
У кого вдруг перестало работать, устанавливаем из репозитория ручками.

**Comment by dmitry-korolev** [comment]
Ручками не работает — HACS отваливается напрочь.

**Comment by AlexxIT** [comment]
Официально в HACS компонента никогда не было. Он ставиться через "добавить репозиторий".
