### ISSUE TITLE
2024.5.0 Warnings

### ISSUE THREAD

**Issue by to4ko** [AlexxIT/YandexStation#502]
парочка ворнингов после перехода на 2024.5.0

`[homeassistant.helpers.typing] HomeAssistantType was used from yandex_station, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'yandex_station' custom integration`

`2024-05-02 13:54:33.064 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'yandex_station' accesses hass.helpers.intent. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from intent directly at custom_components/yandex_station/intent.py, line 24: hass.helpers.intent.async_register(handler), please create a bug report at https://github.com/AlexxIT/YandexStation/issues`

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.16.0
