### ISSUE TITLE
Управление кнопками навигации модуля

### ISSUE THREAD

**Issue by Nik768** [AlexxIT/YandexStation#504]
Добрый день. Подскажите, а есть ли способ как-то управлять кнопками навигации (вниз, влево, вправо, вверх, ок) яндекс модулем?
Проблема в том что у него bluetooth пульт и его команды не перехватить, по крайней мере без головной боли.
В android tv вроде это можно через remote как-то делать, всякие DPAD_LEFT, DPAD_RIGHT и т.д., приставки нет, не могу сказать как точно там это работает.
Может и для модуля как-то можно? Знаю что есть возможность через тв пульт по HDMI CEC управлять, но для этого телевизор должен быть включен, чего не хотелось бы.

**Comment by AlexxIT** [comment]
Любую команду можно послать текстом. Есть в документации
