### ISSUE TITLE
Утреннее шоу Алисы

### ISSUE THREAD

**Issue by Mepox91** [AlexxIT/YandexStation#505]
При отправке команды через HA: "включи утреннее шоу", "доброе утро" и тп, колонка начинает рассказывать какая она умная и сколько всего умеет в этом самом шоу и присылает уведомление для настройки этого шоу.  И так каждый раз, при этом настройки этого самого шоу в приложении удя сбрасываются. При запросе напрямую голосом или через родное приложение удя такого нет, там все отрабатывает корректно.

**Comment by stuffmsksu** [comment]
Это проблема не HA. Запуск прямо на колонке мини - "включи утреннее шоу" и
присылает ссылку для настройки. Данная шляпа последний месяц. Пинать
поддержку Алисы.

сб, 18 мая 2024 г., 09:33 Mepox91 ***@***.***>:

**Comment by AlexxIT** [comment]
Проблема не связана с компонентом
