### ISSUE TITLE
Не подключается интеграция Yandex Station / Не входит в профиль

### ISSUE THREAD

**Issue by K1zz9** [AlexxIT/YandexStation#506]
![image](https://github.com/AlexxIT/YandexStation/assets/151564475/54f6a6c8-7227-4fce-bf71-12a9ed93287c)
И так со всеми способами

**Comment by ClosedClose** [comment]
Заработало после прочтения этого тикета: https://github.com/AlexxIT/YandexStation/issues/452

1. Удалил существующую интеграцию (последней версии)
2. Закинул через терминал в custom_components версию 3.13.2 

`bash
wget https://github.com/AlexxIT/YandexStation/archive/refs/tags/v3.13.2.zip`
unzip v3.13.2
cp -r YandexStation-3.13.2/custom_components/yandex_station/ ./yandex_station`

3. Перезагрузка и повторное добавление в интеграции
4. Вход по cookie скопированные из https://yandex.ru/quasar
5. Готово

**Comment by yellow-sky** [comment]
Д

> Заработало после прочтения этого тикета: #452
> 
> 1. Удалил существующую интеграцию (последней версии)
> 2. Закинул через терминал в custom_components версию 3.13.2
> 
> `bash` `wget https://github.com/AlexxIT/YandexStation/archive/refs/tags/v3.13.2.zip` `unzip v3.13.2` `cp -r YandexStation-3.13.2/custom_components/yandex_station/ ./yandex_station`
> 
> 3. Перезагрузка и повторное добавление в интеграции
> 4. Вход по [cookie](https://chromewebstore.google.com/detail/copy-cookies/jcbpglbplpblnagieibnemmkiamekcdg) скопированные из https://yandex.ru/quasar
> 5. Готово

Этот метод теперь тоже не работает. Авторизация проходит, но дальше все падает с ошибкой:
`Регистратор: homeassistant.config_entries
Источник: config_entries.py:594
Первое сообщение: 23:30:07 (3 сообщений)
Последнее сообщение: 23:31:06

Error setting up entry nikulinea for yandex_station
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/__init__.py", line 145, in async_setup_entry
    await quasar.init()
  File "/config/custom_components/yandex_station/core/yandex_quasar.py", line 153, in init
    r = await self.session.get(f"{URL_V3_USER}/devices")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 467, in get
    return await self._request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 516, in _request
    return await self._request(method, url, retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 516, in _request
    return await self._request(method, url, retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_station/core/yandex_session.py", line 518, in _request
    raise Exception(f"{url} return {r.status} status")
Exception: https://iot.quasar.yandex.ru/m/v3/user/devices return 401 status`

**Comment by kadkin-a** [comment]
тоже не входит.  Говорит и токен невалидный.

**Comment by GlebOlden** [comment]
У меня точно такая же ошибка. Я авторизовался через QR-код, но интеграция не работает (выходит сообщение !Не удалось настроить). Моя версия Home Assistant 2024.5.4
![Снимок экрана_2024-07-05_08-23-20](https://github.com/AlexxIT/YandexStation/assets/44943930/5158a740-e14f-4880-a339-5b332ca48f8c)

**Comment by AlexxIT** [comment]
#354 #386
Обычно помогают повторные попытки в течении 1-2 дней.
Лучше всего работает авторизация через QR.
Не удалось настроить часто лечится перезагрузкой.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.21.0
