### ISSUE TITLE
пропал кондиционер в Хоме Ассистенте

### ISSUE THREAD

**Issue by kcinit32** [AlexxIT/YandexStation#516]

**Comment by kcinit32** [comment]
И больше не интегрируется хотя яндекс станция его видит

**Comment by AlexxIT** [comment]
В описании нет полезной информации для помощи с проблемой

**Comment by kcinit32** [comment]
Спасибо за отклик,но вроде появился кондиционер видимо в связи с обновлениями отлетал!
