### ISSUE TITLE
Не работает интеграция без ВПН 

### ISSUE THREAD

**Issue by cezzz674** [AlexxIT/YandexStation#518]
Добрый день перестала работать интеграция. Если включить впн для малины, заводится без проблем. Пробовал повторно авторизоваться,  точно так же работает до выключения впн. Есть ли способ прописать прокси? Или другой способ вылечить? Спасибо!

**Comment by KAPACb1988** [comment]
![Screenshot_20240704_195904_io homeassistant companion android](https://github.com/AlexxIT/YandexStation/assets/91968865/0abd229d-735d-4710-acaf-b58af5d5b8f1)
Я удалил интеграцию и добавил заново, торрент не могу аккаунт добавить.. прокат не знаю где прописывать.. можно ли исправить проблему 😯

**Comment by K0TlK** [comment]
Аналогичные сложности

**Comment by AlexxIT** [comment]
Прокси поддерживается, но очень давно не тестировалось
https://github.com/AlexxIT/YandexStation/releases/tag/v3.1.0

**Comment by cezzz674** [comment]
> Прокси поддерживается, но очень давно не тестировалось https://github.com/AlexxIT/YandexStation/releases/tag/v3.1.0

Добрый день, спасибо что ответили!  У меня это раньше работало вот  в таком формате  и проблем не было (забыл что прокси был, виноват :D) Но теперь, не работает, адрес проплачен, активен, дважды проверил. Поможете разобраться?
![image](https://github.com/user-attachments/assets/1908bae3-199c-4d1a-9523-0fa6d07ef27f)

**Comment by KAPACb1988** [comment]
У меня сейчас заработали яндекс.станции

**Comment by KAPACb1988** [comment]
Прокси не применял
