### ISSUE TITLE
Черный экран в Chromecast и недоступность регулятора громкости в карточке lovelace

### ISSUE THREAD

**Issue by Ivshin** [AlexxIT/YandexStation#525]
Сделал по readme карточку в lovelace, добавил в конфигурацию ХА источник звука (телевизор с chromecast). В итоге на телевизоре играет музыка, но на экране ничего нет, черный экран, при нажатии плей\стоп вылезает плеер. То есть даже не передаются обложки, так и должно быть? В карточке почему-то недоступна регулировка громкости

![image](https://github.com/user-attachments/assets/81c0a737-a9eb-46ed-b043-14d16bfb7234)

**Comment by AlexxIT** [comment]
Регулировки звука нет потому что колонка перешла в режим трансляции и отключила у себя звук. Этот написано в документации.

Обложки нет и черный экран - так и задумано. Универсальная реализация обложек и названий песен весьма трудоёмкая задача. Не стоит потраченного времени.
