### ISSUE TITLE
Не могу включить телевизор в автоматизации

### ISSUE THREAD

**Issue by Lexx725** [AlexxIT/YandexStation#526]
Пытаюсь а автоматизации сделать управление телеком (включение/выключение)
Через яндекс работает. 
Если в автоматизации выбрать устройство, телевизор, то в действиях пусто. Ничего нельзя сделать. То же самое для кондиционера работает нормально.

**Comment by AlexxIT** [comment]
Нужно глубже изучить ХА. Автоматизации можно писать с помощью вызова сервисов. Можно почитать документацию ХА или поспрашивать на форумах или чатах. Не связано с работой интеграции.
