### ISSUE TITLE
Можно ли получить в event: yandex_speaker ID пользователя зарегистрированного по голосу в алисе

### ISSUE THREAD

**Issue by vtimer** [AlexxIT/YandexStation#527]
Можно ли каким-то образом из евента понять кто говорит, если голос зарегистрирован в Алисе.
Судя по докам яндекса user_id это не то и вообще депрекейтед. 

event_type: yandex_speaker
data:
  instance: text_action
  value: Сделай громче на 0
  entity_id: media_player.yandex_station_....
  name: Стереопара
origin: LOCAL
time_fired: "2024-08-02T04:47:19.880654+00:00"
context:
  id: 01J48PKTT8SS04F8MB282SZ4ET
  parent_id: null
  user_id: null

**Comment by AlexxIT** [comment]
Нет. Яндекс не даёт такого функционала.
