### ISSUE TITLE
SLS Чайник не управляется из HA 

### ISSUE THREAD

**Issue by shostko** [AlexxIT/YandexStation#528]
почему-то чайник в HA получает только статус (вкл/выкл), управление не доступно. Хотя в самом яндексе чайник можно включить/выключить без проблем (голосом, приложением, через квазар).

![image](https://github.com/user-attachments/assets/a6f9501e-5008-460f-8d0f-c567ab626e83)
![image](https://github.com/user-attachments/assets/2f5a55cd-d6eb-4274-bb94-683c53859683)
![image](https://github.com/user-attachments/assets/c9f8546d-9430-46bd-8d36-5d942064f47f)

[yandex_station-01J3K7230ARJ12APDXSKQC8G6Q-Чайник-a9daec9f46a156054df6533bcd156ce0.json](https://github.com/user-attachments/files/16492218/yandex_station-01J3K7230ARJ12APDXSKQC8G6Q-.-a9daec9f46a156054df6533bcd156ce0.json)

(начало диалога: https://github.com/AlexxIT/YandexStation/issues/197#issuecomment-2266634970)

**Comment by AlexxIT** [comment]
Исправлено. Можно попробовать мастер версию

**Comment by shostko** [comment]
Подтверждаю, спасибо.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.16.0
