### ISSUE TITLE
Поддержка запуска синхронного воспроизведения медиа на нескольких колонках (мультирум)

### ISSUE THREAD

**Issue by tkmamedov** [AlexxIT/YandexStation#529]
Не хватает поддержки запуска синхронного воспроизведения медиа на нескольких колонках (мультирум).
Возможно эта возможность уже есть, но не удалось найти упоминаний в документации.

**Comment by AlexxIT** [comment]
На колонку можно послать любую текстовую команду, аналогично, как это делается голосом.

**Comment by tkmamedov** [comment]
Действительно, спасибо!
Попробую такой подход.
