### ISSUE TITLE
Unsupported url

### ISSUE THREAD

**Issue by allmoney** [AlexxIT/YandexStation#53]
Создал плейлист. Но не играет. В логах пишет:
2020-08-31 12:28:49 WARNING (MainThread) [custom_components.yandex_station.media_player] Unsupported url: https://music.yandex.ru/users/dmitry.mukhach/playlists/1012

Что не так?

**Comment by allmoney** [comment]
Log Details (WARNING)
Logger: custom_components.yandex_station.media_player
Source: custom_components/yandex_station/media_player.py:467
Integration: YandexStation (documentation)
First occurred: September 11, 2020, 11:03:08 AM (182 occurrences)
Last logged: 2:06:03 PM

**Unsupported media: xxx**

**Comment by AlexxIT** [comment]
Ссылки играются только в локальном режиме. Колонка могла не найтись локально. Можно попробовать перезагрузить роутер и после этого HA.

**Comment by pbo1992** [comment]
Доброго времени суток, подскажите пожалуйста почему я не могу отправить команду через плеер на станцию, так же алиса отказывается воспроизводить текст что я ввел там и выдает в логах:
Unsupported url: http://xxx.xxx.x.xxx:8123/api/tts_proxy/abfc17a32eed2493bec522f8554c6397e1369ba0_en-us_4130161143_cloud.mp3

**Comment by AlexxIT** [comment]
Читайте раздел readme - несколько TTS в конфиге

**Comment by allmoney** [comment]
> Ссылки играются только в локальном режиме. Колонка могла не найтись локально. Можно попробовать перезагрузить роутер и после этого HA.

Не получается... Кто-нибудь может проверить такой экшн:

  - service: media_player.play_media
    data_template:
      media_content_id: 'https://music.yandex.ru/album/4700979/track/45159225'
      media_content_type: 'audio/mp3'
    entity_id: media_player.yandex_station_ff98f029e311fda0037eaa65

Песню не играет... А если ссылку вида https://music.yandex.ru/artist/2611761 вставить, то всё ок, играет... Перезагрузка не помогает... В чём причина?..

**Comment by allmoney** [comment]
@AlexxIT поможете? Так и не работает ссылка на конкретную песню или свой плейлист... Ссылки на артистов без проблем.

**Comment by AlexxIT** [comment]
Проверил, песня из примера выше работает

**Comment by allmoney** [comment]
Заработало! Спасибо!!! И песня и плейлисты!
