### ISSUE TITLE
Опрос устройства из навыка?

### ISSUE THREAD

**Issue by temandroid** [AlexxIT/YandexStation#531]
Есть кондицинеры Haier подключенные к навыку Алисы EVO и проброшенные в HA, все хорошо, только статус кондиционера автоматически не обновляется, то есть если из Алисы включить кондиционер, она опрашивает и все ок, а если вручную с пульта или через само приложение что-то изменить, то УД и HA об этом ниичего не узнают, пока не попросишь сделать опрос, условно спросить, какая температура. 
Вот собственно и вопрос, есть ли возможность как-то вызывать опрос устройства из ha/nodered без участия самой колонки?
Я сделал костыль, по крону спрашиваю алису про каждый кондиционер, таким образом имея актуальную информацию в ha  и строю на этом автоматизацию, но это прям очень не правильно. 
PS в поддержку haier я написал о том, что неплохо было бы пушить обновления по триггеру события, но если они и прислушаются, то неизвестно когда сделают)

**Comment by AlexxIT** [comment]
```yaml
service: homeassistant.update_entity
target:
  entity_id: climate.hall_conditioner
```
