### ISSUE TITLE
Не работает после обновления HA 2024.8

### ISSUE THREAD

**Issue by grizzlylife** [AlexxIT/YandexStation#533]
Интеграция отваливается после обновления с 2024.7.4 на 2024.8.0, в том числе на 2024.8.1. 
Если откатить HA интеграция снова начинает работать, пробовал раз 10 в течении последних 4-х дней. 
Версия YandexStation 3.15.1.

![image](https://github.com/user-attachments/assets/4b651cf4-2f33-4020-83c4-88e6c99e61b6)

В журнале HA вижу:
```
Регистратор: custom_components.yandex_station.core.yandex_session
Источник: custom_components/yandex_station/core/yandex_session.py:411
Login with token error: {'status': 'error', 'errors': ['oauth_token.invalid']}
```
Изменить настройки так же не могу пишет:
`Не удалось загрузить мастер настройки: 500 Internal Server Error Server got itself in trouble`

В дебаг режиме вижу только следующее:
```
2024-08-12 09:52:01.203 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from yandex_station, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'yandex_station' custom integration
2024-08-12 09:52:12.526 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_session] Login in Yandex with token
2024-08-12 09:52:12.876 ERROR (MainThread) [custom_components.yandex_station.core.yandex_session] Login with token error: {'status': 'error', 'errors': ['oauth_token.invalid']}
```

В настройках интеграции под "Записи интеграции" появляется поле c добавлением авторизации, но с пустыми данными, если добавить новую авторизации по QR коду, HA сообщает, что все проходит успешно, перезагрузитесь, но интеграция так и не работает. 

![image](https://github.com/user-attachments/assets/09979c13-a875-4fe7-badf-7aab74cc1c49)

Переустановка интеграции не помогла, решение одно, приходится откатываться на 2024.7

**Comment by Eldellano** [comment]
Подтверждаю, описанная проблема имеет место быть.

**Comment by Anton-Volosatov** [comment]
Подтверждаю. обновился с с 2024.7.4  сразу на 2024.8.1.

**Comment by Anton-Volosatov** [comment]
Каким то чудом интеграция авторизовалась , ничего не обновлял. Деактивировал интеграцию, перезапустил HA, активировал и кликнул перезапустить в интеграции.

**Comment by grizzlylife** [comment]
Подтверждаю. Работает!!!
1. Обновился до 2024.8.1 (интеграция снова не активна)
2. Деактивирую интеграцию
3. Полностью перезагружаю хост HA
4. Активирую интеграцию (интеграция опять не активна)
5. Произвожу авторизацию по QR и работает!!

**Comment by grizzlylife** [comment]
Подтверждаю. Работает!!!
1. Обновился до 2024.8.1 (интеграция снова не активна)
2. Деактивирую интеграцию
3. Полностью перезагружаю хост HA
4. Активирую интеграцию (интеграция опять не активна)
5. Произвожу авторизацию по QR и работает!!

**Comment by voronind-com** [comment]
Мне не помогло. Сегодня внезапно отвалилось и не работает больше. Всё обновил, провал все варианты входа. В логах Bad request от яндекса.
