### ISSUE TITLE
Станция MAX YaOS X управление

### ISSUE THREAD

**Issue by EnviLine** [AlexxIT/YandexStation#535]
Добрый день, можно ли добавить управление новой ОС через HA?

1) Имитацию пульта яндекса, так как кастомные приложения не поддерживают управление голосом и media_player.play_media command не работает
2) Возможность запустить приложение со своими аргументами, например одной командой запустить браузер и открыть переданную ссылку

**Comment by AlexxIT** [comment]
Если это нельзя сделать средствами Яндекса - интеграция также не сможет это сделать.
