### ISSUE TITLE
Не прокидывается device с типом "подсветка"

### ISSUE THREAD

**Issue by maxcriser** [AlexxIT/YandexStation#537]
Для управления реле (aqara relay) через алису прокидываю в алису через aqara account->xiaomi account->yandex.
Добавил все устройства, но все подтянулось, кроме тех каналов реле, которые помечены в алисе как "подсветка"
<img width="553" alt="image" src="https://github.com/user-attachments/assets/2ee0124a-822f-4197-8576-9a5c054d44c4">
Было бы неплохо добавить хотя бы возможность включения/выключения для данного кейса, так как у самого лента не RGB, но указав тип "подсветка" в Алисе, удобно говорить "Включи только подсветки" и тд...

**Comment by AlexxIT** [comment]
Покажите диагностику интеграции (три точки в том же месте, откуда скрин).

**Comment by maxcriser** [comment]
@AlexxIT 
[config_entry-yandex_station-6769c95d736c927c1b07e542e587a8ad.json](https://github.com/user-attachments/files/16733677/config_entry-yandex_station-6769c95d736c927c1b07e542e587a8ad.json)

**Comment by AlexxIT** [comment]
В мастер версии поддерживается. Можете использовать её, пока не выйдет новый релиз.
