### ISSUE TITLE
Поддержка типов при добавлении устройств из УДЯ в HA

### ISSUE THREAD

**Issue by Lazemir** [AlexxIT/YandexStation#539]
Не добавляются устройства с типами:
- devices.types.light.ceiling
- devices.types.light.lamp
- devices.types.light.strip
- devices.types.ventilation
        
<img src="https://github.com/user-attachments/assets/8538b955-720c-43c3-ab63-64fc8338aabd" width=30% height=30%>

Если переключить тип устройства на devices.types.light или devices.types.switch, устройства добавляются. 

Если после добавления устройств сменить его тип назад на неподдерживаемый, устройство остаётся доступно до перезагрузки интеграции. 

На некоторых устройствах, например, на умной ленте Яндекса, поменять тип устройства вовсе невозможно.

**Comment by AlexxIT** [comment]
Лента поддерживается в мастер версии

**Comment by Lazemir** [comment]
Я установил интеграцию из [HACS](https://hacs.xyz/). 

Для того, чтобы лента заработала, мне необходимо установить интеграцию из ветки master этого репозитория?
Или же под "мастер версией" подразумевается что-то другое?

**Comment by AlexxIT** [comment]
Под мастер версией подразумевается ветка master

**Comment by AlexxIT** [comment]
Где вы взяли `devices.types.light.lamp`? Не вижу такого в документации

**Comment by AlexxIT** [comment]
Для `devices.types.ventilation` нужен пример описания устройства. Если у вас такое есть - можно скачать диагностику интеграции из ХА и найти его там.

**Comment by de-andrei** [comment]
Такая же проблема. Установка мастер версии не помогает

**Comment by de-andrei** [comment]
Добавил строку "devices.types.ventilation" в файл switch.py и все заработало :)
![Снимок экрана (72)](https://github.com/user-attachments/assets/5a49bd42-4b3e-4f11-9619-a7a6d7dc00a1)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.16.0
