### ISSUE TITLE
При громкости колонки больше 95 процентов "Сделай громче на 0" не работает как ожидалось

### ISSUE THREAD

**Issue by PeaceByPeace** [AlexxIT/YandexStation#540]
Сначала хочется поблагодарить за интеграцию, но есть одно но: "пустышка" в виде "Сделай громче на 0" работает только если громкость колонки установлена на 94 процента и ниже, а вот с 95 она начинает говорить, что громче уже некуда и тд и тп, есть ли другой вариант такой заглушки, а то все автоматизации выполняются локально и переносить датчики из HA в яндекс не хочется: просто нет необходимости

**Comment by AlexxIT** [comment]
Новая пустышка "ничего не делай" работает лучше.

**Comment by PeaceByPeace** [comment]
Действительно работает вот ровно так, как и хотелось, спасибо)))
