### ISSUE TITLE
Устройство остаётся недоступным

### ISSUE THREAD

**Issue by Obroten54** [AlexxIT/YandexStation#541]
Есть умная лампочка, когда питание к лампочке отключается на время, статус устройства в УДЯ штатно переходит в `status: "offline"`, в HA соответственно это "недоступно" (Unavailable). После того, как питание к лампочке восстанавливается, статус не обновляется и в HA оно всё ещё остаётся в статусе "недоступно" (Unavailable). Но в отличии от HA, в УДЯ устройству всё ещё можно попытаться дать команду после чего оно переходит в статус online, и становится доступным к управлению в HA. Но в HA устройству со статусом unavailable никакие команды дать нельзя. Получается, что устройство "оживить" можно только в УДЯ.
То же самое происходит время от времени с кондиционером, из-за чего автоматическое управление климатом в HA перестаёт работать. Приходится говорить Алисе включить кондиционер, чтобы та дала ему команду, тем самым обновив его статус на online.
Статус "недоступно" был добавлен в [v3.12.1](https://github.com/AlexxIT/YandexStation/releases/tag/v3.12.1). Как видно в некоторых случаях это вред, а не польза. Можно ли как-то запретить переводить некоторые (или все) устройства в unavailable?

**Comment by AlexxIT** [comment]
Я понял проблему. К сожалению, так работает ХА.
Пробовали отправить команду через вызов службы ХА? Возможно там нет проверки на недоступность.
Ещё попробуйте вызвать службу `homeassistant.update_entity`.

**Comment by Obroten54** [comment]
> Я понял проблему. К сожалению, так работает ХА. Пробовали отправить команду через вызов службы ХА? Возможно там нет проверки на недоступность. Ещё попробуйте вызвать службу `homeassistant.update_entity`.

Спасибо! Команды через вызов службы не проходят. Но вот `homeassistant.update_entity` лечит, устройство оживает.

**Comment by AlexxIT** [comment]
Эта команда принудительно получает состояние устройства у Яндекса. А он уже принудительно получает состояние у самой лампочки.
Можно добавить автоматизацию с обновлением по расписанию. Только не злоупотреблять с частотой опроса.
