### ISSUE TITLE
Интеграция групп устройств из УДЯ в ХА

### ISSUE THREAD

**Issue by baradetsky** [AlexxIT/YandexStation#544]
У меня две умные лампы в торшере объединены в группу "Торшер" в УДЯ. Пытаюсь их прокинуть в ХА, он их видит корректно, но взаимодействовать не хочет
![2024-09-15_22-35-17](https://github.com/user-attachments/assets/a3838fa4-37b9-413d-ba1a-8fca02b596bf)

**Comment by AlexxIT** [comment]
#499
