### ISSUE TITLE
Некорректное воспроизведение чисел.

### ISSUE THREAD

**Issue by ognevdv** [AlexxIT/YandexStation#549]
При попытке произнести 
media_content_id: Температура {{ states("sensor.yousensor") }} 
и значении sensor.yousensor с точкой, например 45.97, Алиса скажет:" Температура 45 часов 97 минут."

**Comment by AlexxIT** [comment]
Это к Яндексу вопросы. Возможно если вы добавите знак градуса - начнёт произносить нормально.
Если не поможет, можно попробовать интеграцию https://github.com/AlexxIT/MorphNumbers

**Comment by ognevdv** [comment]
Спасибо за ответ! Буду пробовать.

вт, 1 окт. 2024 г., 23:59 Alex X ***@***.***>:
