### ISSUE TITLE
Проигрывание медиа по ссылкам через облачное управление - работает

### ISSUE THREAD

**Issue by vzenrhen** [AlexxIT/YandexStation#55]
Спасибо за классный компонент!

В readme написано:

> Проигрывание медиа по ссылкам
> Поддерживается только на колонках (или модуле) с локальным управлением!

На самом деле через облачное управление тоже работает. Проверил на колонке от Irbis.

**Comment by AlexxIT** [comment]
Всё ещё работает? В Яндексе запретили спецсимволы недавно

**Comment by vzenrhen** [comment]
Проверил. Теперь не работает :(
