### ISSUE TITLE
Совместимость с Станция Дуо Макс

### ISSUE THREAD

**Issue by oxygen121** [AlexxIT/YandexStation#550]
Добрый день.

Приобрел Станция Дуо Макс, интеграция её видит как неизвестное устройство, отправить на станцию сообщение нельзя.
![image](https://github.com/user-attachments/assets/bda00d50-ec16-42ae-b484-9073f5bdd787)

**Comment by AlexxIT** [comment]
Покажите диагностику интеграции или диагностику этого устройства.

**Comment by oxygen121** [comment]
> Покажите диагностику интеграции или диагностику этого устройства.

Прошу прощенья, разобрался, всё работает.
