### ISSUE TITLE
Ошибки [deprecated] в логах

### ISSUE THREAD

**Issue by jekakmail** [AlexxIT/YandexStation#551]
Недавно заметил, что после перезагрузки в логах появились такие ошибки:

```
Регистратор: homeassistant.helpers.typing
Источник: helpers/deprecation.py:197
Первое сообщение: 15:30:30 (3 сообщений)
Последнее сообщение: 15:30:54

HomeAssistantType was used from yandex_station, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'yandex_station' custom integration
HomeAssistantType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'webrtc' custom integration
ServiceCallType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'webrtc' custom integration 
```

**Comment by alparo** [comment]
Добавлю еще вот это

`2024-10-02 18:52:28.960 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'yandex_station' accesses hass.helpers.intent. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from intent directly at custom_components/yandex_station/intent.py, line 24: hass.helpers.intent.async_register(handler), please create a bug report at https://github.com/AlexxIT/YandexStation/issues`

**Comment by AlexxIT** [comment]
#502
