### ISSUE TITLE
Добавить возможность сменить домен на yandex.com

### ISSUE THREAD

**Issue by baksogen** [AlexxIT/YandexStation#552]
Перестал работать компонент ( в стране забанили yandex.ru )

Нашел решение без VPN и прокси:
в файлах _utils.py, yandex_quasar.py, yandex_session.py_ автозаменой поменял все "**yandex.ru**" на "**yandex.com**".
И после этого обязательно перезапуск  HA
Предложение автору: Сделать в настроках компонента выбор используемого домена "yandex.ru" или "yandex.com".
Возможно в дальнейшем список зеркал расширится... Время такое

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.16.0
