### ISSUE TITLE
Не интегрируются в ХА объекты УДЯ с классом "Вентиляция"

### ISSUE THREAD

**Issue by baradetsky** [AlexxIT/YandexStation#557]
Не получается добавить в ХА устройства из УДЯ если им присвоен класс "Вентиляция". Когда ставишь класс "Розетка" то устройства пробрасываются и работают без проблем. Меняешь им класс на "Вентиляция" - перестают работать. Если удалить их из интеграции в ХА - не добавляются через incude, также не добавляются через кнопку "настроить" в интеграции (хотя в полях выбора их видно)
![image](https://github.com/user-attachments/assets/0c515246-d142-4de6-9d84-9b550e23f360)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/issues/539
