### ISSUE TITLE
Несколько станций

### ISSUE THREAD

**Issue by alexanderznamensky** [AlexxIT/YandexStation#56]
При использовании 2 Яндекс.мини и Яндекс.станции не возможно выключить ни одну мини колонку. Также не отображается на одной мини колонке ковер (artwork: full-cover):
![image](https://user-images.githubusercontent.com/65254375/92442426-88d29500-f1b8-11ea-9b50-21ce1df8ef98.png)

**Comment by kevinblo** [comment]
Точно такая же конфигурация. Все работает.

![yast](https://user-images.githubusercontent.com/64250142/92443255-ef0be780-f1b9-11ea-92c9-1b95c5289a34.jpeg)

**Comment by alexanderznamensky** [comment]
спасибо....

а не поделитесь своим конфигом? у меня, возможно, руки кривые - только недавно начал с НА разбираться )
у меня вот так прописано в ui-lovelace.yaml:
          - entity: media_player.yandex_station_342****
            type: 'custom:mini-media-player'
            artwork: full-cover
            tts:
              platform: alice
            shortcuts:
              columns: 6
              attribute: sound_mode
              buttons:
                - icon: 'mdi:voice'
                  id: Произнеси текст
                  type: sound_mode
                - icon: 'mdi:google-assistant'
                  id: Выполни команду
                  type: sound_mode
                - icon: 'mdi:playlist-star'
                  id: включи мою любимую музыку вперемешку
                  type: command
                - icon: 'mdi:playlist-music'
                  id: включи плейлист дня
                  type: command
                - icon: 'mdi:heart'
                  id: лайк
                  type: command
                - icon: 'mdi:heart-off'
                  id: снять лайк
                  type: command

          - entity: media_player.yandex_station_ff9****a21
            type: 'custom:mini-media-player'
            artwork: full-cover
            tts:
              platform: alice
            shortcuts:
              attribute: sound_mode
              columns: 6
              buttons:
                - icon: 'mdi:voice'
                  id: Произнеси текст
                  type: sound_mode
                - icon: 'mdi:google-assistant'
                  id: Выполни команду
                  type: sound_mode
                - icon: 'mdi:playlist-star'
                  id: включи мою любимую музыку вперемешку
                  type: command
                - icon: 'mdi:playlist-music'
                  id: включи плейлист дня
                  type: command
                - icon: 'mdi:heart'
                  id: лайк
                  type: command
                - icon: 'mdi:heart-off'
                  id: снять лайк
                  type: command

          - entity: media_player.yandex_station_ff9****a1
            type: 'custom:mini-media-player'
            artwork: full-cover
            tts:
              platform: alice
            shortcuts:
              columns: 6
              attribute: sound_mode
              buttons:
                - icon: 'mdi:voice'
                  id: Произнеси текст
                  type: sound_mode
                - icon: 'mdi:google-assistant'
                  id: Выполни команду
                  type: sound_mode
                - icon: 'mdi:playlist-star'
                  id: включи мою любимую музыку вперемешку
                  type: command
                - icon: 'mdi:playlist-music'
                  id: включи плейлист дня
                  type: command
                - icon: 'mdi:heart'
                  id: лайк
                  type: command
                - icon: 'mdi:heart-off'
                  id: снять лайк
                  type: command

**Comment by AlexxIT** [comment]
Что значит "невозможно выключить"? Всё ещё повторяется?

**Comment by alexanderznamensky** [comment]
Алексей, приветствую!

Вы мне объяснили, что "на большой станции есть команда "на главный экран". Потому что у неё может быть экран. Он работает как стоп. На мини нет этой команды. Невозможно сделать стоп. Голосовая команда Стоп на самом деле ставит на паузу". Поэтому на маленьких станциях после нажатия на стоп / паузу все равно светится ковер той музыки, которую слушали последнюю.

Что качается проблемы с отсутствием кавера на одной из маленьких колонок, то проблема пропала после одного из обновлений.

Сделал видео, но сюда его отправить не получается. Если нужно, могу в ТГ отправить.
![Screenshot 2020-11-23 09 55 18](https://user-images.githubusercontent.com/65254375/99935671-44e03c80-2d72-11eb-9f01-8019779baf01.png)

Спасибо.

**Comment by AlexxIT** [comment]
Ну если всё работает, закрываю
