### ISSUE TITLE
Возможность получать/устанавливать будильники

### ISSUE THREAD

**Issue by Valen13776** [AlexxIT/YandexStation#560]
Добрый день.
Было бы удобно проверять и устанавливать будильники на станции.

**Comment by AlexxIT** [comment]
Получайте/устанавливайте https://github.com/AlexxIT/YandexStation?tab=readme-ov-file#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%BE%D0%B2-%D0%BE%D1%82-%D0%BA%D0%BE%D0%BB%D0%BE%D0%BD%D0%BA%D0%B8

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.17.0
