### ISSUE TITLE
Проблема "устройство сначала должно быть включено" при использовании интеграции кондиционеров Haier

### ISSUE THREAD

**Issue by forester62** [AlexxIT/YandexStation#561]
Устройства нормально залетели в HA (AS07TT5HRA и AS09TT5HRA), но нормально использовать интеграцию было нельзя:
при попытке сразу включить какой-нибудь режим вылетала ошибка AssertionError: {'request_id': '5e2210dc-653f-42d8-ae06-433c6bc6b2ad', 'status': 'error', 'code': 'DEVICE_OFF', 'message': 'Сначала нужно включить устройство'}, устройство переходило в нужный режим, но потом отваливалось в оффлайн в умном доме яндекса и в HA.

В логах было такое
[logs.txt](https://github.com/user-attachments/files/17452038/logs.txt)

В итоге чатгпт предложил такой рабочий вариант
  ```
  async def async_set_hvac_mode(self, hvac_mode: HVACMode):    
    # Если режим выключен, выключаем устройство
        if hvac_mode == HVACMode.OFF:
            await self.quasar.device_action(self.device, "on", False)
            self._attr_hvac_mode = HVACMode.OFF  # Явно обновляем состояние
            self._async_write_ha_state()  # Обновляем состояние в Home Assistant
            return
        
        # Если устройство выключено, включаем его
        if self._attr_hvac_mode == HVACMode.OFF:
            await self.quasar.device_action(self.device, "on", True)
            await asyncio.sleep(2)  # Ждем, пока устройство включится
        
        # Устанавливаем требуемый режим
        await self.quasar.device_action(self.device, self.hvac_instance, str(hvac_mode))
    
        # Обновляем состояние после изменения режима
        self._attr_hvac_mode = hvac_mode
        self._async_write_ha_state()  # Обновляем состояние в Home Assistant
```

**Comment by andrewindXXL** [comment]
Здравствуйте! Аналогичная история. Кондиционеры AS25PHP3HRA и AS20PHP3HRA.
Где нужно прописать данный код?

**Comment by AlexxIT** [comment]
Покажите диагностику устройства

**Comment by andrewindXXL** [comment]
[yandex_station-01JCJ39NZ78QRXGKWGHGWHCSPM-Кондиционер-24e81da3d88a589035856ae3060962c5.json](https://github.com/user-attachments/files/17827624/yandex_station-01JCJ39NZ78QRXGKWGHGWHCSPM-.-24e81da3d88a589035856ae3060962c5.json)

Прописал предлагаемый выше код в climate.py и все заработало.

**Comment by AlexxIT** [comment]
Ну сейчас интеграция делает почти тоже самое. Только sleep нету. Не знаю, насколько 2 секунды целесообразно.

Код с слепой установкой состояния устройства я добалять не буду. Это совсем неправильный подход.
Устройство должно само сообщить своё новое состояние. Иначе интерфейс будет не соответствовать фактическому состоянию устройства.

**Comment by andrewindXXL** [comment]
Как скажете, но если вернуть код обратно, то после включения кондиционера автоматизацией, он отваливается в УДЯ и HA. Может, это только Haier касается, но тем не менее...
[log1.txt](https://github.com/user-attachments/files/17829766/log1.txt)
[log2.txt](https://github.com/user-attachments/files/17829767/log2.txt)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.17.0

**Comment by andrewindXXL** [comment]
Увы, с Haier не работает. Устройство включается и отваливается.
[log1a.txt](https://github.com/user-attachments/files/17849425/log1a.txt)
[log2a.txt](https://github.com/user-attachments/files/17849426/log2a.txt)

**Comment by AlexxIT** [comment]
Попробуйте последнюю мастер-версию

**Comment by andrewindXXL** [comment]
Я пробовал на 3.17.0 (последние логи с нее). Есть еще какая-то? Я тут не совсем все понимаю. Недавно пользуюсь.

**Comment by AlexxIT** [comment]
10 минут назад был фикс. Можете или скачать репозиторий вручную. Или обновить только один файл - `climate.py`

**Comment by andrewindXXL** [comment]
Сегодня все отработало без ошибок! Кондиционер не отвалился!

**Comment by AlexxIT** [comment]
Сегодня это с последними обновлениями из репозитория? Можно релизить?

**Comment by andrewindXXL** [comment]
Да, первый раз. А вечером - опять ошибка ((
[log3.txt](https://github.com/user-attachments/files/17880433/log3.txt)

**Comment by AlexxIT** [comment]
Ошибка 403 это ошибка авторизации. Не знаю, откуда она тут взялась, но непосредственно с управлением кондиционером она не связана

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.17.1

**Comment by andrewindXXL** [comment]
Да, все работает, все команды выполняются. Только в HA и УДЯ статус устройства не обновляется. Например, автоматизация его выключила, а в УДЯ и HA он включен. В УДЯ нужно принудительно зайти в кондиционер, тогда статус обновится и после обновления в УДЯ сразу обновляется в HA.

**Comment by AlexxIT** [comment]
Для таких проблемных устройств есть сервис - `homeassistant.update_entity`.
