### ISSUE TITLE
Unsupported url при попытке запустить плейлист по ссылке

### ISSUE THREAD

**Issue by volsk997** [AlexxIT/YandexStation#562]
При попытке запустить плейлист по ссылке в логах сыпет:

> Unsupported url: https://music.yandex.ru/users/<мой_id>/playlists/1000
> Unsupported url: https://music.yandex.ru/users/music.partners/playlists/2050 **_(плейлист из доки)_**

Версия компонента: 3.16.0

Трек, альбом, исполнитель по доке включаются.
Так же требуемый плейлист включается голосом на колонке

**Comment by varrcan** [comment]
На старой версии компонента также, проблема существует уже давно.

```
Регистратор: custom_components.yandex_station.core.yandex_station
Источник: custom_components/yandex_station/core/yandex_station.py:787
Unsupported url: https://music.yandex.ru/users/username/playlists/1012
```

Версия v3.15.1


![img04112024e855](https://github.com/user-attachments/assets/8a9242b0-2b8c-479d-aa02-47b12d5b6b0a)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.17.0
