### ISSUE TITLE
локальный режим и ошибка 429 too many requests

### ISSUE THREAD

**Issue by guntex** [AlexxIT/YandexStation#566]
на мини 2.поколения и миди станциях нет локального режима и в логах появляется такая ошибка.использую прокси,так как живу в Латвии. является ли эта ошибка причиной отсутствия локального режима и как ее исправить?
![yandexstation](https://github.com/user-attachments/assets/4593c165-f1a1-48eb-b52c-64b07d812c77)
![Ekrānuzņēmums 2024-10-25 180016](https://github.com/user-attachments/assets/1af9f469-b553-4abf-a2bf-1c481f98fbc7)

**Comment by AlexxIT** [comment]
Является. А что вы там закрасили? Это HTTP адрес прокси с логином и паролем?

**Comment by guntex** [comment]
да , именно так.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.17.0
