### ISSUE TITLE
Ошибка в Logs - Не могу запустить Яндекс станцию

### ISSUE THREAD

**Issue by rkiller2006** [AlexxIT/YandexStation#57]
Logs:
Log Details (ERROR)
Logger: homeassistant
Source: custom_components/yandex_station/yandex_glagol.py:52
First occurred: 4:49:51 PM (1 occurrences)
Last logged: 4:49:51 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_glagol.py", line 74, in _connect
    await self.refresh_device_token(session)
  File "/config/custom_components/yandex_station/yandex_glagol.py", line 52, in refresh_device_token
    assert resp['status'] == 'ok', resp
AssertionError: {'message': "Device with id '***************' not found for user '*********'", 'status': 'error'}

**Comment by rkiller2006** [comment]
Configuration.yaml
#Yandex station
yandex_station:
  username: !secret yandex_login
  password: !secret yandex_password
  tts_service_name: alice_say
  devices:
    !secret yandex_station_device_id:  # device_id вашей колонки
      host: 192.168.1.107
      name: Яндекс Станция  # имя можно задать и тут
  token: !secret yandexOAuth_token

**Comment by AlexxIT** [comment]
Уберите `token` из конфига и удалите файл `.yandex_station.json` в папке конфига и перезапустите ХА.

**Comment by rkiller2006** [comment]
Спасибо работает
