### ISSUE TITLE
Conversation doens't return any text via telegram_text automation  

### ISSUE THREAD

**Issue by PeaceByPeace** [AlexxIT/YandexStation#575]
Greetings, there's something strange regarding conversation response variable. When I'm trying to ask something from Alice (non trivial)- telegram always returns "Нет текстового ответа". Firstly, I assumed that there's something went haywire with api but no since when i was trying to put response varibale into notification I got the same answer. Strangly enough, only two patterns seems to be working consistently - "Погода" and "Шутка". Don't know what's wrong but there's nothing in log section which might indicate some sort of issue. I noticed that error was about intent but why?

![image](https://github.com/user-attachments/assets/c62fde8a-7fea-4038-8772-81d57c4ced22)
![image](https://github.com/user-attachments/assets/f27c09b2-bee5-4909-a244-ffeaa14e6a97)
![image](https://github.com/user-attachments/assets/5a0b7236-7fa6-4ff2-8196-3ca9865caf7e)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation?tab=readme-ov-file#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%BE%D0%B2-%D0%BE%D1%82-%D0%BA%D0%BE%D0%BB%D0%BE%D0%BD%D0%BA%D0%B8
