### ISSUE TITLE
Нет календаря у станции

### ISSUE THREAD

**Issue by Valen13776** [AlexxIT/YandexStation#576]
Добрый день.
У устройства Станция, нет объекта календарь.
![Screenshot 2024-11-21 144130](https://github.com/user-attachments/assets/75d8a460-bd7e-47c5-b42c-2d18ee945a76)
![Screenshot 2024-11-21 1443325](https://github.com/user-attachments/assets/c6c82fe0-82f7-48f9-a0d8-ad58eb640068)

**Comment by AlexxIT** [comment]
Покажите диагностику устройства

**Comment by Deniom3** [comment]
Добрый день.
Та же самая проблема на одном HA есть календари на станциях а во второй локации не появилось, переустановка и переподключение не помогло.

Файл диагностики:
[yandex_station-01JD7F9DQPHAN37G8Z8W0DZERD-Станция лайт-39e648adfdf655f9d5781fef8a963f3b.json](https://github.com/user-attachments/files/17846775/yandex_station-01JD7F9DQPHAN37G8Z8W0DZERD-.-39e648adfdf655f9d5781fef8a963f3b.json)

**Comment by AlexxIT** [comment]
А аккаунт и сами станции на обоих HA одинаковые?

**Comment by AlexxIT** [comment]
Нашёл проблему. Календари работают только у пользователей, которые что-то забирают из облака Яндекса (настройка include).

Поправил в мастер-версии. Пока нет следующего релиза - можно или её скачать, или забрать в ХА какое-то устройство.

**Comment by EvgenyBash** [comment]
Спрошу здесь, станция только будильники в календаре отображает? А напоминания получается не отображает?

**Comment by AlexxIT** [comment]
Напоминания сложная штука. Одно напоминание может быть привязано к нескольким станциям. Там концептуально непонятно как с ними лучше работать

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.17.1
