### ISSUE TITLE
Перестал адекватно работать кондиционер под ИК управлением через Яндекс Хаб

### ISSUE THREAD

**Issue by Leviann** [AlexxIT/YandexStation#577]
На версии [v3.17.0 - 2024-11-21](https://github.com/AlexxIT/YandexStation/releases/tag/v3.17.0) при попытке включить кондиционер через изменение режима HVAC с "выключено" на любой другой - происходит отправка ИК сигнала только на смену режима, сам кондиционер не включается. Получается, что для включения кондиционера нужно дополнительно отправлять команду вкл/выкл.

Откатился на версию [v3.16.0 - 2024-10-15](https://github.com/AlexxIT/YandexStation/releases/tag/v3.16.0) - такой проблемы нет.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.17.1

**Comment by Leviann** [comment]
Спасибо!
