### ISSUE TITLE
Использование шаблонов в ответах алисы на intent

### ISSUE THREAD

**Issue by kolayuk** [AlexxIT/YandexStation#58]
При попытке использовать значение шаблона в ответе на интент - алиса просто зачитывает название сенсора, например
```
yandex_station:
  username: myuser@yandex.ru
  password: my password
  intents:
    Открой шторы: ага
    Закрой шторы: окей, закрываю
    Какая температура в спальне: В спальне {{ states('sensor.0x00158d0003cd3909_temperature') }} градусов
```

Городить костыли с автоматизацией с реакцией на интент и вызовом скрипта с TTS (чтобы там дернуть через data_template) - мне кажется оверкилл для такой простой задачи как кастомный алиас на чтение сенсора, было бы круто если бы значения перед отдачей в алису шаблонизировались

**Comment by AlexxIT** [comment]
Вот тут подробности. Я всеми руками за более простой способ, но это технически невозможно при текущих API Яндекса

https://t.me/AlexxIT_SmartHome/362
