### ISSUE TITLE
Проблема интеграции Yamaha MusicCast 

### ISSUE THREAD

**Issue by kilkams** [AlexxIT/YandexStation#582]
Приветствую. Спасибо за отличный компонент. Установлены последние версии HA и интеграции. Пробую настроить стриминг музыки. При произнесении фразы  "Алиса, включи трансляцию на Ямаху" отвечает, что устройства с типом камера не найдено. В источниках есть только "Выполнить команду" и "Воспроизвести текст".
Попробовал прописать в конфиге отдельно плееры из musicCast через 
yandex_station:
  media_players:

, ничего не изменилось. Что я делаю не так?

**Comment by AlexxIT** [comment]
Чтоб трансляция включалась голосом - настраивается отдельно и вручную. 
Вы смотрите не на список источников.

**Comment by kilkams** [comment]
у меня есть 2 колонки, подключенные через MusicCast.
На всякий случай прописываю их в конфиге 
yandex_station:
  media_players:
    - entity_id: media_player.vannaia
      name: Ванная
    - entity_id: media_player.kukhnia
      name: Кухня
      
в источниках колонок есть только такой список. ![image](https://github.com/user-attachments/assets/197a3921-53f3-4368-ac36-1a3452dfb558) источника у колонки не вижу. Можно подробнее узнать, где должен появиться источник?

на всякий случай оборудование
Yandex Лайт 1-е поколение
Yamaha wxa-50

**Comment by AlexxIT** [comment]
Список источников нужно смотреть у колонки, а не на принимающей стороне. Не логично конечно, но ХА не умеет иначе.

**Comment by kilkams** [comment]
Entity media_player.yandex_station_l00pzb000dn43n does not support this service.
при попытке сменить источник на колонке через media_player.select_source.

**Comment by AlexxIT** [comment]
Возможно у вас колонка не работает в локальном режиме

**Comment by kilkams** [comment]
я могу отправлять команды на колонку и TTS из HA. для этого не используется локальный режим?

**Comment by kilkams** [comment]
есть список колонок, поддерживающий локальный режим? моя станция частично поддерживает, но на сколько этого достаточно, не понятно. я и с mDNS поковырялся, и в одну сеть все положил, но не заводится работа по локальному режиму. если нужна другая колонка, то хотелось бы сразу брать подходящую.

**Comment by AlexxIT** [comment]
Все колонки бренда Яндекс его поддерживают. Если у вас оно не работает - проблемы на стороне сети или настройки ХА/сервера.

**Comment by kilkams** [comment]
music_token не мог обновить. решение. Не удаляя интеграцию заново добавить и выбрать авторизация по QR коду. Ребутнуть НА и локальный режим заработал. завтра буду трансляцию тестировать.

**Comment by kilkams** [comment]
все работает, спасибо.
