### ISSUE TITLE
Автоматизация по будильнику

### ISSUE THREAD

**Issue by DIMMonchik** [AlexxIT/YandexStation#583]
Сделал автоматизацию, которая бы открывала шторы после срабатывания будильника, с таким триггером: 
event: end
offset: "-0:0:0"
entity_id: calendar.yandex_station_x11m1d300kn9ge_calendar
trigger: calendar
Но он не хочет срабатывать. Если создаю триггер по другому календарю (созданный мной), то всё ОК. В чём может быть связана такая проблема?

**Comment by AlexxIT** [comment]
В документации ответов нет?
https://github.com/AlexxIT/YandexStation?tab=readme-ov-file#%D0%B1%D1%83%D0%B4%D0%B8%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA%D0%B8

**Comment by DIMMonchik** [comment]
Спасибо за помощь, но получается, что будильник на станции запускается позже, чем событие календаря.

**Comment by AlexxIT** [comment]
Не очень понимаю о чём вы. Вы настроили срабатывание триггера на минуту ПОСЛЕ будильника.
При этом триггер должен быть создан и ХА должен быть запущен за 15 минут ДО срабатывания будильника, иначе триггер вообще не подхватится.
