### ISSUE TITLE
Задержка при получении команд от станции

### ISSUE THREAD

**Issue by maffinca69** [AlexxIT/YandexStation#584]
При использовании этой интеграции или похожей yandex-station-intents возникает задержка около 1-1.5с после распознавания голоса. То есть событие в HA появляется спустя 1-1.5с после распознавания голоса, дальше все без задержек. При этом сама автоматизация вручную работает без всяких задержек

Еще примечательно то, что при использовании облака (обращение к серверам вендоров) задержка раза в 2 меньше. Может проблема с конфигурацией самого HA (docker)? Как вообще можно определить из-за чего именно проблема?
Нагрузка на роутер минимальная, сервер в простое

**Comment by AlexxIT** [comment]
Не очень понимаю, в каком именно месте задержка.

**Comment by maffinca69** [comment]
У меня абсолютно тот же вопрос. Я пересмотрел логи контейнера HA, логи роутера, но так и не понял где именно задержка
Ощущение, что задержка либо на уровне интеграции и она долго обрабатывает то, что отправляет колонка, либо это какие-то сетевые проблемы. Хотел как раз спросить куда можно посмотреть или у кого спросить? 

И общий вопрос: может это нормальное поведение? Или при локальном режиме команд задержка должна быть меньше, чем при работе по облаку?

**Comment by AlexxIT** [comment]
Да я вообще не понимаю, про какой момент использования интеграции вы говорите.

**Comment by maffinca69** [comment]
Использование команд по типу "Алиса, включи свет в гостинной"
https://github.com/AlexxIT/YandexStation?tab=readme-ov-file#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4-%D0%BE%D1%82-%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D0%B8

**Comment by AlexxIT** [comment]
И каким событием вы пользуетесь?

**Comment by maffinca69** [comment]
Использовал и yandex_scenario, и yandex_speaker. Задержка одинаково большая

**Comment by AlexxIT** [comment]
Эти события совершенно не связаны с локальным протоколом. Я не помню существенных задержек в своих тестах. Как будет время - попробую ещё раз. Возможно в Яндексе что-то поменялось.

**Comment by AlexxIT** [comment]
Я потестировал `yandex_speaker`. Он может быть немного быстрее `yandex_scenario`. Задержка сравнима с обычным сценарием "прочитай текст вслух". Алиса также отвечает порядка 1-1.5 секунд после фразы. Может на доли секунды быстрее. В целом Алиса стала заметно медленнее, чем была несколько лет назад.
