### ISSUE TITLE
HA 0.115.2  и Компонент

### ISSUE THREAD

**Issue by 2andr** [AlexxIT/YandexStation#59]
Вопрос по совместимости компонента с новой версией HA 0.115.2

В lovelace вижу медиа плеер (Станция)
Работает:
- реакция на кнопки play/pause
- регулировка уровня громкости

Но Станция Не реагирует:
- запуск скриптов yandex_tts1, yandex_tts2, yandex_tts3
- отправку текста через поле "Воспроизвести текст"

После попытки запуска скриптов yandex_tts*, в логе появляется ошибка
```
Logger: homeassistant.helpers.service
Source: helpers/service.py:427
First occurred: 16:27:01 (3 occurrences)
Last logged: 16:27:04

Unable to find referenced entities media_player.yandex_station
Home Assistant работает!
```

При этом в панели разработчиков все колонки имеют обозначение типа:
media_player.yandex_station_6*****************8f

Может в этом проблема?
Или проблема в кривых руках?

![2020-09-20_16-34-00](https://user-images.githubusercontent.com/6235964/93712557-4cf7e200-fb5f-11ea-82bf-467d9a216da2.png)

**Comment by AlexxIT** [comment]
В автоматизациях у вас указан entity_id `media_player.yandex_station`. Но у колонок он `media_player.yandex_station_...`

**Comment by 2andr** [comment]
спасибо, а почему не работает 
"Воспроизвести текст" из карточки плеера станции ?

**Comment by AlexxIT** [comment]
Потому что два tts в конфиге. В readme есть описание как чинить
