### ISSUE TITLE
Эх! Под "IRBIS A" бы!

### ISSUE THREAD

**Issue by drdic** [AlexxIT/YandexStation#6]
Приветствую! Пользуюсь 4-мя колонками IRBIS A. Хочется таки прикрутить к HA tts от Яндекса. Планируется под колонки IRBIS?

**Comment by AlexxIT** [comment]
Все вопросы к Яндексу. Со стороны компонента все колонки поддерживаются. А вот сами колонки не поддерживают пока эти API.

**Comment by drdic** [comment]
Подскажи, какие именно API должны поддерживать колонки. Напишу в поддержку Яндекс.Алиса. Совсем недавно с ними общался.

**Comment by AlexxIT** [comment]
Это неофициальные API, неизвестно кем найденные. Я не знаю их название.

**Comment by varakirill** [comment]
Кстати, с Яндекс Модулем - работает.

**Comment by AlexxIT** [comment]
@varakirill полноценно работает? Можно добавлять в ридми?

**Comment by varakirill** [comment]
@AlexxIT полноценно пока нет возможности удаленно проверить. Вижу, что определился аналогично "большой" станции media_player.yandex_station_айди, атрибуты тоже как у станции, supported_features: 83727 также. Попробую проверить полноценность работы в субботу.

**Comment by 3err0** [comment]
Поддерживаю, не хватает подержки данной колонки.
Буду с нетерпением ждать реализации.

**Comment by AlexxIT** [comment]
@3err0 от себя я сделал всё возможное, теперь шаг за Яндексом.

**Comment by varakirill** [comment]
> @varakirill полноценно работает? Можно добавлять в ридми?

Проверил модуль, работает полноценно. Звук выводится только по HDMI и переключатель Станция-HDMI не отображается (что логично для модуля, т.к. там нет динамиков и звук только по HDMI).
