### ISSUE TITLE
The following integrations and platforms could not be set up:  yandex_station

### ISSUE THREAD

**Issue by Silent4831** [AlexxIT/YandexStation#61]
Привет! Подскажи пожалуйста, в чем соль этой ошибки? Ставлю твою интеграцию не в первый раз, до этого все работало, и тут мне пришлось передобавлять в акк колонку, соответственно в ха тоже. Думал может проблема в двухфакторке, но нет, поставил статический пароль, все равно ошибка.
![2020-09-27_23-37-52](https://user-images.githubusercontent.com/37260995/94375182-83fb6400-011a-11eb-9546-3631eb4e7489.png)

**Comment by AlexxIT** [comment]
В любой непонятной ситуации нужно удалить файл `.yandex_station.json`
