### ISSUE TITLE
Станция определяется только если стереть файл manifest.js

### ISSUE THREAD

**Issue by alextsakunov** [AlexxIT/YandexStation#63]
Очень странный баг. Колонка яндекс мини. Сначала долго не мог настроить, потому что колонка работала день в HA, а потом терялась (видимо что-то с токеном). Чинилось удалением всех токенов и получением новых.
Потом оказалось, что вместо этого можно просто удалить файл manifest.js и все работает долго и без сбоев. Причем при каждом обновлении этот файл появляется снова, колонка теряется, я его удаляю и живу дальше с новой версией.
Я далек от программирования, но сама логика этого действия мне кажется странной.

**Comment by AlexxIT** [comment]
Посмотрите логи на предмет ошибок. В manifest есть зависимости. Возможно они у вас не ставятся. venv?
