### ISSUE TITLE
The following integrations and platforms could not be set up:  yandex_station

### ISSUE THREAD

**Issue by NMGAndy** [AlexxIT/YandexStation#67]
В логах:

2020-10-21 18:46:04 ERROR (MainThread) [custom_components.yandex_station.yandex_quasar] Init
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 99, in init
    await self.add_scenario(device_id)
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 300, in add_scenario
    assert resp['status'] == 'ok', resp
AssertionError: {'request_id': '828677f8-28fd-44ae-81a2-eafb3586eb28', 'status': 'error', 'code': 'INVALID_VALUE', 'message': 'Команда Алисе должна содержать не менее двух букв'}
2020-10-21 18:46:04 ERROR (MainThread) [homeassistant.setup] Error during setup of component yandex_station
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/yandex_station/__init__.py", line 151, in async_setup
    for speaker in speakers:
TypeError: 'NoneType' object is not iterable

В конфиге только логин и одноразовый пароль (включена двухфакторная авторизация)

**Comment by AlexxIT** [comment]
А что в конфиге? `intents` есть?

**Comment by Antonisiy** [comment]
@AlexxIT, @NMGAndy  как мне кажется, эта проблема вызвана изменениями со стороны Яндекса. Сегодня сам столкнулся с ней при установке.
Проблема заключается в том, что нельзя создать сценарий пустышку с **value = "-"**, так как значение меньше двух символов.
Я изменил это значение на **"инит"** или, я думаю, можно изменить на любое другое слово длиннее 2 символов, и все заработало.
Изменял файл **yandex_quasar.py**, **строка 291**.

![bug](https://user-images.githubusercontent.com/22480818/96754155-91360680-13d9-11eb-963c-f11603388a33.jpg)

**Comment by AlexeyHimki** [comment]
Плюс теперь перестало работать произношение символа градуса. Т.е. раньше Алиса нормально произносила "пять градусов" для строки "5°". Теперь выдает ошибку:
**Команда Алисе может содержать только кириллицу, латиницу, цифры и спецсимволы: "-,!.:=?".**

**Comment by AlexxIT** [comment]
Поправлено в последнем релизе

**Comment by AlexeyHimki** [comment]
К сожалению, подтвердить не могу. Поставил релиз v2.2.11, очистил кэш, проценты, градусы - не пропускает. Прежняя ошибка. Это новое ограничение?

**Comment by AlexxIT** [comment]
@AlexeyHimki поправлена ошибка про "не менее 2х букв". А ваши ошибки не поправить. Это Яндекс ввел ограничения. Блог мой в Телеге читаете? :)
