### ISSUE TITLE
Проблема с шаблонами

### ISSUE THREAD

**Issue by dreem2001** [AlexxIT/YandexStation#68]
Добрый день.

Обнаружил, что тепперь модуль ругается на использование шаблона и Алиса прсто молчит 
Даже самый простой шаблон вида:
```  alias: Yandex tells
  trigger:
  - platform: event
    event_type: yandex_intent
  action:
  - data_template:
      message: "Температура на улице {{states('sensor.temperature_158d0002739f4b')|round}}°С"
```
порождает ошибку:
```
Logger: homeassistant.components.automation.yandex_tells
Source: custom_components/yandex_station/yandex_quasar.py:370
Integration: Automation (documentation, issues)
First occurred: 4:38:51 PM (34 occurrences)
Last logged: 4:53:15 PM

Yandex tells: Error executing script. Unexpected error for call_service at pos 1: {'request_id': 'a0866646-6c6b-48d9-8faa-45b95e29dcd4', 'status': 'error', 'code': 'INVALID_VALUE', 'message': 'Команда Алисе может содержать только кириллицу, латиницу, цифры и спецсимволы: "-,!.:=?".'}
.........................................
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 247, in _async_step
    await getattr(
.................................
AssertionError: {'request_id': 'c214323d-3c39-42d7-a2fc-40ae787f3dcd', 'status': 'error', 'code': 'INVALID_VALUE', 'message': 'Команда Алисе может содержать только кириллицу, латиницу, цифры и спецсимволы: "-,!.:=?".'}
```
Так же, очевидно, по этой же причине интенты не регистрируются в яндексе, если в ответе стоит sil[<500>] (взято из тикета с зависанием на точке, что вылечило проблему)

**Comment by ArgoHA** [comment]
Тоже самое у меня
С обновлением посыпались автоматизации с той же ошибкой
Еще вот что выяснил:
"This is a  test" - это не работает
"This is a test" - это работает

Разница в двух пробелах. Если в тесте есть два проблема, то алиса падает с той же ошибкой...

`  - service: media_player.play_media
    entity_id: media_player.yandex_mini
    data:
      media_content_id: This is a  test
      media_content_type: text`

А в моих template создается два проблема в одном месте, наверное по этому и падает

**Comment by AlexxIT** [comment]
@ArgoHA я есть в Телеграме. Очень интересное наблюдение, спасибо

**Comment by zubikovap** [comment]
Посыпалось воспроизведение с любыми эффектами и звуками.
Работает: 
Температура на улице {{ states("sensor.0x00158d00057341ab_temperature")|round }}

Не работает: 
<speaker effect="megaphone">Закройте дверь
<speaker audio="alice-music-horn-1.opus"> <speaker audio="alice-sounds-things-water-1.opus">

**Comment by vindataproducts-buildmaster** [comment]
@zubikovap А какая версия HASSIO и модуля? У меня шаблоны в принципе падают, а вот тест говорит любой. Так же два пробела, как и говорил @ArgoHA 
Последняя рабочая версия была 2.2.8, так как 2.2.9 уже возвращает ошибку с кириллицей. 
2.2.8 тоже не работает - просто не говорит, ошибок не возвращает никаких, как и HASSIO. В общем, тупик :)

**Comment by AlexxIT** [comment]
@vindataproducts-buildmaster локальные колонки в режиме dialog всё ещё не имеют ограничений на символы

**Comment by dreem2001** [comment]
@AlexxIT а вы планируете это подфиксить, или это ограничение не модуля? Спасибо.

**Comment by AlexxIT** [comment]
@dreem2001 это ограничения Яндекса. Чтоб быть в курсе последних новостей - читайте канал в Телеграм.

**Comment by zubikovap** [comment]
Правильно ли я понимаю, что:
1) шаблоны со звуками и эффектами работают сейчас только через колонки с локальным управлением
2) шансов, что заработает через облачное управление - практически нет

**Comment by AlexxIT** [comment]
1. Да
2. Только если Яндекс этого захочет

**Comment by zubikovap** [comment]
Спасибо!

**Comment by dreem2001** [comment]
Спасибо за ответ. Я вот только не понял одного момента: ведь {{ .... }} это шаблон Jinja2 в HASSIO и именно движок должен его разресолвить в кириллический текст, цифры и тд  иуже их отдать в дальше в модуль. А выглядит так, что вся эта конструкцию пытается уйти в яндекс и разумеется, там не принимают ничего кроме кириллицы. Не проблема ли это HASSIO?
Извините, если это обсуждалось в телеграмме. Я туда еще не дошел, но обязательно дойду :)

**Comment by AlexxIT** [comment]
Если использовать `data_template` вместо `data`, то параметры внутри всегда считаются Jinja2 шаблонами. Это делает не компонент, а сам ХА

**Comment by dreem2001** [comment]
Да, в этом я и был уверен, когда создавал тикет. И ХА замечательно отрабатывает и шаблоны. Однако атоматизация такого вида:
```- id: 'yandex-01'
  alias: Yandex tells
  trigger:
  - platform: event
    event_type: yandex_intent
  action:
  - data_template:
      message: "Температура на улице {{states('sensor.temperature_158d0002739f4b')|round}}°С"
    service: tts.yandex_station_say
  mode: single
```
Падает с ошибкой:
```Logger: homeassistant.components.automation.yandex_tells
Source: custom_components/yandex_station/yandex_quasar.py:370
Integration: Automation (documentation, issues)
First occurred: 12:33:43 AM (6 occurrences)
Last logged: 2:40:40 PM

Yandex tells: Error executing script. Unexpected error for call_service at pos 1: {'request_id': '4240a550-0f0a-4ea0-93f9-2cd8391638e5', 'status': 'error', 'code': 'INVALID_VALUE', 'message': 'Команда Алисе может содержать только кириллицу, латиницу, цифры и спецсимволы: "-,!.:=?".'}
While executing automation automation.yandex_tells
Yandex tells: Error executing script. Unexpected error for call_service at pos 1: {'request_id': '65af3be9-128a-4013-ba5b-b5af51ef6738', 'status': 'error', 'code': 'INVALID_VALUE', 'message': 'Команда Алисе может содержать только кириллицу, латиницу, цифры и спецсимволы: "-,!.:=?".'}
Yandex tells: Error executing script. Unexpected error for call_service at pos 1: {'request_id': 'cf4ca11b-80fa-463f-a739-11c0965052c7', 'status': 'error', 'code': 'INVALID_VALUE', 'message': 'Команда Алисе может содержать только кириллицу, латиницу, цифры и спецсимволы: "-,!.:=?".'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/yandex_station/__init__.py", line 144, in yandex_station_say
    await hass.services.async_call(DOMAIN_MP, SERVICE_PLAY_MEDIA, data,
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 482, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 519, in _handle_entity_call
    await result
  File "/config/custom_components/yandex_station/media_player.py", line 430, in async_play_media
    await self.quasar.send(self.device, media_id, is_tts=True)
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 370, in send
    assert resp['status'] == 'ok', resp
AssertionError: {'request_id': '4240a550-0f0a-4ea0-93f9-2cd8391638e5', 'status': 'error', 'code': 'INVALID_VALUE', 'message': 'Команда Алисе может содержать только кириллицу, латиницу, цифры и спецсимволы: "-,!.:=?".'}
```
Это собственно и был изначальный вопрос. 
Я слабо представляю, как это работает со стороны питона и есть подозрение, что это проблема ХА, но это началось с обновлением компонента, я так же факт то, что шаблоны работают в других автоматизациях без проблем.
Есть ли вероятность, что какие-то изменения компонента стали внезапно несовместимы с ХА?
Или я вообще один с такой странной проблемой? 
Спасибо.

**Comment by zubikovap** [comment]
У меня вот такой скрипт прекрасно работает.

yandex_kuh:
  alias: temp ylica
  sequence:
  - service: tts.yandex_station_say
    entity_id: media_player.yandex_station_583242236568992****
    data_template:
      message: Температура на улице {{ states("sensor.0x00158d00057341ab_temperature")|round }}

**Comment by zubikovap** [comment]
Вот такой скрипт у меня прекрасно работает

`yandex_kuh:
  alias: temp ylica
  sequence:
  - service: tts.yandex_station_say
    entity_id: media_player.yandex_station_5832422365689925451
    data_template:
      message: Температура на улице {{ states("sensor.0x00158d00057341ab_temperature")|round }}`

**Comment by zubikovap** [comment]
Вот такой скрипт у меня прекрасно работает

```
yandex_kuh:
  alias: temp ylica
  sequence:
  - service: tts.yandex_station_say
    entity_id: media_player.yandex_station_583242236568992****
    data_template:
      message: Температура на улице {{ states("sensor.0x00158d00057341ab_temperature")|round }}
```

**Comment by dreem2001** [comment]
@zubikovap а колонка подключена локлаьно, или через облако?

**Comment by AlexxIT** [comment]
Сервис tts всегда отправляет через облако

**Comment by dreem2001** [comment]
@ArgoHA У вас та же проблема: в data_template для tts Алисы падают с ошибкой с ограничениями по кириллице? Или у вас проблема c произношением латиницы?

**Comment by zubikovap** [comment]
У меня - DEXP Smartbox - только облачное управление

**Comment by dreem2001** [comment]
Проблема была действительно в шаблоне.  В debug режиме логов компонента ясно видно, что ХА правильно ресолвит шаблон в кирилический текст. А проблема была в знаке градусов, котрый внезапно перестал поддерживаться, и о чем собственно намекала ошибка, но кто их читает...
В общем, сам дурак... :) Закрываю тикет. 
Спасибо всем за помощь.
