### ISSUE TITLE
Обложки и информация о песне в docker (Решено)

### ISSUE THREAD

**Issue by cweater** [AlexxIT/YandexStation#69]
сейчас работает на малине в докере отлично, но при запуске с полностью аналогичными настройками в докере на nas synology информацию прокидывает только о статусе. Управление и tts работает, но ощущение, что не прокинут порт и нет обмена с яндекс (или откуда он там все это  берет) 

вот что в атрибутах объекта : 

sound_mode_list:
  - Произнеси текст
  - Выполни команду
volume_level: 0.25
is_volume_muted: false
sound_mode: Выполни команду
entity_picture_local: null
friendly_name: Яндекс Мини
supported_features: 83901

для сравнения в малине: 

sound_mode_list:
  - Произнеси текст
  - Выполни команду
volume_level: 0.11
is_volume_muted: false
media_content_type: music
media_duration: 157.41
media_position: 26
media_position_updated_at: '2020-10-23T17:47:21.545837+00:00'
media_title: ОЙ
media_artist: SQWOZ BAB
sound_mode: Выполни команду
entity_picture_local: >-
  /api/media_player_proxy/media_player.yandex_station_ID
token=X&cache=Y
alice_state: IDLE
friendly_name: Яндекс Мини
icon: 'yandex:station-mini'
entity_picture: >-
  https://avatars.yandex.net/get-music-content/2480468/b0f1c429.a.10699710-1/400x400
supported_features: 83903

**Comment by ASMfreaK** [comment]
Я не очень знаю подробности, но, возможно, нужно сделать, чтобы контейнер находился в хостовой сети (network: host)

**Comment by cweater** [comment]
> Я не очень знаю подробности, но, возможно, нужно сделать, чтобы контейнер находился в хостовой сети (network: host)

yeah! Это действительно сработало, я думал открыть порт, но в хост сети заработало, правда не нашел как изменить сеть (всеми правдами и не правдами), поэтому переустановил контейнер)) Из пушки по воробушкам, так сказать
