### ISSUE TITLE
Авторизация Яндекс ПДД и второй фактор

### ISSUE THREAD

**Issue by Gurskiy** [AlexxIT/YandexStation#7]
Приветствую, как правильно авторизовываться, если я использую свой домен и двухфакторную авторизацию?

>   File "/config/custom_components/yandex_station/utils.py", line 43, in get_yandex_token
> 
>     return r.json()['access_token']
> 
> KeyError: 'access_token'

**Comment by avdeevsv91** [comment]
У меня тоже была такая же ошибка, но как оказалось, для авторизации нужно использовать не основной пароль аккаунта, а сгенерированный через Я.Ключ (что на самом деле логично).

**Comment by skorolenko** [comment]
> У меня тоже была такая же ошибка, но как оказалось, для авторизации нужно использовать не основной пароль аккаунта, а сгенерированный через Я.Ключ (что на самом деле логично).

Да, зайти то можно используя временный пароль, только вы же не будете каждый раз пароль менять перед перезагрузкой? Нужно как то выйти из этой ситуации. Возможно хранить полученный OAuth и не входить повторно, если уже был вход? Можно решить как то эту проблему? Кстати получил сам OAuth и в настройках прописал его, что бы входить не через логин пароль, но почему то не хочет он это делать, выдает ошибку.

**Comment by Beetle-II** [comment]
А какие права предоставили?
С помощью пароля получает большой список прав...

**API Яндекс.Паспорта**
Доступ к дате рождения
Доступ к логину, имени и фамилии, полу
Доступ к адресу электронной почты
**Яндекс.Музыка**
Изменение плейлистов
Каталог Яндекс.Музыки
Чтение плейлистов
**Яндекс.Диск WebDAV API**
Доступ к Яндекс.Диску для приложений
**Яндекс.Паспорт**
Привязка адресов электронной почты
Доступ к профилям от социальных сетей, хранящихся на Яндексе
Привязка телефона
**Media Sync API**
Пульт для Yandex.IO-устройств
**Мобильные Яндекс-приложения**
Доступ к личным данным пользователя на сервисах Яндекса из мобильных приложений
**Яндекс.Store**
Доступ к API Яндекс.Store для Android-разработчиков

**Comment by remarkua** [comment]
И все таки, как быть с двухфакторной авторизацией?
Отключать?

**Comment by AlexxIT** [comment]
@remarkua я проверял двухфакторку со второй версией компонента. Она работает по одноразовым ключам из приложения ЯКлюч.

**Comment by avdeevsv91** [comment]
Аналогично. Все отлично подцепилось по одноразовому ключу.
