### ISSUE TITLE
Отключается локальный режим

### ISSUE THREAD

**Issue by dmamontov** [AlexxIT/YandexStation#73]
При отключении Станции от сети(220в) и включении, HA перестает работать с ней в локальном режиме.

Помогает перезагрузка HA.

Можно ли это пофиксить?

**Comment by AlexxIT** [comment]
Проблемы с сетью. Можно зафиксировать IP станции на роутере. Можно дополнительно задать IP станции в конфиге

**Comment by dmamontov** [comment]
У меня IP статический, так же указан и в конфигурации. И данная проблема есть(((

**Comment by AlexxIT** [comment]
Какая модель станции?

**Comment by dmamontov** [comment]
Большая, сейчас заметил еще одну закономерность, у меня по расписанию каждую ночь перезагружается роутер, т.е. все устройства теряют интернет, и после этого плагин не подсоеденяется к станции. Можно конечно попробовать только локальный режим но мне нужна все таки комбинация. 

Грешу на вот эту строчку https://github.com/AlexxIT/YandexStation/blob/master/custom_components/yandex_station/yandex_glagol.py#L150

Думаю стоит добавить что-то на подобе
if timeout > MAX_TIMOUT:
    timeout = MAX_TIMOUT

**Comment by AlexxIT** [comment]
Что-то наподобие и есть в этой строчке, если внимательно посмотреть :)

**Comment by dmamontov** [comment]
Имею ввиду, имею ввиду что стоит вынести в конфигурацию, сейчас число 5 максимальное. Сейчас поставил себе максимальный timeout в 60 секунд, понаблюдаю.

**Comment by dmamontov** [comment]
Разобрался в чем дело. Иногда на команду turn_off станция перестает обрабатывать команды, но соединение не закрывается и соответсвенно реконекта нет.

У меня стояла автоматизация на отключение телевизора и перед ночной перезагрузкой роутера, возвращать на главное меню станцию.

**Comment by AlexxIT** [comment]
Только на эту команду? Возможно после длительного простоя она не ответит на любую команду

**Comment by dmamontov** [comment]
Уточню. Она ее выполняет. И как раз именно после нее перестает выполнять другие команды.
