### ISSUE TITLE
Unsupported media: dialog

### ISSUE THREAD

**Issue by Bruteforce150** [AlexxIT/YandexStation#74]
При использовании третьего способа вывода TTS возникает предупреждение: "Unsupported media: dialog" и яндекс станция мини не произносит текст. Из lovelace и при выборе media_content_type: text(второй способ) - текст произносится. Версия интеграции 2.3.0, версия HA - 0.117.5. Колонка настроена локально.

**Comment by AlexxIT** [comment]
Значит не подключилась локально

**Comment by Bruteforce150** [comment]
Спасибо, помогла перезагрузка станции.
