### ISSUE TITLE
Unsupported url: https://music.yandex.com/album/9303276/track/60302674

### ISSUE THREAD

**Issue by rkiller2006** [AlexxIT/YandexStation#75]
Hello,

I tried to play music on Yandex station and receive a warning and music does not play.

Unsupported url: https://music.yandex.com/album/9303276/track/60302674
1:05:10 PM – YandexStation (WARNING) - message first occurred at 11:32:34 AM and shows up 9 times

My service node has data: 

{
    "media_content_id": "https://music.yandex.com/album/2311403/track/32859874",
    "media_content_type": "music"
}

[<a href="https://ibb.co/HH8r7fM"><img src="https://i.ibb.co/HH8r7fM/2020-11-15-13-11-39.png" alt="2020-11-15-13-11-39" border="0"></a>](url)

What I did wrong?

**Comment by AlexxIT** [comment]
Work only with local speakers. Speaker should show artwork

**Comment by rkiller2006** [comment]
The yandex station works in local mode,

[<a href="https://imgbb.com/"><img src="https://i.ibb.co/b27Ly36/2020-11-16-09-21-25-Overview-Home-Assistant.png" alt="2020-11-16-09-21-25-Overview-Home-Assistant" border="0"></a>](url)

**Comment by AlexxIT** [comment]
Yandex com the problem. Need to use ru

**Comment by rkiller2006** [comment]
Yes, it works. Thanks
