### ISSUE TITLE
Home Assistant Core 0.118.0 error

### ISSUE THREAD

**Issue by igoralexeev** [AlexxIT/YandexStation#76]
stop working with Home Assistant Core 0.118.0

**Comment by db0nd** [comment]
Авторы HA не хотят чинить кастомную интеграцию. 
[https://github.com/home-assistant/core/issues/43425](https://github.com/home-assistant/core/issues/43425)

**Comment by AlexxIT** [comment]
Ну это же не касается моего компонента
@igoralexeev ?

**Comment by db0nd** [comment]
> Ну это же не касается моего компонента
> @igoralexeev ?

Судя по ответу, https://github.com/home-assistant/core/issues/43425#issuecomment-731109377 помощи от разрабов HA ждать не стоит. Компонент можно будет похоронить.

**Comment by Anonym-tsk** [comment]
https://github.com/dmitry-k/yandex_smart_home/issues/116#issuecomment-731429516

**Comment by AlexxIT** [comment]
В любом случае тут история про другой компонент, который писал НЕ я
https://github.com/dmitry-k/yandex_smart_home/

И ошибка НЕ на стороне этого компонента, НЕ на стороне ХА и НЕ на стороне библиотеки aiohttp, вот подробности
https://t.me/c/1337651089/4291

Но я сделал фикс
https://github.com/AlexxIT/yandex_smart_home_fix
