### ISSUE TITLE
Yandex intent на нескольких станциях

### ISSUE THREAD

**Issue by Napalmcold** [AlexxIT/YandexStation#77]
Добрый день!

Есть ли возможность настройки автоматизации, к примеру по озвучиванию температуры, именно на той станции, которую я спросил?

**Comment by AlexxIT** [comment]
1. Если все станции локальные - можно закостылить, поймав какая станция последней что-то сказала.

2. А вообще именно такую задачу решают Яндекс.Диалоги:

https://github.com/AlexxIT/YandexDialogs
