### ISSUE TITLE
Не работает команда "произнеси текст" и "выполни команду" в медиа плеере.

### ISSUE THREAD

**Issue by kurskiev** [AlexxIT/YandexStation#8]
Работает управление громкостью и управление плеером станции. Но не работает команда "произнеси текст" и "выполни команду" в медиа плеере. Мигает зеленым потом красным. Версия: 4134f15
![Снимок](https://user-images.githubusercontent.com/57585398/73958518-0ed3e800-4919-11ea-8630-eb71163e9199.JPG)

**Comment by AlexxIT** [comment]
В конфиге есть другие tts. Читайте readme.

**Comment by AlexxIT** [comment]
PS: хорошая песня ;)

**Comment by kurskiev** [comment]
Все верно, был второй tts гугл. Спасибо.

**Comment by allmoney** [comment]
А как быть, если для гугл колонки надо гугловский tts, а для яндекса свой? Чтобы обе tts были в Home Assistant.

**Comment by AlexxIT** [comment]
Читать ридми. Там именно такой пример.
