### ISSUE TITLE
Поставил последнюю версию и колонка перестала произносить и склонять ° и % в другом (не яндекс) медиаплеере работает.

### ISSUE THREAD

**Issue by SmartHouseServer** [AlexxIT/YandexStation#80]
Пример:

temperature_living_room:
  alias: Какая температура в гостиной?
  sequence:
    - service: media_player.select_sound_mode
      entity_id: media_player.yandex_station_[mac adress]
      data:
        sound_mode: Произнеси текст
    - service: tts.alice_say
      entity_id: media_player.yandex_station_[mac adress]
      data_template:
        message: Температура в гостиной {{ states("sensor.dht_sensor_temperature")|round }} °. Влажность {{ states("sensor.dht_sensor_humidity")|round }} %.

**Comment by SmartHouseServer** [comment]
Может я, что-то недоставил?

**Comment by AlexxIT** [comment]
https://t.me/AlexxIT_SmartHome/363

**Comment by SmartHouseServer** [comment]
Спасибо, за ответ. Запустил локально, работает.

temperature_living_room:
    alias: Какая температура в гостиной?
    sequence:
    - service: media_player.play_media
      entity_id: media_player.yandex_station_[*******]
      data_template:
        media_content_id: Температура в гостиной {{ states("sensor.dht_sensor_temperature")|round }} °. Влажность {{ states("sensor.dht_sensor_humidity")|round }} %.
        media_content_type: dialog
    - service: yandex_station.send_command
      entity_id: media_player.yandex_station
      data:
        command: stopListening
