### ISSUE TITLE
Ошибка авторизации required_external_or_native

### ISSUE THREAD

**Issue by ikstema** [AlexxIT/YandexStation#83]
При первоначальной настройке в конфигурации прописываю
yandex_station:
  username: xxx
  password: yyy
И после перезагрузки получаю в логах ошибку

`Logger: custom_components.yandex_station.yandex_quasar
Source: custom_components/yandex_station/yandex_quasar.py:177
Integration: YandexStation (documentation)
First occurred: 13:42:48 (1 occurrences)
Last logged: 13:42:48

Init
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 87, in init
    self.main_token = await self.get_main_token(username, password)
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 177, in get_main_token
    assert 'x_token' in resp, resp
AssertionError: {'status': 'error', 'state': 'auth_challenge', 'errors': ['action.required_external_or_native']}`

Двухфакторная авторизация в яндексе не включена.
Подскажите, что я делаю не так?

**Comment by moskovskiy82** [comment]
Тоже самое и у меня. 1 в 1. Пробовал username и краткий и полный с @yandex.ru

**Comment by ikstema** [comment]
В общем я решил проблему авторизацией напрямую через token

**Comment by torquemada163** [comment]
> В общем, я решил проблему авторизацией напрямую через token

Как? Я получил OAuth токен на Яндексе, но все равно та же ошибка:

```
2020-11-30 12:50:00 ERROR (MainThread) [custom_components.yandex_station.yandex_quasar] Init
Traceback (most recent call last):
File "/config/custom_components/yandex_station/yandex_quasar.py", line 90, in init
await self.login(self.main_token['access_token'])
File "/config/custom_components/yandex_station/yandex_quasar.py", line 219, in login
assert resp['status'] == 'ok', resp
AssertionError: {'status': 'error', 'errors': ['oauth_token.invalid']}
2020-11-30 12:50:00 ERROR (MainThread) [homeassistant.setup] Error during setup of component yandex_station
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/config/custom_components/yandex_station/__init__.py", line 158, in async_setup
for speaker in speakers:
TypeError: 'NoneType' object is not iterable
```

**Comment by ikstema** [comment]
> > В общем, я решил проблему авторизацией напрямую через token
> 
> Как? Я получил OAuth токен на Яндексе, но все равно та же ошибка:
> 
> ```
> 2020-11-30 12:50:00 ERROR (MainThread) [custom_components.yandex_station.yandex_quasar] Init
> Traceback (most recent call last):
> File "/config/custom_components/yandex_station/yandex_quasar.py", line 90, in init
> await self.login(self.main_token['access_token'])
> File "/config/custom_components/yandex_station/yandex_quasar.py", line 219, in login
> assert resp['status'] == 'ok', resp
> AssertionError: {'status': 'error', 'errors': ['oauth_token.invalid']}
> 2020-11-30 12:50:00 ERROR (MainThread) [homeassistant.setup] Error during setup of component yandex_station
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
> result = await task
> File "/config/custom_components/yandex_station/__init__.py", line 158, in async_setup
> for speaker in speakers:
> TypeError: 'NoneType' object is not iterable
> ```

Токен вылавливал Wireshark-ом. Анализируя GETы приложения Яндекс.Музыка на винде.
Токен, который можно получить от Яндекса проствм путем не дает доступа к музыке и устройствам....

**Comment by maxifly** [comment]
То же самое и у меня.
HA 118.4 в  docker-е (если это важно)
так же установлен Yandex Smart Home Fix и Yandex Smart Home .

**Comment by AlexxIT** [comment]
Удаление `.yandex_station.json` не помогает?

**Comment by maxifly** [comment]
> .yandex_station.json

не могу найти этот файл.

**Comment by porox78** [comment]
> Удаление `.yandex_station.json` не помогает?

Не помогает удаление этого файла. Перезапуск ХА заново создает файл .yandex_station.json и вываливается опять эта ошибка.

Init
Traceback (most recent call last):
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 99, in init
    await self.add_scenario(device_id)
  File "/config/custom_components/yandex_station/yandex_quasar.py", line 300, in add_scenario
    assert resp['status'] == 'ok', resp
AssertionError: {'request_id': 'тут был какой-то код', 'status': 'error', 'code': 'INVALID_VALUE', 'message': 'Активационная фраза для сценария уже используется'}

**Comment by maxifly** [comment]
Что интересно, когда я намеряно меняю

>  username

 на неправильный, то ошибка меняется: 

> 'status': 'error', 'errors': ['account.not_found']

**Comment by maxifly** [comment]
> Токен вылавливал Wireshark-ом. Анализируя GETы приложения Яндекс.Музыка на винде.
> Токен, который можно получить от Яндекса проствм путем не дает доступа к музыке и устройствам....

А можно подробнее, как Вы добились именно GET запросов. Я пробовал со Standalone приложением Яндекс.Музыка , но RESTзапросы шли только когда я переключался с музыки на радио и там был только OAuth токен.
И заодно второй вопрос, как переделать код приложения, чтобы авторизация напрямую через токен шла?

**Comment by maxifly** [comment]
Ну всё! решил я проблему.
Дело было в очень старом Яндекс аккаунте (еще времен narod.ru). 
Я завел новый - проблема не проявилась.  Появился файл  ` .yandex_station.json`

Перенес на него все свои настройки, музыку, яндекс-диалоги. Специально удалил   ` .yandex_station.json` и перезагрузил  HA.   ` .yandex_station.json`  создался заново.

Видимо мой старый аккаунт с течением времени мигрировал по кишкам Яндекса и стал для него несколько "чужим".

**Comment by AlexxIT** [comment]
Итак. У кого ошибка `required_external_or_native` - вероятно у вас очень старый аккаунт времён narod и заблокирована двухфакторная авторизация. Проверьте это и пишите в поддержку Яндекс, просите починить двухфакторку.

**Comment by AlexxIT** [comment]
Дальнейшие обсуждения в issue #103
