### ISSUE TITLE
Не работают устройства  добавленные в Яндекс

### ISSUE THREAD

**Issue by almaziphone** [AlexxIT/YandexStation#85]
Привет! Сегодня 00:00 перестали работать устройства. SSL своего сайта обновил. У меня проблема или может на стороне Яндекса? При добавлении устройств в Яндексе, в Hassio уведомляет "Login attempt or request with invalid authentication from 172.30.33.4" 
Home Assistant Core 0.114.4
Operating System  4.12

**Comment by AlexxIT** [comment]
1. Это не проблема ЭТОГО репозитория. Это проблема умного дома Яндекса
2. Но у меня есть фикс. Там написано про новую версию ХА, но теперь он помогает и старым

https://github.com/AlexxIT/yandex_smart_home_fix
