### ISSUE TITLE
Добавить service для обновления Intents.

### ISSUE THREAD

**Issue by Sergey-SRG** [AlexxIT/YandexStation#87]
Как на счет добавить service для обновления Intents из конфига(что бы не перезапускать HA). Было бы очень здорово.

**Comment by Sergey-SRG** [comment]
Походу не кому не нужно кроме я (

**Comment by Sergey-SRG** [comment]
Всё-таки есть надежда!?!?

**Comment by AlexxIT** [comment]
Логика intents заменена новой логикой получения команд от станции:

https://github.com/AlexxIT/YandexStation#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4-%D0%BE%D1%82-%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D0%B8

Старая логика intents остаётся неизменной. При желании есть альтернативный компонент:

https://github.com/dext0r/ha-yandex-station-intents
