### ISSUE TITLE
В мануале не явно прописано как происходит обнаружение media_player yandex station

### ISSUE THREAD

**Issue by tjunussov** [AlexxIT/YandexStation#9]
У меня есть Яндекс.Станция (большая) в одной сети WIFI, 
прописал аккаунт yandex в configuration.yaml как по мануалу, 
но дальше ничего не произошло, перезагружал HA.

Судя по картинке в мануале, у меня в списках entities автоматический должно было появится что то вроде 
> media_player.yandex_station_12345678901234567890

но увы у меня ничего нет кроме моих google_home_mini, да и в логах пишет что, значить плагин установлен норм!

> 2020-02-10 11:19:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for yandex_station which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

затем вот такая штука

> Device 34007890c4084813068c not found in Yandex account.

хотя у себя на телефоне я колонку вижу, колонка работает. ее както поособому надо привязать к аккаунту ?

**Comment by AlexxIT** [comment]
Станция обнаруживается по протоколу Zeroconf (mDNS).
Проблемы могут быть, если в сети не работает Multicast или если для HA закрыты порты, кроме его главного 8123.

**Comment by AlexxIT** [comment]
@tjunussov `Device not found` означает, что в локальной сети есть устройство Яндекса, которое не привязано к указанному вами аккаунту Яндекса.

**Comment by tjunussov** [comment]
создается файл .yandex_connect в папке config там какойто токен, но в списках states я немогу найти entity с названеим yadex_station, 
я правильно веду пойск ? либо мне надо заходить во вкладку integration и далее подключать yandex станцию ?

**Comment by AlexxIT** [comment]
> p.s.s едиственный момент может ли быть елси вначале был введена другая учетка, к которой небыло ничего подвязано, но после я изменил на свою учетку в которой была яндекс станция, могло ли гдето закэшировать сессию со старой учеткой ?

В этом проблема. Удалите файл `.yandex_station.txt` (он скрытый) и перезапустите HA.

**Comment by tjunussov** [comment]
Ура! Получилось, работает! Но теперь второй вопрос, неработает tts, молчит, 
Нужна ли дополнительная настройка yandex_tts ? т.е нужен ли аккаунт в Yandex TTS ?

**Comment by AlexxIT** [comment]
Проигрывать произвольный файл пока не научился.
