### ISSUE TITLE
Проигрывать случайную песню из плейлиста

### ISSUE THREAD

**Issue by allmoney** [AlexxIT/YandexStation#91]
В автоматизации добавил плейлист.
При каждом запуске автоматизации плейлист начинает играть с одной и той же песни 👎 
Пожалуйста, добавьте возможность играть в случайном порядке песню из плейлиста. Пожалуйста!

**Comment by AlexxIT** [comment]
У Яндекса нет этого в API. Можно запустить только текстом "включи плейлист ХХХ вперемешку"

**Comment by allmoney** [comment]
Подскажите, в API так и не появилось? Только через текстовую комманду?

**Comment by AlexxIT** [comment]
Не встречал таких изменений
