### ISSUE TITLE
Яндекс станция макс работает нормально

### ISSUE THREAD

**Issue by Kadett** [AlexxIT/YandexStation#92]
Приобрел яндекс станцию макс. Все работает.

**Comment by mike02spb** [comment]
Подтверждаю, единственное, почему-то не работает вывод на HDMI

**Comment by Sergey-SRG** [comment]
@Kadett @mike02spb подскажите дорогие обладатели сего чуда она научилась телевизор включать через hdmi-cec?

**Comment by mike02spb** [comment]
> @Kadett @mike02spb подскажите дорогие обладатели сего чуда она научилась телевизор включать через hdmi-cec?

Кстати, я не пробовал. Надо будет поэкспериментировать сегодня.

**Comment by Zuz666** [comment]
> Подтверждаю, единственное, почему-то не работает вывод на HDMI

Да, та же проблема, в миниплеере нет переключения на HDMI. Скриптом не пробовал давать команду.

**Comment by Sergey-SRG** [comment]
@all Ну как успехи с макс? Умеет включать тв технологией hdmi-cec?

**Comment by Zuz666** [comment]
> @ALL Ну как успехи с макс? Умеет включать тв технологией hdmi-cec?

Умеет.
