### ISSUE TITLE
Проблема с установкой интеграции 

### ISSUE THREAD

**Issue by pivovarov7089** [AlexxIT/YandexStation#93]
Пытаюсь подключиться к Яндекс.Станции мини через HA, но вот никак HA не видит станцию, в логе пишет "WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: yandex_station", так же через некоторое время пишет: "ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream while finding first packet: "

**Comment by AlexxIT** [comment]
Посмотрите в списке интеграций в GUI

**Comment by pivovarov7089** [comment]
Не знаю как, но сейчас заработало -_- спасибо!
