### ISSUE TITLE
Unsupported media: dialog

### ISSUE THREAD

**Issue by dobriys** [AlexxIT/YandexStation#95]
После обновления Home Assistant до 2020.12.0 версии, в логах появилось вот такое

`Logger: custom_components.yandex_station.media_player
Source: custom_components/yandex_station/media_player.py:481 
Integration: YandexStation (documentation) 
First occurred: 7:48:30 AM (1 occurrences) 
Last logged: 7:48:30 AM

Unsupported media: dialog`

Соответственно Станция перестала выполнять мою автоматизацию. Использую большую колонку.

вот часть моего кода автоматизации

  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.yandex_station_342078968308182b0650
      volume_level: 0.3
  - service: media_player.play_media
    entity_id: media_player.yandex_station_342078968308182b0650
    data:
      media_content_id: <speaker audio="alice-sounds-nature-forest-2.opus">Сегодня {{ ['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'][now().weekday()]
        }}. Сейчас на улице {{states.weather.yandex_weather.attributes['weather_condition']}}.
        Температура {{states.weather.yandex_weather.attributes['temperature']|round}}  градуса.
        Ощущается как {{states.weather.yandex_weather.attributes['feels_like']|round}}.
        Влажность {{states.weather.yandex_weather.attributes['humidity']}}  процентов.
        Давление {{states.weather.yandex_weather.attributes['pressure_mm']}}  миллиметра.
        Ветер {{states.weather.yandex_weather.attributes['wind_speed_ms']}}  метра
        в секунду.
      media_content_type: dialog

**Comment by AlexxIT** [comment]
Дубль #74
