### ISSUE TITLE
Второй аккаунт

### ISSUE THREAD

**Issue by Karsak4747** [AlexxIT/YandexStation#96]
Как добавить колонки привязанные на второй аккаунт?

**Comment by AlexxIT** [comment]
Поддерживается в версии 3

**Comment by dmatora** [comment]
@AlexxIT а как в конфиге второй аккаунт прописывать?
не нашел ни в документации ни в коде

**Comment by AlexxIT** [comment]
Аккаунт добавляется через GUI интеграций
