### ISSUE TITLE
Conversation component rises an error

### ISSUE THREAD

**Issue by nazmang** [AlexxIT/YandexStation#97]
Hi,

Conversation doesn't start with yandex_station 
See errors in log like below
```
2020-12-19 23:16:36 ERROR (MainThread) [homeassistant.helpers.integration_platform] Error processing platform yandex_station.intent
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 41, in _process
    await process_platform(hass, component_name, platform)
  File "/usr/src/homeassistant/homeassistant/components/intent/__init__.py", line 44, in _async_process_intent
    await platform.async_setup_intents(hass)
  File "/config/custom_components/yandex_station/intent.py", line 20, in async_setup_intents
    if 'host' in device or device['platform'].startswith('yandex'):
TypeError: string indices must be integers
````
And as a result, when pressing 'Microphone' button in browser
`2020-12-19 23:26:43 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1796239928] Error handling message: Unknown intent media_player.yandex_station_ffeeccddffssaaxxxxx`

**Comment by itpcss** [comment]
попробовал добавить тоже по инструкции не работает! пишет ошибка и все, алиса не отзывается, + ковсему после недавнего обновления перестала отзываться и в телеграмме, настроено тоже было по инструкции, сейчас не работает, молчит.

**Comment by csrc** [comment]
Точно такая же проблема - после грейда с 2.4 до 3.1 появился intent_2. Избавиться от него не получается (только если на 2,4 откатиться, но там вылазят уже другие ошибки). Так как интеграция Yandex.Station появляется в "настройки>интеграции" сама, видимо из-за того, что все прописано уже конфиге.


`Logger: homeassistant.helpers.integration_platform
Source: custom_components/yandex_station/intent.py:20
First occurred: 4:22:47 (1 occurrences)
Last logged: 4:22:47

Error processing platform yandex_station.intent
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 41, in _process
    await process_platform(hass, component_name, platform)
  File "/usr/src/homeassistant/homeassistant/components/intent/__init__.py", line 44, in _async_process_intent
    await platform.async_setup_intents(hass)
  File "/config/custom_components/yandex_station/intent.py", line 20, in async_setup_intents
    if 'host' in device or device['platform'].startswith('yandex'):
TypeError: string indices must be integers`

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:129
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 4:22:49 (1 occurrences)
Last logged: 4:22:49

[547565521888] Error handling message: Unknown intent media_player.yandex_station_mini34563`

**Comment by csrc** [comment]
Перезалил файл, ХА выдает такие ошибки. 

<pre>Logger: custom_components.yandex_station.media_player
Source: custom_components/yandex_station/media_player.py:566
Integration: Yandex.Station (documentation)
First occurred: 17:33:32 (1 occurrences)
Last logged: 17:33:32

Unsupported media: question:7a35f33a35562e594c56c1d940b5565a
</pre>
<pre>Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:129
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 17:33:34 (1 occurrences)
Last logged: 17:33:34

[547438107664] Error handling message: Error handling media_player.yandex_station_ff98f</pre>

**Comment by AlexxIT** [comment]
@csrc значит колонка не в локальном режиме. Обложки показывает?

**Comment by nazmang** [comment]
> @csrc значит колонка не в локальном режиме. Обложки показывает?

Да
![screen](https://i.paste.pics/30ecfb8c7d8432c8c395d6eb0bdee131.png)

**Comment by itpcss** [comment]
У меня тоже показывает обложку, с телегой общается, была  проблема с телегой, выяснилось что локальный режим пропал, сейчас же локальный режим работает в телеге алиса отвечает, а через Lovelace не работает.
Подскажите что означает в настройках [.+] - это должно быть обязательно после ":", у меня настроено сейчас таким образом:

conversation:
  intents:
    media_player.yandex_station_мой_id_станции: [.+] 

Но с такими настройками выдает сразу ошибку.

**Comment by csrc** [comment]
@AlexxIT да, отображается обложка, все работает. Так же команды с колонки проходят на умный дом - т.е я могу включать/выключать все, что я добавил до бага. И кстати описанное выше @itpcss имеет место быть в версиях > 2.4.

Добился нормальной работы полностью откатившись на 2.4. Второй айдентс не создается, команды из conversation проходят из мобильников и десктопов. Есть реакция на айдентс, настроенные в яндекс.станция. Но баги все равно имеются, я никак не могу понять почему - например через раз выдается обратное сообщение от станции в окно conversation (команды все срабатывают).

**Comment by nazmang** [comment]
У меня с поледней версией заработал, ошибок не вижу, но голосовой ввод все равно на английском. Строчка в конфиге есть
`yandex_station:
  recognition_lang: ru-RU
`

**Comment by csrc** [comment]
@itpcss посмотрите в сервисах в каком порядке у вас идут tts. Если яндексовский первый - должно на русском работать (кеш очень жестокий!!!). Если не первый, то переименуйте его. В документации это очень четко прописано.

**Comment by itpcss** [comment]
ничего не получается, уже почистил КЭШ в хроме, пишет в lovelace - К сожалению, произошла ошибка

Кто нибудь может помочь, правильно ли я указал в настройках, не совсем понятно что означает [.+] должно ли это там быть:
conversation:
  intents:
      media_player.yandex_station_мой_id_станции: [.+]

**Comment by AlexxIT** [comment]
Я дополнительно проверю у себя, позже

**Comment by AlexxIT** [comment]
conversation текстом в последней бете работает. Голосом не пробовал.

https://github.com/AlexxIT/YandexStation/releases/tag/v3.0.2b1

`[.+]` означает, что все фразы conversation надо отправлять на колонку

**Comment by itpcss** [comment]
Обновил до бета версии, теперь все работает, через Lovelace, yandex станция мини, стала отзываться. 
Спасибо.

**Comment by ar4ig** [comment]
не работает русский голосовой ввод
Вот что вводит при слове "привет"
![image](https://user-images.githubusercontent.com/13949729/105555209-f3c0da80-5d19-11eb-8c43-279c0afb8fd4.png)

**Comment by csrc** [comment]
> не работает русский голосовой ввод
> Вот что вводит при слове "привет"
https://github.com/AlexxIT/YandexStation/issues/97#issuecomment-757865653
Проверьте в другом браузере (или инкогнито).

**Comment by DivanX10** [comment]
у меня аналогичная  ошибка. Проверил в браузерах яндекс, google и opera
![yandex](https://user-images.githubusercontent.com/64090632/107423236-26960b80-6b2d-11eb-8b26-7de6c7b860f3.JPG)

В конфиге указал так
![yandex_config](https://user-images.githubusercontent.com/64090632/107425691-5c88bf00-6b30-11eb-8561-7128c8d180d6.jpg)

Музыка играет и обложку показывает после перезагрузки ХА, но если я остановлю музыку, то не могу ее запустить. Стоит снова перезагрузить ХА, то могу включить музыку и так по кругу.

**Comment by AlexxIT** [comment]
Точно версия компонента последняя? 3.0.2?

**Comment by DivanX10** [comment]
Да, это мой косяк, я не обновил версию компонента. Обновил компонент и все заработало. Список покупок, алиса в Lovelace, музыка работает.  Как можно узнать, какая версия компонента у меня стоит? На карточке это не указано.

![яндекс](https://user-images.githubusercontent.com/64090632/107555960-dd0af680-6be8-11eb-96ab-e4bc69276b0c.JPG)

**Comment by AlexxIT** [comment]
Поправлено в последних версиях
