### ISSUE TITLE
Кэшируются ответы для intents

### ISSUE THREAD

**Issue by siriuske** [AlexxIT/YandexStation#99]
Добавил в конфиг для тестов следующие строки
`  intents:
    Покажи сообщение: ага`

После тестов удалил данные строки из конфига, но алиса по-прежнему отвечает на на фразу как было задано в конфиге.
Где кешируются данные ответы и есть ли возможность сбросить кэш?

**Comment by AlexxIT** [comment]
В мобильном приложении Яндекса в сценариях

**Comment by siriuske** [comment]
Отлично, слона то я и не заметил, возможно стоит добавить в reedme.
Спасибо.
